import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { tools } from '../src/agent/toolRegistry.js';
import { selectToolNames } from '../src/agent/SmartToolRouter.js';
import { ReminderStore } from '../src/agent/ReminderStore.js';
import { PinnedNoteStore } from '../src/agent/PinnedNoteStore.js';
import { PermissionPolicy } from '../src/agent/PermissionPolicy.js';
import { WELLBEING_PROFILES } from '../src/agent/wellbeingTools.js';

const must=names=>{for(const name of names)assert.ok(tools[name],`missing tool: ${name}`);};

test('autonomous core exposes more than one hundred structured tools',()=>{assert.ok(Object.keys(tools).length>=120,`expected >=120 tools, got ${Object.keys(tools).length}`);});
test('deep Windows diagnostics and repair tools exist',()=>must(['performance_snapshot','battery_status','disk_health_summary','process_resource_usage','startup_programs','windows_services','recent_system_errors','defender_status','firewall_status','update_history','problem_devices','network_adapters','wifi_status','verify_system_files','scan_windows_image_health','repair_windows_image','repair_system_files','create_restore_point','cleanup_user_temp','open_device_manager','open_event_viewer']));
test('coding agent has branch patch test and recovery tools',()=>must(['inspect_project','project_read_file','project_search_text','project_apply_replacements','project_create_file','project_restore_backup','list_project_scripts','run_project_task','git_create_branch','git_switch_branch','git_commit_files','git_restore_files','node_check_file']));
test('media and local image understanding tools exist',()=>must(['media_info','media_thumbnail','media_extract_audio','media_clip','media_convert','media_folder_catalog','media_find_large','vision_inspect_image_file']));
test('reminder note and wellbeing tools exist',()=>must(['create_reminder','list_reminders','update_reminder','snooze_reminder','complete_reminder','cancel_reminder','remove_reminder','create_pinned_note','list_pinned_notes','search_pinned_notes','update_pinned_note','remove_pinned_note','wellbeing_catalog','schedule_wellbeing','list_wellbeing_schedules']));
test('wellbeing catalog contains at least twenty non-medical profiles',()=>assert.ok(Object.keys(WELLBEING_PROFILES).length>=20));
test('natural Persian routes complex goals to the right specialist tools',()=>{const code=selectToolNames('برو پروژه رو بررسی کن کدشو درست کن تست و بیلد بگیر');assert.ok(code.includes('project_search_text'));assert.ok(code.includes('run_project_task'));const diag=selectToolNames('سیستم خیلی کند شده مصرف رم و خطاهای ویندوز رو بررسی کن');assert.ok(diag.includes('performance_snapshot'));assert.ok(diag.includes('recent_system_errors'));const media=selectToolNames('این فیلم رو بررسی کن و از دقیقه دو یه کلیپ بساز');assert.ok(media.includes('media_info'));assert.ok(media.includes('media_clip'));const note=selectToolNames('این پرامپت رو به عنوان متن مهم پین کن');assert.ok(note.includes('create_pinned_note'));});
test('durable reminder supports update snooze complete and reload',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'bc-reminder-'));try{const a=new ReminderStore({directory}),item=await a.create({message:'کار مهم',dueAt:new Date(Date.now()+60000),category:'test'});await a.update(item.id,{message:'کار خیلی مهم'});await a.snooze(item.id,5);const active=await a.list();assert.equal(active[0].message,'کار خیلی مهم');assert.ok(new Date(active[0].dueAt).getTime()>Date.now());await a.complete(item.id);assert.equal((await a.list()).length,0);const b=new ReminderStore({directory});assert.equal((await b.list({includeDone:true})).length,1);}finally{await fs.rm(directory,{recursive:true,force:true});}});
test('pinned notes survive reload and can be archived',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'bc-note-'));try{const a=new PinnedNoteStore({directory}),item=await a.create({title:'پرامپت',text:'این متن مهم است',tags:['prompt']});assert.equal((await a.search('مهم')).length,1);await a.update(item.id,{pinned:false,archived:true});assert.equal((await a.list()).length,0);const b=new PinnedNoteStore({directory});const all=await b.list({includeArchived:true});assert.equal(all.length,1);assert.equal(all[0].archived,true);}finally{await fs.rm(directory,{recursive:true,force:true});}});
test('autonomous permissions still require confirmation for core-code edits and permanent cleanup',async()=>{const directory=await fs.mkdtemp(path.join(os.tmpdir(),'bc-policy-'));try{const p=new PermissionPolicy({directory});assert.equal(await p.shouldConfirm('project_apply_replacements',{risk:'sensitive'},{}),true);assert.equal(await p.shouldConfirm('git_commit_files',{risk:'sensitive'},{}),true);assert.equal(await p.shouldConfirm('empty_recycle_bin',{risk:'sensitive'},{}),true);assert.equal(await p.shouldConfirm('launch_app',{risk:'low'},{}),false);}finally{await fs.rm(directory,{recursive:true,force:true});}});
