import test from 'node:test';
import assert from 'node:assert/strict';
import { tools,ollamaTools,runTool } from '../src/agent/toolRegistry.js';

test('tool definitions expose valid function schemas',()=>{const defs=ollamaTools();assert.ok(defs.length>=72,`expected >=72 tools, got ${defs.length}`);assert.equal(defs.length,Object.keys(tools).length);assert.ok(defs.every(x=>x.type==='function'&&x.function.name&&x.function.description&&x.function.parameters?.type==='object'));});
test('dynamic registry can expose zero or selected tools',()=>{assert.equal(ollamaTools([]).length,0);const defs=ollamaTools(['get_time','get_volume']);assert.deepEqual(defs.map(x=>x.function.name).sort(),['get_time','get_volume']);});
test('system info returns structured result',async()=>{const r=await runTool('get_system_info',{});assert.equal(r.success,true);assert.equal(r.tool_name,'get_system_info');assert.ok(r.data.totalRamGB>0);assert.ok(r.data.home);});
test('time tool is platform independent',async()=>{const r=await runTool('get_time',{});assert.equal(r.success,true);assert.ok(r.data.iso);});
test('unknown tool is rejected',async()=>{await assert.rejects(()=>runTool('__missing__',{}),/Unknown tool/);});
test('destructive or direct-input tools remain marked sensitive',()=>{for(const name of ['shutdown_pc','restart_pc','sleep_pc','sign_out','install_app','uninstall_app','close_app','write_text_file','delete_path','take_screenshot','type_text','mouse_click','rename_path','move_path','copy_path','create_text_file','append_text_file','upgrade_app','invoke_ui_element','set_ui_value','run_project_task','forget_memory','unprotect_resource'])assert.equal(tools[name].risk,'sensitive',`${name} must be sensitive`);});
test('core desktop capabilities exist',()=>{for(const name of ['get_volume','set_volume','volume_up','volume_down','toggle_mute','get_brightness','set_brightness','media_play_pause','media_next','media_previous','web_search','youtube_search','google_maps_search','find_app','list_installed_apps','launch_app','winget_search','lock_pc','check_windows_update'])assert.ok(tools[name],`missing ${name}`);});
test('advanced computer-use and local vision capabilities exist',()=>{for(const name of ['list_windows','focus_window','type_text','press_key','move_mouse','mouse_click','mouse_scroll','inspect_ui','invoke_ui_element','set_ui_value','vision_inspect_screen'])assert.ok(tools[name],`missing ${name}`);});
test('advanced file and coding capabilities exist',()=>{for(const name of ['rename_path','move_path','copy_path','search_files','create_text_file','append_text_file','open_downloads','open_desktop','inspect_project','run_project_task'])assert.ok(tools[name],`missing ${name}`);});
test('web app and package capabilities exist',()=>{for(const name of ['open_social_web','open_web_search_in_service','list_winget_upgrades','upgrade_app'])assert.ok(tools[name],`missing ${name}`);});
test('research, memory, scheduler and policy capabilities exist',()=>{for(const name of ['live_web_search','read_web_page','wikipedia_search','research_topic','remember_fact','recall_memory','list_recent_memories','update_memory','forget_memory','create_reminder','list_reminders','cancel_reminder','permission_status','set_permission_profile','protect_resource','unprotect_resource'])assert.ok(tools[name],`missing ${name}`);});
test('file and clipboard capabilities exist',()=>{for(const name of ['list_directory','file_info','read_text_file','create_folder','write_text_file','delete_path','open_folder','open_file','copy_to_clipboard','read_clipboard','take_screenshot'])assert.ok(tools[name],`missing ${name}`);});
test('Windows settings shortcuts exist',()=>{for(const name of ['open_display_settings','open_sound_settings','open_bluetooth_settings','open_network_settings','open_apps_settings','open_storage_settings','open_privacy_settings','open_windows_security'])assert.ok(tools[name],`missing ${name}`);});
