import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const quote=s=>String(s??'').replaceAll("'","''");
async function ps(script,timeout=45000){const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout,maxBuffer:8_000_000});return stdout.trim();}
const header="Add-Type -AssemblyName UIAutomationClient; Add-Type -AssemblyName UIAutomationTypes; Add-Type -TypeDefinition @'\nusing System; using System.Runtime.InteropServices; public static class BCWin { [DllImport(\"user32.dll\")] public static extern IntPtr GetForegroundWindow(); }\n'@;";
const rootScript=windowName=>{
  if(windowName){const w=quote(windowName);return header+" $p=Get-Process -ErrorAction SilentlyContinue|Where-Object {$_.MainWindowHandle -ne 0 -and ($_.MainWindowTitle -like '*"+w+"*' -or $_.ProcessName -like '*"+w+"*')}|Select-Object -First 1;if(!$p){throw 'Target window not found'};$h=$p.MainWindowHandle;$root=[System.Windows.Automation.AutomationElement]::FromHandle($h);if(!$root){throw 'Target UI Automation root unavailable'};";}
  return header+" $h=[BCWin]::GetForegroundWindow();if($h -eq [IntPtr]::Zero){throw 'No foreground window'};$root=[System.Windows.Automation.AutomationElement]::FromHandle($h);if(!$root){throw 'Foreground UI Automation root unavailable'};";
};
const findScript=(windowName,name,id)=>{let s=rootScript(windowName)+" $cond=@();";if(name)s+=" $cond += New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::NameProperty,'"+quote(name)+"');";if(id)s+=" $cond += New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::AutomationIdProperty,'"+quote(id)+"');";s+=" if($cond.Count -eq 0){throw 'name or automation_id required'};if($cond.Count -eq 1){$c=$cond[0]}else{$c=New-Object System.Windows.Automation.AndCondition($cond)};$el=$root.FindFirst([System.Windows.Automation.TreeScope]::Descendants,$c);if(!$el){throw 'UI element not found'};";return s;};
export const automationTools={
  inspect_ui:tool('read','Inspect accessible controls in a target Windows app using Microsoft UI Automation. Pass window when known; otherwise the current foreground window is used.',{type:'object',properties:{window:{type:'string'},limit:{type:'number'}},required:[]},async({window='',limit=120})=>{const n=Math.max(10,Math.min(Number(limit)||120,250));let script=rootScript(window);script+=" $all=$root.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition);$out=@();foreach($e in $all){if($out.Count -ge "+n+"){break};try{$r=$e.Current.BoundingRectangle;$rx=$r.X;$ry=$r.Y;$rw=$r.Width;$rh=$r.Height;if([double]::IsNaN($rx)-or[double]::IsInfinity($rx)){$rx=$null}else{$rx=[math]::Round($rx)};if([double]::IsNaN($ry)-or[double]::IsInfinity($ry)){$ry=$null}else{$ry=[math]::Round($ry)};if([double]::IsNaN($rw)-or[double]::IsInfinity($rw)){$rw=$null}else{$rw=[math]::Round($rw)};if([double]::IsNaN($rh)-or[double]::IsInfinity($rh)){$rh=$null}else{$rh=[math]::Round($rh)};$walker=[System.Windows.Automation.TreeWalker]::ControlViewWalker;$parent=$walker.GetParent($e);$out += [pscustomobject]@{name=$e.Current.Name;automationId=$e.Current.AutomationId;parentName=$parent.Current.Name;className=$e.Current.ClassName;helpText=$e.Current.HelpText;controlType=$e.Current.ControlType.ProgrammaticName;enabled=$e.Current.IsEnabled;offscreen=$e.Current.IsOffscreen;x=$rx;y=$ry;width=$rw;height=$rh}}catch{}};$proc='';if($p){$proc=$p.ProcessName};[pscustomobject]@{window=$root.Current.Name;process=$proc;handle=[int64]$h;count=$out.Count;elements=$out}|ConvertTo-Json -Depth 5 -Compress";const raw=await ps(script);return result('inspect_ui',true,'Target UI inspected',JSON.parse(raw));}),
  invoke_ui_element:tool('sensitive','Activate a named accessible control in a target app using UI Automation rather than coordinate guessing',{type:'object',properties:{window:{type:'string'},name:{type:'string'},automation_id:{type:'string'}},required:[]},async({window='',name='',automation_id=''})=>{let script=findScript(window,name,automation_id);script+=" if($el.TryGetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern,[ref]$patt)){$patt.Invoke();'invoke'}elseif($el.TryGetCurrentPattern([System.Windows.Automation.SelectionItemPattern]::Pattern,[ref]$patt)){$patt.Select();'select'}elseif($el.TryGetCurrentPattern([System.Windows.Automation.TogglePattern]::Pattern,[ref]$patt)){$patt.Toggle();'toggle'}elseif($el.TryGetCurrentPattern([System.Windows.Automation.ExpandCollapsePattern]::Pattern,[ref]$patt)){$patt.Expand();'expand'}else{throw 'No supported activation pattern'}";const raw=await ps(script);return result('invoke_ui_element',true,'UI element activated',{method:raw,window,name,automation_id});}),
  set_ui_value:tool('sensitive','Set text/value of an accessible input control in a target app through UI Automation',{type:'object',properties:{window:{type:'string'},name:{type:'string'},automation_id:{type:'string'},value:{type:'string'}},required:['value']},async({window='',name='',automation_id='',value})=>{let script=findScript(window,name,automation_id);script+=" if(!$el.Current.IsEnabled){throw 'Element disabled'};if($el.TryGetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern,[ref]$patt)){if($patt.Current.IsReadOnly){throw 'Element is read-only'};$patt.SetValue('"+quote(value)+"')}else{throw 'ValuePattern unavailable'}";await ps(script);return result('set_ui_value',true,'UI value set',{window,name,automation_id});})
};
