import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const quote=s=>String(s??'').replaceAll("'","''");
async function ps(script,timeout=45000){const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{windowsHide:true,timeout,maxBuffer:8_000_000});return stdout.trim();}
const prefix=`Add-Type -AssemblyName UIAutomationClient; Add-Type -AssemblyName UIAutomationTypes; Add-Type -TypeDefinition @'\nusing System; using System.Runtime.InteropServices; public static class BCWin { [DllImport("user32.dll")] public static extern IntPtr GetForegroundWindow(); }\n'@; $h=[BCWin]::GetForegroundWindow(); if($h -eq [IntPtr]::Zero){throw 'No foreground window'}; $root=[System.Windows.Automation.AutomationElement]::FromHandle($h);`;
const findScript=(name,id)=>`${prefix} $cond=@(); ${name?`$cond += New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::NameProperty,'${quote(name)}');`:''} ${id?`$cond += New-Object System.Windows.Automation.PropertyCondition([System.Windows.Automation.AutomationElement]::AutomationIdProperty,'${quote(id)}');`:''} if($cond.Count -eq 0){throw 'name or automation_id required'}; if($cond.Count -eq 1){$c=$cond[0]}else{$c=New-Object System.Windows.Automation.AndCondition($cond)}; $el=$root.FindFirst([System.Windows.Automation.TreeScope]::Descendants,$c); if(!$el){throw 'UI element not found'};`;
export const automationTools={
  inspect_ui:tool('read','Inspect accessible controls in the foreground Windows application using Microsoft UI Automation. Prefer this before blind mouse clicks',{type:'object',properties:{limit:{type:'number'}},required:[]},async({limit=120})=>{const n=Math.max(10,Math.min(Number(limit)||120,250));const raw=await ps(`${prefix} $all=$root.FindAll([System.Windows.Automation.TreeScope]::Descendants,[System.Windows.Automation.Condition]::TrueCondition); $out=@(); foreach($e in $all){if($out.Count -ge ${n}){break}; try{$r=$e.Current.BoundingRectangle;$out += [pscustomobject]@{name=$e.Current.Name;automationId=$e.Current.AutomationId;controlType=$e.Current.ControlType.ProgrammaticName;enabled=$e.Current.IsEnabled;offscreen=$e.Current.IsOffscreen;x=[math]::Round($r.X);y=[math]::Round($r.Y);width=[math]::Round($r.Width);height=[math]::Round($r.Height)}}catch{}}; [pscustomobject]@{window=$root.Current.Name;count=$out.Count;elements=$out}|ConvertTo-Json -Depth 5 -Compress`);return result('inspect_ui',true,'Foreground UI inspected',JSON.parse(raw));}),
  invoke_ui_element:tool('sensitive','Activate a named accessible control in the foreground app using UI Automation rather than coordinate guessing',{type:'object',properties:{name:{type:'string'},automation_id:{type:'string'}},required:[]},async({name='',automation_id=''})=>{const raw=await ps(`${findScript(name,automation_id)} if($el.TryGetCurrentPattern([System.Windows.Automation.InvokePattern]::Pattern,[ref]$p)){$p.Invoke();'invoke'} elseif($el.TryGetCurrentPattern([System.Windows.Automation.SelectionItemPattern]::Pattern,[ref]$p)){$p.Select();'select'} elseif($el.TryGetCurrentPattern([System.Windows.Automation.TogglePattern]::Pattern,[ref]$p)){$p.Toggle();'toggle'} elseif($el.TryGetCurrentPattern([System.Windows.Automation.ExpandCollapsePattern]::Pattern,[ref]$p)){$p.Expand();'expand'} else{throw 'No supported activation pattern'}`);return result('invoke_ui_element',true,'UI element activated',{method:raw,name,automation_id});}),
  set_ui_value:tool('sensitive','Set text/value of an accessible input control in the foreground app through UI Automation',{type:'object',properties:{name:{type:'string'},automation_id:{type:'string'},value:{type:'string'}},required:['value']},async({name='',automation_id='',value})=>{await ps(`${findScript(name,automation_id)} if(!$el.Current.IsEnabled){throw 'Element disabled'}; if($el.TryGetCurrentPattern([System.Windows.Automation.ValuePattern]::Pattern,[ref]$p)){if($p.Current.IsReadOnly){throw 'Element is read-only'};$p.SetValue('${quote(value)}')}else{throw 'ValuePattern unavailable'}`);return result('set_ui_value',true,'UI value set',{name,automation_id});})
};
