import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile,spawn } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const root=p=>path.resolve(String(p||process.cwd()));
function inside(base,target){const b=root(base),p=path.resolve(b,String(target||''));if(p!==b&&!p.startsWith(b+path.sep))throw new Error('Path escapes project root');return p;}
async function backup(file){try{await fs.access(file);}catch{return null;}const stamp=new Date().toISOString().replace(/[:.]/g,'-'),dst=`${file}.maria-backup-${stamp}`;await fs.copyFile(file,dst);return dst;}
function requireExists(p){try{return !!p&&requireExistsSync(p);}catch{return false;}}
function requireExistsSync(p){try{const fsSync=process.getBuiltinModule('node:fs');return fsSync.existsSync(p);}catch{return false;}}
async function run(cmd,args,cwd,timeout=900000){const {stdout,stderr}=await execFileAsync(cmd,args,{cwd,windowsHide:true,timeout,maxBuffer:20_000_000,env:process.env});return {stdout:stdout.slice(-50000),stderr:stderr.slice(-20000)};}
async function grepDir(base,needle,limit=100){const out=[],skip=new Set(['node_modules','.git','dist','build','coverage','.next','.cache','.venv','venv']);async function walk(dir,d=0){if(d>7||out.length>=limit)return;let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(skip.has(e.name))continue;const p=path.join(dir,e.name);if(e.isDirectory()){await walk(p,d+1);continue;}let s;try{s=await fs.stat(p);if(s.size>1_500_000)continue;}catch{continue;}let text;try{text=await fs.readFile(p,'utf8');}catch{continue;}const lines=text.split(/\r?\n/);for(let i=0;i<lines.length;i++){if(lines[i].toLowerCase().includes(needle.toLowerCase())){out.push({file:path.relative(base,p),line:i+1,text:lines[i].slice(0,500)});if(out.length>=limit)return;}}} }await walk(base);return out;}
export const codingWorkspaceTools={
  project_search_text:tool('read','Search source text recursively inside a local project while skipping dependencies/build outputs',{type:'object',properties:{directory:{type:'string'},query:{type:'string'},limit:{type:'number'}},required:['directory','query']},async({directory,query,limit=100})=>result('project_search_text',true,'Project text search completed',await grepDir(root(directory),String(query),Math.max(1,Math.min(Number(limit)||100,500))))),
  read_project_file:tool('read','Read a UTF-8 project source file by project-relative path',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},max_chars:{type:'number'}},required:['directory','file']},async({directory,file,max_chars=200000})=>{const base=root(directory),p=inside(base,file),s=await fs.stat(p);if(s.size>2_000_000)throw new Error('Source file too large');const text=await fs.readFile(p,'utf8');return result('read_project_file',true,'Project file read',{file:path.relative(base,p),content:text.slice(0,Math.max(1000,Math.min(Number(max_chars)||200000,1_000_000))),truncated:text.length>max_chars});}),
  replace_project_text:tool('sensitive','Replace an exact unique text block in a project source file and create an automatic backup first',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},old_text:{type:'string'},new_text:{type:'string'},expected_occurrences:{type:'number'}},required:['directory','file','old_text','new_text']},async({directory,file,old_text,new_text,expected_occurrences=1})=>{const base=root(directory),p=inside(base,file),text=await fs.readFile(p,'utf8'),old=String(old_text),count=text.split(old).length-1,expected=Math.max(1,Number(expected_occurrences)||1);if(count!==expected)throw new Error(`Expected ${expected} occurrence(s), found ${count}`);const b=await backup(p),next=text.split(old).join(String(new_text));await fs.writeFile(p,next,'utf8');return result('replace_project_text',true,'Project text replaced',{file:path.relative(base,p),backup:b,count});}),
  write_project_file:tool('sensitive','Create or replace a project source file inside the project root with automatic backup when replacing',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},content:{type:'string'}},required:['directory','file','content']},async({directory,file,content})=>{const base=root(directory),p=inside(base,file);await fs.mkdir(path.dirname(p),{recursive:true});const b=await backup(p);await fs.writeFile(p,String(content),'utf8');return result('write_project_file',true,'Project file written',{file:path.relative(base,p),backup:b});}),
  project_quality_task:tool('sensitive','Run one allowlisted project quality command without arbitrary shell: npm lint/typecheck/test/build, pytest, dotnet build/test, or git status/diff',{type:'object',properties:{directory:{type:'string'},task:{type:'string',enum:['npm_lint','npm_typecheck','npm_test','npm_build','pytest','dotnet_build','dotnet_test','git_status','git_diff']}},required:['directory','task']},async({directory,task})=>{const cwd=root(directory),map={npm_lint:['npm.cmd',['run','lint']],npm_typecheck:['npm.cmd',['run','typecheck']],npm_test:['npm.cmd',['test']],npm_build:['npm.cmd',['run','build']],pytest:['python.exe',['-m','pytest','-q']],dotnet_build:['dotnet.exe',['build','--nologo']],dotnet_test:['dotnet.exe',['test','--nologo']],git_status:['git.exe',['status','--short','--branch']],git_diff:['git.exe',['diff','--stat']]};const [cmd,args]=map[task]||[];if(!cmd)throw new Error('Unsupported task');const out=await run(cmd,args,cwd);return result('project_quality_task',true,`${task} completed`,out);}),
  git_create_branch:tool('sensitive','Create and switch to a new local git branch for an isolated coding change',{type:'object',properties:{directory:{type:'string'},branch:{type:'string'}},required:['directory','branch']},async({directory,branch})=>{const name=String(branch).replace(/[^a-zA-Z0-9._\/-]/g,'-').slice(0,100);if(!name)throw new Error('Invalid branch');const out=await run('git.exe',['switch','-c',name],root(directory));return result('git_create_branch',true,'Git branch created',{branch:name,...out});}),
  git_remote_info:tool('read','Show the current Git branch and configured remotes before publishing a project',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>{const cwd=root(directory),branch=(await run('git.exe',['branch','--show-current'],cwd)).stdout.trim(),remotes=(await run('git.exe',['remote','-v'],cwd)).stdout.trim();return result('git_remote_info',true,'Git remote info loaded',{branch,remotes});}),
  open_project_vscode:tool('low','Open this project folder directly in Visual Studio Code',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>{const cwd=root(directory),candidates=[path.join(process.env.LOCALAPPDATA||'','Programs','Microsoft VS Code','Code.exe'),path.join(process.env.PROGRAMFILES||'','Microsoft VS Code','Code.exe')],exe=candidates.find(x=>x&&requireExists(x));if(!exe)return result('open_project_vscode',false,'Visual Studio Code executable not found');const child=spawn(exe,[cwd],{detached:true,stdio:'ignore',windowsHide:false});child.unref();return result('open_project_vscode',true,'Project opened in VS Code',{directory:cwd});}),
  git_commit_changes:tool('sensitive','Commit already modified local project files with a user/task-provided message. Does not push remotely',{type:'object',properties:{directory:{type:'string'},message:{type:'string'}},required:['directory','message']},async({directory,message})=>{const cwd=root(directory);await run('git.exe',['add','-A'],cwd);const out=await run('git.exe',['commit','-m',String(message).slice(0,200)],cwd);return result('git_commit_changes',true,'Local git commit created',out);}),
  git_push_branch:tool('sensitive','Push the current committed branch to an already configured Git remote. Never invent credentials or create a remote silently.',{type:'object',properties:{directory:{type:'string'},remote:{type:'string'},branch:{type:'string'}},required:['directory']},async({directory,remote='origin',branch=''})=>{const cwd=root(directory),safeRemote=String(remote||'origin').replace(/[^a-zA-Z0-9._-]/g,'' )||'origin';let b=String(branch||'').replace(/[^a-zA-Z0-9._\/-]/g,'');if(!b)b=(await run('git.exe',['branch','--show-current'],cwd)).stdout.trim();if(!b)throw new Error('No current Git branch');const remotes=(await run('git.exe',['remote'],cwd)).stdout.split(/\r?\n/).filter(Boolean);if(!remotes.includes(safeRemote))throw new Error(`Git remote not configured: ${safeRemote}`);const out=await run('git.exe',['push','--set-upstream',safeRemote,b],cwd);return result('git_push_branch',true,'Git branch pushed to configured remote',{remote:safeRemote,branch:b,...out});})
};
