import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const resolveDir=d=>path.resolve(String(d||process.cwd()));
const inside=(root,target)=>{const p=path.resolve(root,String(target||'')),rel=path.relative(root,p);if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('Path escapes project root');return p;};
async function run(cmd,args,cwd,timeout=900000){const {stdout,stderr}=await execFileAsync(cmd,args,{cwd,windowsHide:true,timeout,maxBuffer:20_000_000,env:process.env});return {stdout:stdout.slice(-50000),stderr:stderr.slice(-20000)};}
async function projectFiles(root,limit=500){const out=[],skip=new Set(['node_modules','.git','dist','build','coverage','.next','.cache','.venv','venv']);async function walk(dir,depth=0){if(depth>7||out.length>=limit)return;let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){if(skip.has(e.name))continue;const p=path.join(dir,e.name),rel=path.relative(root,p);out.push({path:rel,type:e.isDirectory()?'directory':'file'});if(e.isDirectory())await walk(p,depth+1);if(out.length>=limit)break;}}await walk(root);return out;}
async function packageInfo(root){try{return JSON.parse(await fs.readFile(path.join(root,'package.json'),'utf8'));}catch{return null;}}
export const codingTools={
  inspect_project:tool('read','Inspect a local coding project structure and package metadata without executing arbitrary shell text',{type:'object',properties:{directory:{type:'string'},limit:{type:'number'}},required:['directory']},async({directory,limit=350})=>{const root=resolveDir(directory),files=await projectFiles(root,Math.max(50,Math.min(Number(limit)||350,1000))),pkg=await packageInfo(root);return result('inspect_project',true,'Project inspected',{root,files,package:pkg?{name:pkg.name,scripts:pkg.scripts,dependencies:pkg.dependencies,devDependencies:pkg.devDependencies}:null});}),
  project_read_file:tool('read','Read a UTF-8 source/config file inside a project with size limits',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},max_bytes:{type:'number'}},required:['directory','file']},async({directory,file,max_bytes=400000})=>{const root=resolveDir(directory),p=inside(root,file),s=await fs.stat(p),max=Math.max(1000,Math.min(Number(max_bytes)||400000,2_000_000));if(s.size>max)throw new Error('Project file exceeds read limit');return result('project_read_file',true,'Project file read',{path:path.relative(root,p),content:await fs.readFile(p,'utf8'),size:s.size});}),
  project_search_text:tool('read','Search text across project source files while ignoring dependency/build folders',{type:'object',properties:{directory:{type:'string'},query:{type:'string'},limit:{type:'number'}},required:['directory','query']},async({directory,query,limit=80})=>{const root=resolveDir(directory),files=(await projectFiles(root,1400)).filter(x=>x.type==='file'),needle=String(query||'').toLowerCase(),out=[],max=Math.max(1,Math.min(Number(limit)||80,300));for(const item of files){if(out.length>=max)break;const p=inside(root,item.path);let text='';try{const s=await fs.stat(p);if(s.size>700000)continue;text=await fs.readFile(p,'utf8');}catch{continue;}const lines=text.split(/\r?\n/);for(let i=0;i<lines.length&&out.length<max;i++)if(lines[i].toLowerCase().includes(needle))out.push({file:item.path,line:i+1,text:lines[i].slice(0,500)});}return result('project_search_text',true,'Project text search completed',out);}),
  project_apply_replacements:tool('sensitive','Apply exact text replacements to one project file. Every old_text must exist; optional expected_count protects against ambiguous edits',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},replacements:{type:'array',items:{type:'object',properties:{old_text:{type:'string'},new_text:{type:'string'},expected_count:{type:'number'}},required:['old_text','new_text']}}},required:['directory','file','replacements']},async({directory,file,replacements})=>{const root=resolveDir(directory),p=inside(root,file),before=await fs.readFile(p,'utf8');let next=before,total=0;for(const r of (replacements||[]).slice(0,100)){if(!String(r.old_text||''))throw new Error('old_text cannot be empty');const parts=next.split(String(r.old_text)),count=parts.length-1;if(count===0)throw new Error('Expected text not found');if(Number.isFinite(Number(r.expected_count))&&count!==Number(r.expected_count))throw new Error(`Replacement count mismatch: expected ${r.expected_count}, got ${count}`);next=parts.join(String(r.new_text));total+=count;}if(next===before)return result('project_apply_replacements',true,'No content change was needed',{file:path.relative(root,p),replacements:0});const backup=`${p}.maria-backup`;await fs.copyFile(p,backup);await fs.writeFile(p,next,'utf8');return result('project_apply_replacements',true,'Project file patched',{file:path.relative(root,p),replacements:total,backup});}),
  project_create_file:tool('sensitive','Create a new UTF-8 file inside a project without overwriting an existing file',{type:'object',properties:{directory:{type:'string'},file:{type:'string'},content:{type:'string'}},required:['directory','file','content']},async({directory,file,content})=>{const root=resolveDir(directory),p=inside(root,file);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(content),'utf8',{flag:'wx'});return result('project_create_file',true,'Project file created',{file:path.relative(root,p)});}),
  project_restore_backup:tool('sensitive','Restore a project file from the .maria-backup created by Maria patching',{type:'object',properties:{directory:{type:'string'},file:{type:'string'}},required:['directory','file']},async({directory,file})=>{const root=resolveDir(directory),p=inside(root,file),backup=`${p}.maria-backup`;await fs.copyFile(backup,p);return result('project_restore_backup',true,'Project file restored',{file:path.relative(root,p)});}),
  list_project_scripts:tool('read','List package.json scripts available in a Node project',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>{const root=resolveDir(directory),pkg=await packageInfo(root);return result('list_project_scripts',Boolean(pkg),pkg?'Project scripts listed':'package.json not found',pkg?.scripts||{});}),
  run_project_task:tool('sensitive','Run a safe allowlisted project task: npm install/test/build/lint/typecheck/audit or git status/diff/log',{type:'object',properties:{directory:{type:'string'},task:{type:'string',enum:['npm_install','npm_test','npm_build','npm_lint','npm_typecheck','npm_audit','git_status','git_diff','git_log']}},required:['directory','task']},async({directory,task})=>{const cwd=resolveDir(directory),pkg=await packageInfo(cwd),map={npm_install:['npm.cmd',['install']],npm_test:['npm.cmd',['test']],npm_build:['npm.cmd',['run','build']],npm_lint:['npm.cmd',['run','lint']],npm_typecheck:['npm.cmd',['run','typecheck']],npm_audit:['npm.cmd',['audit','--json']],git_status:['git.exe',['status','--short','--branch']],git_diff:['git.exe',['diff']],git_log:['git.exe',['log','-15','--oneline','--decorate']]};if(task==='npm_lint'&&!pkg?.scripts?.lint)return result('run_project_task',false,'Project has no lint script');if(task==='npm_typecheck'&&!pkg?.scripts?.typecheck)return result('run_project_task',false,'Project has no typecheck script');const [cmd,args]=map[task]||[];if(!cmd)return result('run_project_task',false,'Unsupported task');const out=await run(cmd,args,cwd,task==='npm_install'?1800000:900000);return result('run_project_task',true,`${task} completed`,out);}),
  git_create_branch:tool('sensitive','Create and switch to a new Git branch inside a project',{type:'object',properties:{directory:{type:'string'},branch:{type:'string'}},required:['directory','branch']},async({directory,branch})=>{const name=String(branch||'').trim();if(!/^[A-Za-z0-9._\/-]{1,120}$/.test(name))throw new Error('Invalid branch name');const out=await run('git.exe',['switch','-c',name],resolveDir(directory));return result('git_create_branch',true,'Git branch created',{branch:name,...out});}),
  git_switch_branch:tool('sensitive','Switch to an existing Git branch',{type:'object',properties:{directory:{type:'string'},branch:{type:'string'}},required:['directory','branch']},async({directory,branch})=>{const name=String(branch||'').trim();if(!/^[A-Za-z0-9._\/-]{1,120}$/.test(name))throw new Error('Invalid branch name');const out=await run('git.exe',['switch',name],resolveDir(directory));return result('git_switch_branch',true,'Git branch switched',{branch:name,...out});}),
  git_commit_files:tool('sensitive','Stage an explicit list of project-relative files and create a Git commit with a user-visible message',{type:'object',properties:{directory:{type:'string'},files:{type:'array',items:{type:'string'}},message:{type:'string'}},required:['directory','files','message']},async({directory,files,message})=>{const cwd=resolveDir(directory),safe=(files||[]).slice(0,200).map(f=>path.relative(cwd,inside(cwd,f)));if(!safe.length)throw new Error('No files to commit');await run('git.exe',['add','--',...safe],cwd);const out=await run('git.exe',['commit','-m',String(message).slice(0,300)],cwd);return result('git_commit_files',true,'Git commit created',{files:safe,...out});}),
  git_restore_files:tool('sensitive','Discard uncommitted changes in an explicit list of project files using Git restore',{type:'object',properties:{directory:{type:'string'},files:{type:'array',items:{type:'string'}}},required:['directory','files']},async({directory,files})=>{const cwd=resolveDir(directory),safe=(files||[]).slice(0,200).map(f=>path.relative(cwd,inside(cwd,f)));if(!safe.length)throw new Error('No files to restore');const out=await run('git.exe',['restore','--',...safe],cwd);return result('git_restore_files',true,'Git files restored',{files:safe,...out});}),
  node_check_file:tool('read','Run Node.js syntax checking on a JavaScript file inside a project',{type:'object',properties:{directory:{type:'string'},file:{type:'string'}},required:['directory','file']},async({directory,file})=>{const cwd=resolveDir(directory),p=inside(cwd,file),out=await run(process.execPath,['--check',p],cwd,60000);return result('node_check_file',true,'Node syntax check passed',{file:path.relative(cwd,p),...out});})
};
