import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const downloadsDir=()=>path.join(os.homedir(),'Downloads');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function recent({after=0,extensions=[],limit=30}={}){const dir=downloadsDir(),exts=new Set((extensions||[]).map(x=>String(x).replace(/^\./,'').toLowerCase()).filter(Boolean)),out=[];let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return[];}for(const e of entries){if(!e.isFile()||/\.(crdownload|part|tmp)$/i.test(e.name))continue;const p=path.join(dir,e.name);try{const s=await fs.stat(p),extension=path.extname(e.name).replace(/^\./,'').toLowerCase();if(s.mtimeMs<after)continue;if(exts.size&&!exts.has(extension))continue;out.push({name:e.name,path:p,size:s.size,modified:s.mtime.toISOString(),mtimeMs:s.mtimeMs,extension});}catch{}}return out.sort((a,b)=>b.mtimeMs-a.mtimeMs).slice(0,Math.max(1,Math.min(Number(limit)||30,100)));}
export const downloadTools={
  list_recent_downloads:tool('read','List recent completed files in the current user Downloads folder. Useful after a web download so Maria can use the exact downloaded path instead of guessing.',schema({after_iso:{type:'string'},extensions:{type:'array',items:{type:'string'}},limit:{type:'number'}},[]),async({after_iso='',extensions=[],limit=30})=>{const after=after_iso?Date.parse(after_iso):Date.now()-24*60*60*1000,items=await recent({after:Number.isFinite(after)?after:0,extensions,limit});return result('list_recent_downloads',true,'Recent downloads listed',{directory:downloadsDir(),items});}),
  wait_for_new_download:tool('read','Wait for a newly completed browser download and return its exact local path. Call with after_iso captured before clicking Download; ignores partial .crdownload/.part files.',schema({after_iso:{type:'string'},extensions:{type:'array',items:{type:'string'}},timeout_seconds:{type:'number'}},['after_iso']),async({after_iso,extensions=[],timeout_seconds=45})=>{const after=Date.parse(after_iso);if(!Number.isFinite(after))throw new Error('Valid after_iso is required');const deadline=Date.now()+Math.max(3,Math.min(Number(timeout_seconds)||45,120))*1000;while(Date.now()<deadline){const items=await recent({after,extensions,limit:10});if(items.length)return result('wait_for_new_download',true,'New completed download detected',{directory:downloadsDir(),file:items[0],candidates:items});await sleep(750);}return result('wait_for_new_download',false,'No completed new download appeared before timeout',{directory:downloadsDir(),after_iso});})
};
