import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import dgram from 'node:dgram';
import {openChromeUrl} from './browserTools.js';
import {messengerSupportTools} from './messengerSupportTools.js';

const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
async function ps(script,timeout=30000){const {stdout=''}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout,maxBuffer:3000000});return String(stdout).trim();}
async function openSettings(uri){await execFileAsync('cmd.exe',['/d','/s','/c','start','',uri],{windowsHide:true,timeout:10000});return uri;}
function macBytes(raw){const hex=String(raw||'').replace(/[^0-9a-f]/gi,'');if(hex.length!==12)throw new Error('MAC address must contain 12 hexadecimal digits');return Buffer.from(hex,'hex');}
async function wake(mac,{broadcast='255.255.255.255',port=9}={}){const m=macBytes(mac),packet=Buffer.concat([Buffer.alloc(6,0xff),...Array.from({length:16},()=>m)]),socket=dgram.createSocket('udp4');await new Promise((resolve,reject)=>{socket.bind(()=>{try{socket.setBroadcast(true);socket.send(packet,Number(port)||9,String(broadcast||'255.255.255.255'),err=>err?reject(err):resolve());}catch(e){reject(e);}});});socket.close();return {mac:String(mac),broadcast,port:Number(port)||9,bytes:packet.length};}
const explorerModes={icons:1,small_icons:2,list:3,details:4,thumbnails:5,tiles:6,thumbstrip:7,content:8};
async function explorerView(mode){const n=explorerModes[mode];if(!n)throw new Error('Unsupported Explorer view mode');const script="$s=New-Object -ComObject Shell.Application;$w=@($s.Windows())|Where-Object{$_.FullName -like '*explorer.exe'}|Select-Object -First 1;if(-not $w){throw 'No File Explorer window is open'};$w.Document.CurrentViewMode="+n+";$w.Refresh();$w.LocationURL";const out=await ps(script);return {mode,viewMode:n,location:out};}
async function explorerFlag(name,enabled){const cfg={extensions:{path:'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced',key:'HideFileExt',on:0,off:1},hidden:{path:'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced',key:'Hidden',on:1,off:2}}[name];if(!cfg)throw new Error('Unknown Explorer flag');const value=enabled?cfg.on:cfg.off;const script="Set-ItemProperty -Path '"+cfg.path+"' -Name '"+cfg.key+"' -Value "+value+";$s=New-Object -ComObject Shell.Application;@($s.Windows())|Where-Object{$_.FullName -like '*explorer.exe'}|ForEach-Object{$_.Refresh()}";await ps(script);return {name,enabled:Boolean(enabled)};}
function uniqueRecipients(recipients=[]){const seen=new Set(),out=[];for(const raw of recipients){const name=String(raw||'').trim();if(!name)continue;const key=name.toLocaleLowerCase('fa');if(seen.has(key))continue;seen.add(key);out.push(name);}return out;}

export const extensionTools={
  windows_signin_status:tool('read','Inspect Windows sign-in/Hello availability without reading or exposing any PIN/password/biometric secret',schema({}),async()=>{
    const raw=await ps("$bio=Get-Service WbioSrvc -ErrorAction SilentlyContinue;$pin=Test-Path 'HKCU:\\Software\\Microsoft\\PassportForWork';[pscustomobject]@{BiometricService=[string]$bio.Status;PassportConfig=$pin;User=$env:USERNAME}|ConvertTo-Json -Compress");
    let data={raw};try{data=JSON.parse(raw)}catch{}return result('windows_signin_status',true,'Windows sign-in status inspected',data);
  }),
  windows_signin_options_open:tool('low','Open the official Windows Sign-in options page. PIN/password/Hello secrets remain inside Windows secure UI and are never stored by MARIA.',schema({}),async()=>result('windows_signin_options_open',true,'Windows Sign-in options opened',{uri:await openSettings('ms-settings:signinoptions'),requiresUserSecureEntry:true})),
  windows_pin_change_handoff:tool('sensitive','Start the official Windows PIN/Hello settings handoff. MARIA does not read, store, or type the current/new PIN.',schema({}),async()=>result('windows_pin_change_handoff',true,'PIN/Hello secure flow opened',{uri:await openSettings('ms-settings:signinoptions'),requiresUserSecureEntry:true})),
  windows_hello_face_setup_handoff:tool('sensitive','Open official Windows Hello Face setup. This is OS-managed biometric enrollment; MARIA never reads Windows Hello templates.',schema({}),async()=>result('windows_hello_face_setup_handoff',true,'Windows Hello Face settings opened',{uri:await openSettings('ms-settings:signinoptions'),requiresUserSecureEntry:true})),
  face_identity_backend_status:tool('read','Check real local prerequisites for owner-face identity. Never claims an owner match unless an enrolled local identity backend exists.',schema({}),async()=>{
    const raw=await ps("$cam=Get-PnpDevice -Class Camera -Status OK -ErrorAction SilentlyContinue|Select-Object -First 3 FriendlyName,Status;$bio=Get-Service WbioSrvc -ErrorAction SilentlyContinue;[pscustomobject]@{CameraCount=@($cam).Count;Cameras=@($cam);BiometricService=[string]$bio.Status;CustomOwnerMatcher=$false;LivenessBackend=$false}|ConvertTo-Json -Compress -Depth 4");
    let data={raw};try{data=JSON.parse(raw)}catch{};return result('face_identity_backend_status',true,data.CustomOwnerMatcher?'Owner identity backend ready':'Camera/Hello inspected; custom owner recognition remains disabled until an enrolled local matcher and liveness backend exist.',data);
  }),
  wake_capabilities_inspect:tool('read','Inspect physical network adapters for Wake-on-LAN related power-management properties without changing firmware or adapter settings',schema({}),async()=>{
    const raw=await ps("Get-NetAdapter -Physical -ErrorAction SilentlyContinue|ForEach-Object{$a=$_;$p=Get-NetAdapterPowerManagement -Name $a.Name -ErrorAction SilentlyContinue;[pscustomobject]@{Name=$a.Name;Status=$a.Status;MacAddress=$a.MacAddress;WakeOnMagicPacket=[string]$p.WakeOnMagicPacket;WakeOnPattern=[string]$p.WakeOnPattern}}|ConvertTo-Json -Compress");
    let data=[];try{data=JSON.parse(raw||'[]')}catch{data={raw}}return result('wake_capabilities_inspect',true,'Wake capabilities inspected',data);
  }),
  wake_on_lan_send:tool('sensitive','Send one Wake-on-LAN magic packet to an explicitly supplied MAC/broadcast address. Packet sent is not the same as verified power-on.',schema({mac:{type:'string'},broadcast:{type:'string'},port:{type:'number'}},['mac']),async({mac,broadcast='255.255.255.255',port=9})=>result('wake_on_lan_send',true,'Wake-on-LAN packet sent; target wake is not yet verified',await wake(mac,{broadcast,port}))),
  explorer_view_set:tool('low','Change the currently open File Explorer window presentation only; does not move/delete/rename files.',schema({mode:{type:'string',enum:Object.keys(explorerModes)}},['mode']),async({mode})=>result('explorer_view_set',true,'Explorer view changed',await explorerView(mode))),
  explorer_extensions_show:tool('low','Show or hide filename extensions in File Explorer; does not change files.',schema({enabled:{type:'boolean'}},['enabled']),async({enabled})=>result('explorer_extensions_show',true,enabled?'Filename extensions shown':'Filename extensions hidden',await explorerFlag('extensions',enabled))),
  explorer_hidden_items_show:tool('low','Show or hide hidden items in File Explorer; showing them does not authorize modification of protected files.',schema({enabled:{type:'boolean'}},['enabled']),async({enabled})=>result('explorer_hidden_items_show',true,enabled?'Hidden items shown':'Hidden items hidden',await explorerFlag('hidden',enabled))),
  google_image_search:tool('low','Open a real Google Images results page in the personal Chrome profile. Downloading the actual source image remains a separate verified download step.',schema({query:{type:'string'},profile:{type:'string'}},['query']),async({query,profile='personal'})=>{const text=String(query||'').trim();if(!text)throw new Error('Image query is empty');const url='https://www.google.com/search?tbm=isch&q='+encodeURIComponent(text);return result('google_image_search',true,'Google Images opened',{query:text,...await openChromeUrl(url,{profile})});}),
  telegram_folder_prepare:tool('low','Open Telegram and prepare an explicitly named chat-folder workflow. Folder membership must be inspected from the authorized UI before any send/forward.',schema({folder:{type:'string'},mode:{type:'string',enum:['auto','desktop','web']}},['folder']),async({folder,mode='auto'})=>{const opened=await messengerSupportTools.messenger_open.run({service:'telegram',mode});return result('telegram_folder_prepare',opened.success,'Telegram opened for chat-folder inspection',{folder:String(folder).trim(),opened:opened.data,next:'Use UI inspection to resolve the exact Telegram folder and enumerate chats; do not send yet.'});}),
  recipient_set_preview:tool('read','Build and deduplicate an explicit multi-recipient set before any bulk external send. This tool never sends messages.',schema({recipients:{type:'array',items:{type:'string'}},exclude:{type:'array',items:{type:'string'}}},['recipients']),async({recipients,exclude=[]})=>{const ex=new Set(uniqueRecipients(exclude).map(x=>x.toLocaleLowerCase('fa'))),resolved=uniqueRecipients(recipients).filter(x=>!ex.has(x.toLocaleLowerCase('fa')));return result('recipient_set_preview',true,resolved.length+' explicit recipient(s) prepared; no message sent',{recipients:resolved,count:resolved.length,requiresConfirmationBeforeBulkSend:resolved.length>1});}),
  screen_share_prepare:tool('sensitive','Prepare a live screen-share workflow for an already-authorized meeting/call. Never starts sharing blindly: exact service, call and source must be verified in UI first.',schema({service:{type:'string'},source:{type:'string',enum:['monitor','window','tab']},target:{type:'string'}},['service','source']),async({service,source,target=''})=>result('screen_share_prepare',true,'Screen-share workflow prepared; UI verification and explicit Share commit are still required',{service:String(service),source,target:String(target||''),next:'Inspect exact call UI, select requested source, preview it, then require explicit share commit and verify active sharing indicator.'}))
};
