import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
async function where(exe){try{const {stdout}=await execFileAsync('where.exe',[exe],{windowsHide:true,timeout:10000});return stdout.trim().split(/\r?\n/)[0]||null;}catch{return null;}}
async function ff(name){const p=await where(name);if(!p)throw new Error(`${name} is not installed; run Maria Full Setup`);return p;}
const resolve=p=>path.resolve(String(p));
const mediaExt=/\.(mp4|mkv|mov|avi|webm|m4v|mp3|wav|flac|m4a|aac|ogg|opus|wma)$/i;
export const mediaTools={
  media_info:tool('read','Inspect a local audio/video file with FFprobe: duration, codecs, streams, resolution, bitrate and tags',{type:'object',properties:{file:{type:'string'}},required:['file']},async({file})=>{const input=resolve(file),probe=await ff('ffprobe.exe');const {stdout}=await execFileAsync(probe,['-v','error','-show_format','-show_streams','-of','json',input],{windowsHide:true,timeout:60000,maxBuffer:8_000_000});return result('media_info',true,'Media inspected',JSON.parse(stdout));}),
  media_thumbnail:tool('low','Create a JPEG thumbnail from a local video at a requested second',{type:'object',properties:{file:{type:'string'},output:{type:'string'},second:{type:'number'}},required:['file','output']},async({file,output,second=1})=>{const input=resolve(file),out=resolve(output),bin=await ff('ffmpeg.exe');await fs.mkdir(path.dirname(out),{recursive:true});await execFileAsync(bin,['-y','-ss',String(Math.max(0,Number(second)||0)),'-i',input,'-frames:v','1','-q:v','2',out],{windowsHide:true,timeout:180000,maxBuffer:8_000_000});return result('media_thumbnail',true,'Thumbnail created',{path:out,second:Number(second)||0});}),
  media_extract_audio:tool('sensitive','Extract audio from a local video into MP3 or WAV without modifying the source file',{type:'object',properties:{file:{type:'string'},output:{type:'string'},format:{type:'string',enum:['mp3','wav']}},required:['file','output']},async({file,output,format='mp3'})=>{const input=resolve(file),out=resolve(output),bin=await ff('ffmpeg.exe');await fs.mkdir(path.dirname(out),{recursive:true});const args=format==='wav'?['-y','-i',input,'-vn','-acodec','pcm_s16le',out]:['-y','-i',input,'-vn','-codec:a','libmp3lame','-q:a','2',out];await execFileAsync(bin,args,{windowsHide:true,timeout:1800000,maxBuffer:12_000_000});return result('media_extract_audio',true,'Audio extracted',{path:out,format});}),
  media_clip:tool('sensitive','Create a new video clip from a local media file between start and duration; the source is preserved',{type:'object',properties:{file:{type:'string'},output:{type:'string'},start_seconds:{type:'number'},duration_seconds:{type:'number'}},required:['file','output','start_seconds','duration_seconds']},async({file,output,start_seconds,duration_seconds})=>{const input=resolve(file),out=resolve(output),bin=await ff('ffmpeg.exe');await fs.mkdir(path.dirname(out),{recursive:true});await execFileAsync(bin,['-y','-ss',String(Math.max(0,Number(start_seconds)||0)),'-i',input,'-t',String(Math.max(.1,Number(duration_seconds)||1)),'-c','copy',out],{windowsHide:true,timeout:1800000,maxBuffer:12_000_000});return result('media_clip',true,'Media clip created',{path:out,startSeconds:Number(start_seconds),durationSeconds:Number(duration_seconds)});}),
  media_convert:tool('sensitive','Convert a local media file to mp4, mp3, wav or webm while preserving the source',{type:'object',properties:{file:{type:'string'},output:{type:'string'},format:{type:'string',enum:['mp4','mp3','wav','webm']}},required:['file','output','format']},async({file,output,format})=>{const input=resolve(file),out=resolve(output),bin=await ff('ffmpeg.exe');await fs.mkdir(path.dirname(out),{recursive:true});const map={mp4:['-c:v','libx264','-preset','medium','-crf','20','-c:a','aac'],webm:['-c:v','libvpx-vp9','-crf','30','-b:v','0','-c:a','libopus'],mp3:['-vn','-c:a','libmp3lame','-q:a','2'],wav:['-vn','-c:a','pcm_s16le']};await execFileAsync(bin,['-y','-i',input,...map[format],out],{windowsHide:true,timeout:3600000,maxBuffer:12_000_000});return result('media_convert',true,'Media converted',{path:out,format});}),
  media_folder_catalog:tool('read','Catalog local audio/video files below a folder with size and modified time',{type:'object',properties:{directory:{type:'string'},limit:{type:'number'}},required:['directory']},async({directory,limit=500})=>{const root=resolve(directory),out=[],max=Math.max(10,Math.min(Number(limit)||500,2000));async function walk(dir,depth=0){if(depth>6||out.length>=max)return;let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){const p=path.join(dir,e.name);if(e.isDirectory())await walk(p,depth+1);else if(mediaExt.test(e.name)){try{const s=await fs.stat(p);out.push({name:e.name,path:p,size:s.size,modified:s.mtime.toISOString()});}catch{}}if(out.length>=max)break;}}await walk(root);return result('media_folder_catalog',true,'Media catalog created',out);}),
  media_find_large:tool('read','Find the largest local audio/video files below a folder',{type:'object',properties:{directory:{type:'string'},limit:{type:'number'}},required:['directory']},async({directory,limit=30})=>{const r=await mediaTools.media_folder_catalog.run({directory,limit:2000}),n=Math.max(5,Math.min(Number(limit)||30,100)),items=(r.data||[]).sort((a,b)=>b.size-a.size).slice(0,n);return result('media_find_large',true,'Largest media files listed',items);})
};
