import { memory } from './MemoryStore.js';
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
export const memoryTools={
  remember_fact:tool('low','Remember an important user preference, fact, rule, plan or recurring detail for future conversations',{type:'object',properties:{text:{type:'string'},kind:{type:'string'},importance:{type:'number'},tags:{type:'array',items:{type:'string'}}},required:['text']},async({text,kind='fact',importance=.75,tags=[]})=>{const item=await memory.remember(text,{kind,importance,source:'agent',tags});return result('remember_fact',Boolean(item),item?'Saved to durable local memory':'Nothing saved',item);}),
  recall_memory:tool('read','Recall relevant long-term memories about the user, rules or ongoing plans',{type:'object',properties:{query:{type:'string'},limit:{type:'number'}},required:['query']},async({query,limit=8})=>result('recall_memory',true,'Relevant memories recalled',await memory.recall(query,{limit}))),
  list_recent_memories:tool('read','List recent long-term memories',{type:'object',properties:{limit:{type:'number'}},required:[]},async({limit=30})=>result('list_recent_memories',true,'Recent memories listed',await memory.list(limit))),
  update_memory:tool('low','Correct or update a known memory by id',{type:'object',properties:{id:{type:'string'},text:{type:'string'},kind:{type:'string'},importance:{type:'number'},tags:{type:'array',items:{type:'string'}}},required:['id']},async({id,...changes})=>{const item=await memory.update(id,changes);return result('update_memory',Boolean(item),item?'Memory updated':'Memory not found',item);}),
  forget_memory:tool('sensitive','Forget a specific memory by id or relevant query. This permanently removes remembered information',{type:'object',properties:{id:{type:'string'},query:{type:'string'}},required:[]},async({id,query})=>{if(id){const ok=await memory.remove(id);return result('forget_memory',ok,ok?'Memory forgotten':'Memory not found',{id});}if(query){const count=await memory.removeByQuery(query);return result('forget_memory',count>0,count?`Forgot ${count} matching memories`:'No matching memory found',{count});}return result('forget_memory',false,'Provide id or query');})
};
