import fs from 'node:fs/promises';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { openChromeUrl,chromeProfileForService } from './browserTools.js';
import { automationTools } from './automationTools.js';
import { MessengerDeliveryVerification } from './MessengerDeliveryVerification.js';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const delivery=new MessengerDeliveryVerification({inspect:args=>automationTools.inspect_ui.run(args)});
const appRoots=`@($env:ProgramData+'\\Microsoft\\Windows\\Start Menu\\Programs',$env:APPDATA+'\\Microsoft\\Windows\\Start Menu\\Programs')`;
const serviceNames={telegram:['Telegram'],whatsapp:['WhatsApp'],rubika:['Rubika','روبیکا']};
const webFallback={telegram:'https://web.telegram.org/',whatsapp:'https://web.whatsapp.com/',rubika:'https://web.rubika.ir/'};
const quote=s=>String(s??'').replaceAll("'","''");
async function ps(script,timeout=60000){const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout,maxBuffer:4_000_000});return stdout.trim();}
async function desktopMessenger(key){const names=serviceNames[key];if(!names)throw new Error('Unsupported messenger');const patterns=names.map(n=>`$_.BaseName -like '*${quote(n)}*'`).join(' -or ');const raw=await ps(`$p=${appRoots};$x=Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {${patterns}} | Select-Object -First 1;if($x){Start-Process $x.FullName;$x.FullName}`);return raw||null;}
async function openMessenger(service,mode='auto'){const key=String(service||'').toLowerCase();if(!serviceNames[key])throw new Error('Unsupported messenger');const wanted=String(mode||'auto').toLowerCase(),companyWeb=['whatsapp','rubika'].includes(key);if(wanted==='desktop'||(wanted==='auto'&&!companyWeb)){const target=await desktopMessenger(key);if(target)return {service:key,mode:'desktop',target};if(wanted==='desktop')return {service:key,mode:'missing',target:null};}const url=webFallback[key];if(!url)return {service:key,mode:'missing',target:null};const opened=await openChromeUrl(url,{profile:chromeProfileForService(key)});return {service:key,mode:'web-chrome',target:url,chrome:opened.exe,profile:opened.profile,profileRole:opened.profileRole};}
async function putFilesOnClipboard(files){const resolved=[];for(const f of files||[]){const p=path.resolve(String(f));const s=await fs.stat(p);if(!s.isFile())throw new Error(`Not a file: ${p}`);resolved.push(p);}if(!resolved.length)throw new Error('No files supplied');const arr=resolved.map(x=>`'${quote(x)}'`).join(',');await ps(`Add-Type -AssemblyName System.Windows.Forms;$c=New-Object System.Collections.Specialized.StringCollection;@(${arr})|ForEach-Object{[void]$c.Add($_)};[System.Windows.Forms.Clipboard]::SetFileDropList($c)`);return resolved;}
export const messengerSupportTools={
  messenger_delivery_checkpoint:tool('read','Before sending, verify the destination conversation from accessible UI and capture existing matching sent content. content is the exact message text or attachment filename. If recipient verification fails, do not send.',schema({service:{type:'string',enum:['telegram','whatsapp','rubika']},recipient:{type:'string'},content:{type:'string'},window:{type:'string'}},['service','recipient','content']),async args=>{const data=await delivery.prepare(args);return result('messenger_delivery_checkpoint',true,'چت مقصد برای بررسی ارسال ثبت شد.',data);}),
  messenger_verify_delivery:tool('read','After sending once, check the same destination conversation for NEW matching content with a sent/delivered receipt. Pre-existing messages, drafts and a changed window do not count. Never blindly resend after an uncertain result.',schema({checkpoint:{type:'string'}},['checkpoint']),async({checkpoint})=>{const verification=await delivery.verify(checkpoint);return result('messenger_verify_delivery',verification.verified,verification.reason,{verification});}),
  messenger_open:tool('low','Open Telegram, WhatsApp or Rubika. In auto mode Telegram prefers desktop, while WhatsApp and Rubika intentionally use the company Chrome profile. mode=web forces Chrome; mode=desktop requires the installed app.',schema({service:{type:'string',enum:['telegram','whatsapp','rubika']},mode:{type:'string',enum:['auto','desktop','web']}},['service']),async({service,mode='auto'})=>{const data=await openMessenger(service,mode);return result('messenger_open',data.mode!=='missing',data.mode==='missing'?'Messenger app not found':'Messenger opened',data);}),
  copy_files_to_clipboard:tool('low','Put one or more local files on the Windows file-drop clipboard so a selected chat can receive them with paste',schema({files:{type:'array',items:{type:'string'}}},['files']),async({files})=>result('copy_files_to_clipboard',true,'Files staged on clipboard',{files:await putFilesOnClipboard(files)})),
  messenger_stage_files:tool('low','Open the requested messenger and stage local files on the Windows clipboard. WhatsApp/Rubika auto-route to the company Chrome profile; Telegram auto-prefers desktop. Then use UI inspection/vision to locate and verify the exact chat/contact/group before sending.',schema({service:{type:'string',enum:['telegram','whatsapp','rubika']},files:{type:'array',items:{type:'string'}},mode:{type:'string',enum:['auto','desktop','web']}},['service','files']),async({service,files,mode='auto'})=>{const opened=await openMessenger(service,mode),staged=await putFilesOnClipboard(files);return result('messenger_stage_files',opened.mode!=='missing',opened.mode==='missing'?'Messenger app not found; files are staged':'Messenger opened and files staged',{opened,files:staged,next:'Use UI Automation or vision to verify and select the requested chat/group/folder, then paste and send with existing keyboard/UI tools.'});})
};
