import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const coreAudio=`Add-Type -TypeDefinition @'\nusing System;\nusing System.Runtime.InteropServices;\npublic class BCAudio {\n [ComImport, Guid("BCDE0395-E52F-467C-8E3D-C4579291692E")] class MMDeviceEnumeratorComObject {}\n enum EDataFlow { eRender, eCapture, eAll } enum ERole { eConsole, eMultimedia, eCommunications }\n [Guid("A95664D2-9614-4F35-A746-DE8DB63617E6"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IMMDeviceEnumerator { int NotImpl1(); [PreserveSig] int GetDefaultAudioEndpoint(EDataFlow dataFlow, ERole role, out IMMDevice ppDevice); }\n [Guid("D666063F-1587-4E43-81F1-B948E807363F"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IMMDevice { [PreserveSig] int Activate(ref Guid iid, int dwClsCtx, IntPtr pActivationParams, [MarshalAs(UnmanagedType.IUnknown)] out object ppInterface); }\n [Guid("5CDF2C82-841E-4546-9722-0CF74078229A"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IAudioEndpointVolume { int RegisterControlChangeNotify(IntPtr pNotify); int UnregisterControlChangeNotify(IntPtr pNotify); int GetChannelCount(out uint pnChannelCount); int SetMasterVolumeLevel(float fLevelDB, Guid pguidEventContext); int SetMasterVolumeLevelScalar(float fLevel, Guid pguidEventContext); int GetMasterVolumeLevel(out float pfLevelDB); int GetMasterVolumeLevelScalar(out float pfLevel); int SetChannelVolumeLevel(uint nChannel, float fLevelDB, Guid pguidEventContext); int SetChannelVolumeLevelScalar(uint nChannel, float fLevel, Guid pguidEventContext); int GetChannelVolumeLevel(uint nChannel, out float pfLevelDB); int GetChannelVolumeLevelScalar(uint nChannel, out float pfLevel); int SetMute([MarshalAs(UnmanagedType.Bool)] bool bMute, Guid pguidEventContext); int GetMute(out bool pbMute); }\n static IAudioEndpointVolume Endpoint(){var en=(IMMDeviceEnumerator)(new MMDeviceEnumeratorComObject()); IMMDevice dev; Marshal.ThrowExceptionForHR(en.GetDefaultAudioEndpoint(EDataFlow.eRender,ERole.eMultimedia,out dev)); Guid iid=typeof(IAudioEndpointVolume).GUID; object obj; Marshal.ThrowExceptionForHR(dev.Activate(ref iid,23,IntPtr.Zero,out obj)); return (IAudioEndpointVolume)obj;}\n public static float Get(){float v; Marshal.ThrowExceptionForHR(Endpoint().GetMasterVolumeLevelScalar(out v)); return v;}\n public static void Set(float v){Marshal.ThrowExceptionForHR(Endpoint().SetMasterVolumeLevelScalar(Math.Max(0,Math.Min(1,v)),Guid.Empty));}\n public static bool Muted(){bool m; Marshal.ThrowExceptionForHR(Endpoint().GetMute(out m)); return m;}\n public static void Mute(bool m){Marshal.ThrowExceptionForHR(Endpoint().SetMute(m,Guid.Empty));}\n}\n'@;`;
async function ps(script){const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:30000,maxBuffer:2_000_000});return stdout.trim();}
export const nativeWindowsTools={
  get_volume:tool('read','Read Windows default multimedia endpoint master volume through CoreAudio',{type:'object',properties:{},required:[]},async()=>{const raw=await ps(`${coreAudio} [pscustomobject]@{percent=[math]::Round([BCAudio]::Get()*100);muted=[BCAudio]::Muted()}|ConvertTo-Json -Compress`);return result('get_volume',true,'Master volume read',JSON.parse(raw));}),
  set_volume:tool('low','Set Windows default multimedia endpoint master volume through CoreAudio',{type:'object',properties:{percent:{type:'number'}},required:['percent']},async({percent})=>{const n=Math.round(clamp(percent,0,100));await ps(`${coreAudio} [BCAudio]::Set(${n}/100.0)`);return result('set_volume',true,`Volume set to ${n}%`,{percent:n});}),
  set_mute:tool('low','Set Windows default audio endpoint mute state through CoreAudio',{type:'object',properties:{muted:{type:'boolean'}},required:['muted']},async({muted})=>{const m=Boolean(muted);await ps(`${coreAudio} [BCAudio]::Mute($${m?'true':'false'})`);return result('set_mute',true,m?'Muted':'Unmuted',{muted:m});}),
  toggle_mute:tool('low','Toggle Windows default audio endpoint mute through CoreAudio',{type:'object',properties:{},required:[]},async()=>{const raw=await ps(`${coreAudio} $m=[BCAudio]::Muted();[BCAudio]::Mute(!$m); (!$m).ToString().ToLower()`);return result('toggle_mute',true,'Mute toggled',{muted:raw==='true'});})
};
