import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const empty={type:'object',properties:{},required:[]};
const coreAudio=`Add-Type -TypeDefinition @'\nusing System;\nusing System.Runtime.InteropServices;\npublic class BCAudio {\n [ComImport, Guid("BCDE0395-E52F-467C-8E3D-C4579291692E")] class MMDeviceEnumeratorComObject {}\n enum EDataFlow { eRender, eCapture, eAll } enum ERole { eConsole, eMultimedia, eCommunications }\n [Guid("A95664D2-9614-4F35-A746-DE8DB63617E6"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IMMDeviceEnumerator { int EnumAudioEndpoints(EDataFlow dataFlow, int dwStateMask, IntPtr ppDevices); [PreserveSig] int GetDefaultAudioEndpoint(EDataFlow dataFlow, ERole role, out IMMDevice ppDevice); }\n [Guid("D666063F-1587-4E43-81F1-B948E807363F"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IMMDevice { [PreserveSig] int Activate(ref Guid iid, int dwClsCtx, IntPtr pActivationParams, [MarshalAs(UnmanagedType.IUnknown)] out object ppInterface); }\n [Guid("5CDF2C82-841E-4546-9722-0CF74078229A"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)] interface IAudioEndpointVolume { int RegisterControlChangeNotify(IntPtr pNotify); int UnregisterControlChangeNotify(IntPtr pNotify); int GetChannelCount(out uint pnChannelCount); int SetMasterVolumeLevel(float fLevelDB, Guid pguidEventContext); int SetMasterVolumeLevelScalar(float fLevel, Guid pguidEventContext); int GetMasterVolumeLevel(out float pfLevelDB); int GetMasterVolumeLevelScalar(out float pfLevel); int SetChannelVolumeLevel(uint nChannel, float fLevelDB, Guid pguidEventContext); int SetChannelVolumeLevelScalar(uint nChannel, float fLevel, Guid pguidEventContext); int GetChannelVolumeLevel(uint nChannel, out float pfLevelDB); int GetChannelVolumeLevelScalar(uint nChannel, out float pfLevel); int SetMute([MarshalAs(UnmanagedType.Bool)] bool bMute, Guid pguidEventContext); int GetMute(out bool pbMute); }\n static IAudioEndpointVolume Endpoint(){var en=(IMMDeviceEnumerator)(new MMDeviceEnumeratorComObject()); IMMDevice dev; Marshal.ThrowExceptionForHR(en.GetDefaultAudioEndpoint(EDataFlow.eRender,ERole.eMultimedia,out dev)); Guid iid=typeof(IAudioEndpointVolume).GUID; object obj; Marshal.ThrowExceptionForHR(dev.Activate(ref iid,23,IntPtr.Zero,out obj)); return (IAudioEndpointVolume)obj;}\n public static float Get(){float v; Marshal.ThrowExceptionForHR(Endpoint().GetMasterVolumeLevelScalar(out v)); return v;}\n public static void Set(float v){Marshal.ThrowExceptionForHR(Endpoint().SetMasterVolumeLevelScalar(Math.Max(0,Math.Min(1,v)),Guid.Empty));}\n public static bool Muted(){bool m; Marshal.ThrowExceptionForHR(Endpoint().GetMute(out m)); return m;}\n public static void Mute(bool m){Marshal.ThrowExceptionForHR(Endpoint().SetMute(m,Guid.Empty));}\n}\n'@;`;
async function ps(script,timeout=30000){const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout,maxBuffer:2_000_000});return stdout.trim();}
const mediaVirtualKeys={VOLUME_MUTE:0xAD,VOLUME_DOWN:0xAE,VOLUME_UP:0xAF,MEDIA_NEXT_TRACK:0xB0,MEDIA_PREV_TRACK:0xB1,MEDIA_STOP:0xB2,MEDIA_PLAY_PAUSE:0xB3};
async function mediaKey(key,count=1){const safe=Math.max(1,Math.min(60,Math.round(count))),vk=mediaVirtualKeys[key];if(!vk)throw new Error(`Unsupported media key: ${key}`);await ps(`Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public static class BCMediaKey { [DllImport("user32.dll")] public static extern void keybd_event(byte vk,byte scan,uint flags,UIntPtr extra); }'; 1..${safe}|ForEach-Object{[BCMediaKey]::keybd_event(${vk},0,0,[UIntPtr]::Zero);[BCMediaKey]::keybd_event(${vk},0,2,[UIntPtr]::Zero);Start-Sleep -Milliseconds 15}`);}
async function fallbackSetVolume(percent){const n=Math.round(clamp(percent,0,100));await mediaKey('VOLUME_DOWN',55);if(n>0)await mediaKey('VOLUME_UP',Math.ceil(n/2));return n;}
async function coreVolume(){const raw=await ps(`${coreAudio} [pscustomobject]@{percent=[math]::Round([BCAudio]::Get()*100);muted=[BCAudio]::Muted()}|ConvertTo-Json -Compress`);return JSON.parse(raw);}
async function readBrightness(){const raw=await ps(`Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightness -ErrorAction Stop|Select-Object -First 1 -ExpandProperty CurrentBrightness`);return Number(raw);}
async function writeBrightness(percent){const n=Math.round(clamp(percent,0,100));await ps(`$m=Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightnessMethods -ErrorAction Stop|Select-Object -First 1;Invoke-CimMethod -InputObject $m -MethodName WmiSetBrightness -Arguments @{Timeout=1;Brightness=${n}}|Out-Null`);return n;}
export const nativeWindowsTools={
  get_volume:tool('read','Read Windows default multimedia endpoint master volume through CoreAudio with a safe fallback',{type:'object',properties:{},required:[]},async()=>{try{return result('get_volume',true,'Master volume read',await coreVolume());}catch(error){return result('get_volume',false,'Windows did not expose the current master volume through CoreAudio',{error:error.message});}}),
  set_volume:tool('low','Set Windows default multimedia endpoint master volume 0-100; falls back to media keys if CoreAudio is unavailable',{type:'object',properties:{percent:{type:'number'}},required:['percent']},async({percent})=>{const n=Math.round(clamp(percent,0,100));try{await ps(`${coreAudio} [BCAudio]::Set(${n}/100.0)`);return result('set_volume',true,`Volume set to ${n}%`,{percent:n,engine:'coreaudio'});}catch(error){const actual=await fallbackSetVolume(n);return result('set_volume',true,`Volume set to approximately ${actual}%`,{percent:actual,engine:'media-key-fallback',coreAudioError:error.message});}}),
  volume_up:tool('low','Increase Windows master volume by a practical step',empty,async()=>{try{const current=await coreVolume(),n=Math.round(clamp(current.percent+10,0,100));await ps(`${coreAudio} [BCAudio]::Set(${n}/100.0)`);return result('volume_up',true,`Volume increased to ${n}%`,{percent:n,engine:'coreaudio'});}catch(error){await mediaKey('VOLUME_UP',3);return result('volume_up',true,'Volume increased',{engine:'virtual-key-fallback',coreAudioError:error.message});}}),
  volume_down:tool('low','Decrease Windows master volume by a practical step',empty,async()=>{try{const current=await coreVolume(),n=Math.round(clamp(current.percent-10,0,100));await ps(`${coreAudio} [BCAudio]::Set(${n}/100.0)`);return result('volume_down',true,`Volume decreased to ${n}%`,{percent:n,engine:'coreaudio'});}catch(error){await mediaKey('VOLUME_DOWN',3);return result('volume_down',true,'Volume decreased',{engine:'virtual-key-fallback',coreAudioError:error.message});}}),
  set_mute:tool('low','Set Windows default audio endpoint mute state through CoreAudio with media-key fallback',{type:'object',properties:{muted:{type:'boolean'}},required:['muted']},async({muted})=>{const m=Boolean(muted);try{await ps(`${coreAudio} [BCAudio]::Mute($${m?'true':'false'})`);return result('set_mute',true,m?'Muted':'Unmuted',{muted:m,engine:'coreaudio'});}catch(error){let current=null;try{current=await coreVolume();}catch{}if(current&&Boolean(current.muted)===m)return result('set_mute',true,m?'Muted':'Unmuted',{muted:m,engine:'coreaudio-read'});await mediaKey('VOLUME_MUTE');return result('set_mute',true,m?'Mute toggled on':'Mute toggled off',{muted:m,engine:'media-key-fallback',coreAudioError:error.message});}}),
  toggle_mute:tool('low','Toggle Windows default audio endpoint mute through CoreAudio with media-key fallback',empty,async()=>{try{const current=await coreVolume();await ps(`${coreAudio} [BCAudio]::Mute($${current.muted?'false':'true'})`);return result('toggle_mute',true,'Mute toggled',{muted:!current.muted,engine:'coreaudio'});}catch(error){await mediaKey('VOLUME_MUTE');return result('toggle_mute',true,'Mute toggled',{engine:'virtual-key-fallback',coreAudioError:error.message});}}),
  media_play_pause:tool('low','Toggle active media play/pause with native Windows media key',empty,async()=>{await mediaKey('MEDIA_PLAY_PAUSE');return result('media_play_pause',true,'Play/pause sent',{engine:'virtual-key'});}),
  media_next:tool('low','Go to next media track with native Windows media key',empty,async()=>{await mediaKey('MEDIA_NEXT_TRACK');return result('media_next',true,'Next track sent',{engine:'virtual-key'});}),
  media_previous:tool('low','Go to previous media track with native Windows media key',empty,async()=>{await mediaKey('MEDIA_PREV_TRACK');return result('media_previous',true,'Previous track sent',{engine:'virtual-key'});}),
  brightness_up:tool('low','Increase built-in display brightness by a practical step',empty,async()=>{const current=await readBrightness(),percent=await writeBrightness(current+10);return result('brightness_up',true,`Brightness increased to ${percent}%`,{percent});}),
  brightness_down:tool('low','Decrease built-in display brightness by a practical step',empty,async()=>{const current=await readBrightness(),percent=await writeBrightness(current-10);return result('brightness_down',true,`Brightness decreased to ${percent}%`,{percent});})
};
