// Stable intent contracts. Phrases below are anchors, NOT a brittle list of
// every possible user sentence. Real execution is delegated to the existing
// Skill/Tool registry, permission layer and result verifier.
const C=(id,tool,mode,objects,verbs,canonical,{direct=false,requiresTarget=false,risk='normal'}={})=>({
  id,tool,mode,objects,verbs,canonical,direct,requiresTarget,risk
});
export const CORE_PERSIAN_INTENTS=Object.freeze([
  C('audio.volume.up','volume_up','audio',['صدا','ولوم','اسپیکر','صدای سیستم','صدای ویندوز'],['زیاد کن','ببر بالا','بیار بالا','بلندتر کن','بیشتر کن','تقویت کن'],'صدای سیستم رو زیاد کن',{direct:true}),
  C('audio.volume.down','volume_down','audio',['صدا','ولوم','اسپیکر','صدای سیستم','صدای ویندوز'],['کم کن','بیار پایین','ببر پایین','آرومتر کن','کمتر کن','کاهش بده'],'صدای سیستم رو کم کن',{direct:true}),
  C('audio.volume.max','set_volume','audio',['صدا','ولوم','اسپیکر','صدای سیستم'],['تا ته زیاد کن','تا آخر زیاد کن','تا آخر ببر بالا','صد درصد کن','فول کن','تا سقف بالا ببر'],'صدا رو تا آخر زیاد کن',{direct:true}),
  C('audio.volume.min','set_volume','audio',['صدا','ولوم','اسپیکر','صدای سیستم'],['صفر کن','تا ته پایین ببر','روی صفر بذار','به صفر برسون'],'صدا رو روی صفر بذار',{direct:true}),
  C('audio.volume.mute','set_mute','audio',['صدا','ولوم','اسپیکر','صدای سیستم'],['قطع کن','بی صدا کن','سایلنت کن','میوت کن','خاموش کن'],'صدا رو بی صدا کن',{direct:true}),
  C('audio.volume.unmute','set_mute','audio',['صدا','ولوم','اسپیکر','صدای سیستم'],['از بی صدا دربیار','وصل کن','از سایلنت دربیار','آن میوت کن','صدادار کن'],'صدا رو از بی صدا دربیار',{direct:true}),
  C('audio.app.down','inspect_ui','audio',['صدای کروم','صدای فیلم','صدای ویدیو','صدای تلگرام','صدای برنامه','صدای یوتیوب','صدای پلیر','ولوم فیلم'],['کم کن','بیار پایین','کاهش بده','کمتر کن'],'صدای فیلم رو کم کن',{requiresTarget:true}),
  C('audio.app.up','inspect_ui','audio',['صدای کروم','صدای فیلم','صدای ویدیو','صدای تلگرام','صدای برنامه','صدای یوتیوب','صدای پلیر','ولوم فیلم'],['زیاد کن','ببر بالا','بیشتر کن','بلندتر کن'],'صدای فیلم رو زیاد کن',{requiresTarget:true}),
  C('audio.app.mute','inspect_ui','audio',['صدای کروم','صدای فیلم','صدای ویدیو','صدای تلگرام','صدای برنامه','صدای یوتیوب','صدای پلیر','ولوم فیلم'],['میوت کن','قطع کن','بی صدا کن','سایلنت کن'],'صدای فیلم رو بی صدا کن',{requiresTarget:true}),
  C('audio.volume.get','get_volume','audio',['صدا','ولوم','اسپیکر','صدای سیستم'],['چنده','چقدر هست','چند درصده','وضعیتش چیه'],'صدای سیستم چنده',{direct:true,risk:'read'}),
  C('display.brightness.up','brightness_up','display',['نور','روشنایی','نور صفحه','نور مانیتور'],['زیاد کن','ببر بالا','بیار بالا','بیشتر کن','روشنتر کن'],'نور صفحه رو بیشتر کن',{direct:true}),
  C('display.brightness.down','brightness_down','display',['نور','روشنایی','نور صفحه','نور مانیتور'],['کم کن','ببر پایین','بیار پایین','کمتر کن','تاریکتر کن'],'روشنایی رو کم کن',{direct:true}),
  C('display.brightness.max','set_brightness','display',['نور','روشنایی','نور صفحه'],['تا آخر زیاد کن','تا آخر ببر بالا','صد درصد کن','تا سقف ببر بالا'],'روشنایی رو تا آخر ببر بالا',{direct:true}),
  C('display.brightness.min','set_brightness','display',['نور','روشنایی','نور صفحه'],['صفر کن','تا ته کم کن','روی صفر بذار'],'روشنایی رو روی صفر بذار',{direct:true}),
  C('display.brightness.get','get_brightness','display',['نور','روشنایی','نور صفحه'],['چنده','چند درصده','چقدر هست','وضعیتش چیه'],'روشنایی چنده',{direct:true,risk:'read'}),
  C('media.play_pause','media_play_pause','media',['آهنگ','موزیک','موسیقی','ویدیو','فیلم','پخش'],['مکث کن','نگه دار','پاز کن','ادامه بده','پخش کن'],'موزیک رو نگه دار',{direct:true}),
  C('media.next','media_next','media',['آهنگ','موزیک','موسیقی','ترک'],['بعدی رو بزن','برو بعدی','بعدی رو پخش کن','رد کن'],'آهنگ بعدی رو بزن',{direct:true}),
  C('media.previous','media_previous','media',['آهنگ','موزیک','موسیقی','ترک'],['قبلی رو بزن','برگرد قبلی','قبلی رو پخش کن','برو قبلی'],'آهنگ قبلی رو بزن',{direct:true}),
  C('power.shutdown','shutdown_pc','power',['سیستم','کامپیوتر','ویندوز','لپتاپ','پی سی'],['خاموش کن','شات داون کن','ببر خاموشی'],'سیستم رو خاموش کن',{direct:true,risk:'critical'}),
  C('power.restart','restart_pc','power',['سیستم','کامپیوتر','ویندوز','لپتاپ','پی سی'],['ریستارت کن','ری استارت کن','دوباره راه اندازی کن'],'سیستم رو ریستارت کن',{direct:true,risk:'critical'}),
  C('power.sleep','sleep_pc','power',['سیستم','کامپیوتر','ویندوز','لپتاپ','پی سی'],['اسلیپ کن','بخوابون','ببر حالت خواب'],'سیستم رو ببر حالت خواب',{direct:true,risk:'critical'}),
  C('power.lock','lock_pc','power',['سیستم','کامپیوتر','ویندوز','لپتاپ','پی سی'],['قفل کن','لاک کن','بزن قفل'],'سیستم رو قفل کن',{direct:true}),
  C('windows.window.minimize','minimize_foreground_window','ui',['پنجره','این پنجره','برنامه فعال'],['کوچیک کن','کمینه کن','مینیمایز کن','جمع کن'],'این پنجره رو کمینه کن',{direct:true}),
  C('windows.window.maximize','maximize_foreground_window','ui',['پنجره','این پنجره','برنامه فعال'],['بزرگ کن','بیشینه کن','ماکسیمایز کن'],'این پنجره رو بزرگ کن',{direct:true}),
  C('windows.window.restore','restore_foreground_window','ui',['پنجره','این پنجره','برنامه فعال'],['برگردون','حالت عادی کن','ریستور کن'],'این پنجره رو به حالت عادی برگردون',{direct:true}),
  C('windows.desktop.show','show_desktop','ui',['دسکتاپ','صفحه اصلی ویندوز','پنجره ها'],['نشون بده','نمایش بده','بیار جلو'],'دسکتاپ رو نشون بده',{direct:true}),
  C('windows.screenshot','take_screenshot','ui',['صفحه','اسکرین','نمایشگر','مانیتور'],['اسکرین شات بگیر','عکس بگیر','اسکرین بگیر','تصویر بگیر'],'از صفحه اسکرین شات بگیر',{direct:true}),
  C('apps.launch','launch_any_app','apps',['کروم','تلگرام','واتساپ','روبیکا','فتوشاپ','وی اس کد','اکسل','ورد','فایرفاکس','برنامه'],['باز کن','اجرا کن','راه بنداز','بیار بالا'],'تلگرام رو باز کن',{requiresTarget:true}),
  C('apps.close','close_app','apps',['کروم','تلگرام','واتساپ','روبیکا','فتوشاپ','اکسل','برنامه'],['ببند','خارج شو','کلوز کن','تموم کن'],'برنامه رو ببند',{requiresTarget:true}),
  C('apps.install','install_app','apps',['برنامه','نرم افزار','اپ','بازی'],['نصب کن','دانلود و نصب کن','بگیر نصب کن'],'برنامه رو نصب کن',{requiresTarget:true,risk:'important'}),
  C('apps.update','upgrade_app','apps',['برنامه','نرم افزار','اپ','بازی'],['آپدیت کن','بروزرسانی کن','نسخه جدیدش رو نصب کن'],'برنامه رو آپدیت کن',{requiresTarget:true}),
  C('apps.uninstall','uninstall_app','apps',['برنامه','نرم افزار','اپ','بازی'],['حذف کن','پاک کن','آن اینستال کن'],'برنامه رو حذف کن',{requiresTarget:true,risk:'critical'}),
  C('files.find','global_find_files','files',['فایل','پرونده','پوشه','فولدر','اکسل'],['پیدا کن','دنبالش بگرد','لوکیشنشو پیدا کن'],'فایل رو پیدا کن',{requiresTarget:true,risk:'read'}),
  C('files.open','open_named_file','files',['فایل','پرونده','عکس','فیلم','فایل اکسل'],['باز کن','نشون بده','بیار بالا'],'فایل رو باز کن',{requiresTarget:true}),
  C('files.folder.open','open_named_folder','files',['پوشه','فولدر','دایرکتوری'],['باز کن','برو داخل','نشون بده'],'پوشه رو باز کن',{requiresTarget:true}),
  C('files.folder.create','create_folder','files',['پوشه','فولدر','دایرکتوری'],['بساز','ایجاد کن','درست کن'],'یه پوشه بساز',{requiresTarget:true}),
  C('files.rename','rename_path','files',['فایل','پوشه','فولدر','اسم فایل','نام پوشه'],['اسمشو عوض کن','عوض کن','تغییر نام بده','ری نیم کن'],'اسم فایل رو عوض کن',{requiresTarget:true}),
  C('files.copy','copy_path','files',['فایل','پوشه','فولدر'],['کپی کن','یه نسخه بگیر','تکثیر کن'],'فایل رو کپی کن',{requiresTarget:true}),
  C('files.move','move_path','files',['فایل','پوشه','فولدر'],['منتقل کن','جابجا کن','ببر یه مسیر دیگه'],'فایل رو منتقل کن',{requiresTarget:true}),
  C('files.delete','delete_path','files',['فایل','پوشه','فولدر','پرونده'],['حذف کن','پاک کن','بنداز سطل زباله'],'فایل رو حذف کن',{requiresTarget:true,risk:'critical'}),
  C('files.archive.zip','zip_files','files',['فایل','پوشه','فولدر'],['زیپ کن','فشرده کن','ببر داخل زیپ'],'فایل رو زیپ کن',{requiresTarget:true}),
  C('files.archive.extract','extract_archive','files',['زیپ','فایل فشرده','آرشیو'],['اکسترکت کن','استخراج کن','از زیپ دربیار'],'فایل زیپ رو اکسترکت کن',{requiresTarget:true}),
  C('web.google.search','chrome_search','web',['گوگل','کروم','اینترنت','وب'],['سرچ کن','جستجو کن','بگرد','پیدا کن'],'تو گوگل درباره موضوع سرچ کن',{requiresTarget:true,risk:'read'}),
  C('web.youtube.search','youtube_search','web',['یوتیوب','یوتوب','youtube'],['سرچ کن','جستجو کن','بگرد','پیدا کن'],'تو یوتیوب موزیک سرچ کن',{requiresTarget:true,risk:'read'}),
  C('web.open.site','chrome_open_named_site','web',['سایت','وبسایت','آدرس سایت','لینک'],['باز کن','برو تو','برو به'],'سایت رو باز کن',{requiresTarget:true}),
  C('browser.tab.pin','invoke_ui_element','web',['تب','زبانه','صفحه کروم'],['پین کن','سنجاق کن','ثابت کن'],'تب رو پین کن',{requiresTarget:true}),
  C('browser.tab.unpin','invoke_ui_element','web',['تب','زبانه','صفحه کروم'],['از پین دربیار','از پین بردار','آن پین کن','سنجاقشو بردار'],'تب رو از پین بردار',{requiresTarget:true}),
  C('browser.tab.close','invoke_ui_element','web',['تب','زبانه','صفحه کروم'],['ببند','کلوز کن','حذف کن'],'تب رو ببند',{requiresTarget:true}),
  C('notes.pin.create','create_pinned_note','notes',['یادداشت','متن','نوت','پین'],['پین کن','ذخیره کن','یادداشت کن','سنجاق کن'],'متن رو پین کن',{requiresTarget:true}),
  C('reminder.create','create_reminder','scheduler',['یادآور','یادم','یادآوری'],['بنداز','بذار','یادم بنداز','یادآوری کن'],'فردا یادم بنداز که به جلسه برسم',{requiresTarget:true}),
  C('reminder.action.schedule','create_scheduled_action','scheduler',['کار','عملیات','دستور','گزارش'],['زمان بندی کن','سر ساعت اجرا کن','فردا انجام بده'],'کار رو برای فردا زمان بندی کن',{requiresTarget:true,risk:'important'}),
  C('excel.read','excel_read_range','spreadsheet',['اکسل','سلول','شیت','فایل اکسل'],['بخون','محتواشو بگو','نمایش بده','بررسی کن'],'اکسل رو بخون',{requiresTarget:true,risk:'read'}),
  C('excel.edit','excel_set_cells','spreadsheet',['اکسل','سلول','شیت','فایل اکسل'],['تغییر بده','ویرایش کن','اصلاح کن','بنویس'],'سلول اکسل رو تغییر بده',{requiresTarget:true}),
  C('excel.hyperlink','excel_set_cells','spreadsheet',['اکسل','سلول','سلول h','شیت'],['لینک کن','هایپرلینک بزن','پیوند بده'],'سلول اکسل رو لینک کن',{requiresTarget:true}),
  C('messenger.send','messenger_open','social',['تلگرام','واتساپ','روبیکا','پیام','چت'],['پیام بفرست','ارسال کن','بفرست به','بده به مخاطب'],'تلگرام پیام بفرست',{requiresTarget:true,risk:'critical'}),
  C('messenger.forward','messenger_open','social',['تلگرام','واتساپ','روبیکا','پیام'],['فوروارد کن','ارسال مجدد کن','بفرست به گروه'],'پیام تلگرام رو فوروارد کن',{requiresTarget:true,risk:'critical'}),
  C('translation.selection','vision_inspect_screen','ui',['متن انتخاب شده','سلکت','این متن','نوشته'],['ترجمه کن','برگردون فارسی','برگردون انگلیسی'],'متن انتخاب شده رو ترجمه کن',{requiresTarget:true}),
  C('translation.page','vision_inspect_screen','ui',['این صفحه','صفحه کروم','کل صفحه','وبسایت'],['ترجمه کن','فارسی کن','انگلیسی کن'],'کل صفحه رو ترجمه کن',{requiresTarget:true}),
  C('translation.image','vision_inspect_screen','ui',['تصویر','عکس','متن عکس','اسکرین شات'],['ترجمه کن','فارسی کن','معنی کن'],'متن عکس رو ترجمه کن',{requiresTarget:true}),
  C('security.windows.settings','windows_signin_options_open','settings',['رمز ویندوز','رمز سیستم','ورود ویندوز','windows hello'],['تنظیماتشو باز کن','باز کن','تغییر بده','برو تنظیمات'],'تنظیمات رمز ویندوز رو باز کن',{requiresTarget:true,risk:'important'}),
  C('system.troubleshoot','recent_system_errors','diagnostics',['ویندوز','سیستم','برنامه','ارور','خطا'],['عیب یابی کن','مشکلشو پیدا کن','بررسی کن','درست کن'],'مشکل ویندوز رو عیب یابی کن',{requiresTarget:true}),
]);
export const CORE_INTENT_MAP=new Map(CORE_PERSIAN_INTENTS.map(x=>[x.id,x]));
export const CORE_INTENT_COUNT=CORE_PERSIAN_INTENTS.length;
