import fs from 'node:fs/promises';
import path from 'node:path';
import {execFile,spawn} from 'node:child_process';
import {promisify} from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const schema=(properties,required=[])=>({type:'object',properties,required});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const open=url=>spawn('cmd.exe',['/c','start','',url],{detached:true,windowsHide:true});
const resolveSafe=p=>path.resolve(String(p));
const SOCIAL={telegram:'https://web.telegram.org/',whatsapp:'https://web.whatsapp.com/',instagram:'https://www.instagram.com/',discord:'https://discord.com/app',gmail:'https://mail.google.com/',outlook:'https://outlook.live.com/mail/',github:'https://github.com/',youtube:'https://www.youtube.com/'};
export const powerTools={
 rename_path:tool('sensitive','Rename a file or folder',{type:'object',properties:{target:{type:'string'},new_name:{type:'string'}},required:['target','new_name']},async({target,new_name})=>{const src=resolveSafe(target),dst=path.join(path.dirname(src),path.basename(String(new_name)));await fs.rename(src,dst);return result('rename_path',true,'Path renamed',{from:src,to:dst});}),
 move_path:tool('sensitive','Move a file or folder to another directory',{type:'object',properties:{target:{type:'string'},destination_directory:{type:'string'}},required:['target','destination_directory']},async({target,destination_directory})=>{const src=resolveSafe(target),dir=resolveSafe(destination_directory),dst=path.join(dir,path.basename(src));await fs.mkdir(dir,{recursive:true});await fs.rename(src,dst);return result('move_path',true,'Path moved',{from:src,to:dst});}),
 copy_path:tool('sensitive','Copy a file or folder recursively',{type:'object',properties:{target:{type:'string'},destination:{type:'string'}},required:['target','destination']},async({target,destination})=>{const src=resolveSafe(target),dst=resolveSafe(destination);await fs.cp(src,dst,{recursive:true,errorOnExist:true});return result('copy_path',true,'Path copied',{from:src,to:dst});}),
 search_files:tool('read','Search files and folders below a directory by partial name',{type:'object',properties:{directory:{type:'string'},query:{type:'string'},limit:{type:'number'}},required:['directory','query']},async({directory,query,limit=100})=>{const root=resolveSafe(directory),needle=String(query).toLowerCase(),found=[],max=Math.max(1,Math.min(Number(limit)||100,500));async function walk(dir,depth=0){if(depth>8||found.length>=max)return;let entries=[];try{entries=await fs.readdir(dir,{withFileTypes:true});}catch{return;}for(const e of entries){const p=path.join(dir,e.name);if(e.name.toLowerCase().includes(needle))found.push({name:e.name,path:p,type:e.isDirectory()?'directory':'file'});if(e.isDirectory()&&found.length<max)await walk(p,depth+1);if(found.length>=max)break;}}await walk(root);return result('search_files',true,'Search completed',found);}),
 create_text_file:tool('sensitive','Create a new UTF-8 text file without overwriting an existing file',{type:'object',properties:{file:{type:'string'},content:{type:'string'}},required:['file','content']},async({file,content})=>{const p=resolveSafe(file);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(content),{encoding:'utf8',flag:'wx'});return result('create_text_file',true,'File created',{path:p});}),
 append_text_file:tool('sensitive','Append UTF-8 text to an existing file',{type:'object',properties:{file:{type:'string'},content:{type:'string'}},required:['file','content']},async({file,content})=>{const p=resolveSafe(file);await fs.appendFile(p,String(content),'utf8');return result('append_text_file',true,'Text appended',{path:p});}),
 open_social_web:tool('low','Open a supported communication/social web application: Telegram, WhatsApp, Instagram, Discord, Gmail, Outlook, GitHub or YouTube',schema({service:{type:'string',enum:Object.keys(SOCIAL)}} ,['service']),async({service})=>{const url=SOCIAL[String(service).toLowerCase()];if(!url)return result('open_social_web',false,'Unsupported service');open(url);return result('open_social_web',true,`${service} opened`,{url});}),
 open_web_search_in_service:tool('low','Open a search URL for supported services where URL search is available',{type:'object',properties:{service:{type:'string',enum:['youtube','github']},query:{type:'string'}},required:['service','query']},async({service,query})=>{const q=encodeURIComponent(query),url=service==='youtube'?`https://www.youtube.com/results?search_query=${q}`:`https://github.com/search?q=${q}`;open(url);return result('open_web_search_in_service',true,'Service search opened',{service,query,url});}),
 list_winget_upgrades:tool('read','List available application upgrades through winget',{type:'object',properties:{},required:[]},async()=>{const {stdout}=await execFileAsync('winget.exe',['upgrade','--accept-source-agreements'],{windowsHide:true,timeout:120000,maxBuffer:6_000_000});return result('list_winget_upgrades',true,'Available upgrades listed',{output:stdout.slice(0,20000)});}),
 upgrade_app:tool('sensitive','Upgrade one installed package by exact winget package id',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const {stdout}=await execFileAsync('winget.exe',['upgrade','--id',String(id),'-e','--accept-package-agreements','--accept-source-agreements'],{windowsHide:false,timeout:600000,maxBuffer:8_000_000});return result('upgrade_app',true,'Application upgrade completed',{output:stdout.slice(-10000)});}),
 open_downloads:tool('low','Open the current user Downloads folder',{type:'object',properties:{},required:[]},async()=>{const p=path.join(process.env.USERPROFILE||process.cwd(),'Downloads');spawn('explorer.exe',[p],{detached:true,windowsHide:true});return result('open_downloads',true,'Downloads opened',{path:p});}),
 open_desktop:tool('low','Open the current user Desktop folder',{type:'object',properties:{},required:[]},async()=>{const p=path.join(process.env.USERPROFILE||process.cwd(),'Desktop');spawn('explorer.exe',[p],{detached:true,windowsHide:true});return result('open_desktop',true,'Desktop opened',{path:p});})
};
