const privateTools=new Set([
  'read_text_file','list_directory','file_info','search_files','global_find_files','open_named_file','reveal_named_file','storage_overview','read_clipboard','take_screenshot','vision_inspect_screen','vision_inspect_image_file','list_windows','inspect_ui',
  'excel_status','excel_list_sheets','excel_read_range','excel_set_cells','excel_append_rows','excel_add_image','excel_list_hyperlinks','excel_collect_images',
  'messenger_open','messenger_stage_files','copy_files_to_clipboard','media_info','media_thumbnail','media_extract_audio','media_clip','media_convert','media_folder_catalog','media_find_large',
  'remember_fact','recall_memory','list_recent_memories','update_memory','forget_memory','create_pinned_note','list_pinned_notes','search_pinned_notes','update_pinned_note','remove_pinned_note',
  'get_system_info','list_processes','performance_snapshot','disk_health_summary','volume_inventory','process_resource_usage','startup_programs','windows_services','scheduled_tasks_summary','recent_system_errors','defender_status','firewall_status','problem_devices','device_inventory','display_inventory','audio_device_inventory','network_adapters','wifi_status','ip_configuration','listening_ports','environment_summary','restore_points','temp_usage','recycle_bin_usage',
  'type_text','set_ui_value','invoke_ui_element','mouse_click','move_mouse','press_key','rename_path','move_path','copy_path','write_text_file','delete_path','inspect_project','project_read_file','project_search_text','project_apply_replacements','project_create_file','project_restore_backup','run_project_task','git_create_branch','git_switch_branch','git_commit_files','git_restore_files','node_check_file',
  'teach_skill','search_learned_skills','learning_status','forget_learned_skill'
]);
const privateText=/(رمز|پسورد|password|token|api.?key|کلید|کلیپ.?بورد|clipboard|فایل شخصی|پوشه|مسیر|desktop|documents|دانلود|اکانت|حساب|ایمیل|پیام خصوصی|تلگرام|واتساپ|روبیکا|اینستاگرام|اکسل|excel|xlsx|xlsm|اسکرین|صفحه من|روی سیستم من|کامپیوتر من|اطلاعات من|حافظه من|کل حافظه|کل درایو|متن مهم|یادداشت|پین|ویدیو من|فیلم من|عکس من|ببین چی روی صفحه|چی می.?بینی)/i;
const forceOnline=/(از اینترنت|آنلاین جستجو|سرچ آنلاین|تحقیق آنلاین|منبع جدید|آخرین اطلاعات|latest|current web)/i;
export function isPrivateRequest(text,hints=[]){const s=String(text||'');if(forceOnline.test(s)&&!/(فایل|رمز|اکانت|پیام|کلیپ.?بورد|صفحه من|کامپیوتر من|اکسل|excel|عکس من|فیلم من)/i.test(s))return false;return privateText.test(s)||hints.some(x=>/(file|clipboard|screen|window|social|system|coding|spreadsheet|storage|media|notes)/i.test(String(x)));}
export function toolMakesContextPrivate(name){return privateTools.has(name);}
export function explainPrivacyMode(isPrivate){return isPrivate?'local-private':'online-eligible';}
