import { spawn,execFile } from 'node:child_process';
import { promisify } from 'node:util';
import fs from 'node:fs/promises';
import path from 'node:path';
import { Agent } from './Agent.js';
import { BrainRouter } from './BrainRouter.js';
import { projects } from './ProjectStore.js';
const execFileAsync=promisify(execFile);
const PROJECT_TOOLS=['inspect_project','project_search_text','read_project_file','replace_project_text','write_project_file','project_quality_task','run_project_task','git_create_branch','git_remote_info','git_commit_changes','git_push_branch','open_project_vscode','live_web_search','research_topic','read_web_page'];
const contextFor=p=>`\n\n[PROJECT WORKSPACE]\nProject: ${p.name}\nType: ${p.type}\nRoot directory: ${p.directory}\nStay inside this project root for file work. Inspect before editing. Use project tools instead of guessing file contents. Run relevant tests/build after edits. Never invent a successful GitHub push. Reply in Persian unless code or raw output needs English.`;
const run=async(cmd,args,cwd,timeout=120000)=>{const {stdout,stderr}=await execFileAsync(cmd,args,{cwd,windowsHide:true,timeout,maxBuffer:12_000_000});return {stdout:stdout.trim(),stderr:stderr.trim()};};
async function codeExe(){const candidates=[path.join(process.env.LOCALAPPDATA||'','Programs','Microsoft VS Code','Code.exe'),path.join(process.env.PROGRAMFILES||'','Microsoft VS Code','Code.exe')];for(const p of candidates){try{await fs.access(p);return p;}catch{}}try{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',"(Get-ItemProperty 'HKCU:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\Code.exe' -ErrorAction SilentlyContinue).'(default)'"],{windowsHide:true,timeout:10000});if(stdout.trim())return stdout.trim();}catch{}return null;}
async function ghExe(){const candidates=[path.join(process.env.PROGRAMFILES||'','GitHub CLI','gh.exe'),path.join(process.env.LOCALAPPDATA||'','Programs','GitHub CLI','gh.exe')];for(const p of candidates){try{await fs.access(p);return p;}catch{}}try{const {stdout}=await execFileAsync('where.exe',['gh.exe'],{windowsHide:true,timeout:6000});return stdout.trim().split(/\r?\n/)[0]||null;}catch{return null;}}
async function ghState(cwd){const exe=await ghExe();if(!exe)return {installed:false,authenticated:false};try{const out=await run(exe,['auth','status'],cwd,15000);return {installed:true,authenticated:true,detail:out.stdout||out.stderr};}catch(e){return {installed:true,authenticated:false,detail:String(e.stderr||e.stdout||e.message||'')};}}
const safeRepoName=s=>String(s||'maria-project').trim().replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)||'maria-project';

export class ProjectService{
  constructor({emit=()=>{}}={}){this.emit=emit;this.sessions=new Map();this.router=new BrainRouter();}
  reloadBrains(){this.router=new BrainRouter();this.sessions.clear();return true;}
  async list(){return projects.list();}
  async catalog(){const [items,models]=await Promise.all([projects.list(),this.router.models()]),web=[{provider:'web',label:'ChatGPT Web',model:'chatgpt',configured:true},{provider:'web',label:'Claude Web',model:'claude',configured:true},{provider:'web',label:'DeepSeek Web',model:'deepseek',configured:true},{provider:'web',label:'Qwen Web',model:'qwen',configured:true}];return {projects:items,models:models||[],providers:[...(this.router.online?.catalog?.()||[]),...web]};}
  async create(payload){const item=await projects.create(payload||{});try{await run('git.exe',['init'],item.directory,20000);}catch{}this.sessions.delete(item.id);return item;}
  async update(id,patch){const item=await projects.update(id,patch||{});const s=this.sessions.get(id);if(s){s.project=item;s.agent.chatOptions={profile:'coding',provider:item.provider||'ollama',model:item.model||'auto'};}return item;}
  async remove(id){this.sessions.delete(id);return projects.remove(id);}
  async session(id){const existing=this.sessions.get(id);if(existing)return existing;const project=await projects.get(id);if(!project)throw new Error('Project not found');const agent=new Agent({emit:e=>this.emit({...e,projectId:id}),client:new BrainRouter(),systemContext:contextFor(project),chatOptions:{profile:'coding',provider:project.provider||'ollama',model:project.model||'auto'},defaultTools:PROJECT_TOOLS,enableScheduler:false});for(const m of (project.messages||[]).slice(-30))agent.history.push({role:m.role==='assistant'?'assistant':'user',content:String(m.content||''),_private:true});const session={project,agent};this.sessions.set(id,session);return session;}
  async chat({projectId,text,provider,model}={}){const s=await this.session(String(projectId||''));if(provider||model){s.project=await projects.update(s.project.id,{provider:provider||s.project.provider,model:model||s.project.model});s.agent.chatOptions={profile:'coding',provider:s.project.provider||'ollama',model:s.project.model||'auto'};}const message=String(text||'').trim();if(!message)return {ok:false,text:'پیام خالی است.'};await projects.appendMessage(s.project.id,{role:'user',content:message});if((s.project.provider||provider)==='web'){const service=String(s.project.model||model||'chatgpt').toLowerCase(),textOut=`${service} در حالت Web با پروفایل شخصی Chrome باز می‌شود. تاریخچه این Project داخل Maria جدا می‌ماند؛ برای پاسخ مستقیم داخل همین پنجره باید API همان سرویس تنظیم شود.`;await projects.appendMessage(s.project.id,{role:'assistant',content:textOut});return {ok:true,webOnly:true,service,text:textOut,projectId:s.project.id};}const response=await s.agent.chat(message);await projects.appendMessage(s.project.id,{role:'assistant',content:response.text||''});return {...response,projectId:s.project.id};}
  async openVSCode(id){const project=await projects.get(id);if(!project)throw new Error('Project not found');const exe=await codeExe();if(!exe)throw new Error('Visual Studio Code پیدا نشد');const child=spawn(exe,['-n',project.directory],{detached:true,stdio:'ignore',windowsHide:false});child.unref();return {ok:true,path:project.directory};}
  async openVsCode(id){return this.openVSCode(id);}
  async openFolder(id){const project=await projects.get(id);if(!project)throw new Error('Project not found');const child=spawn('explorer.exe',[project.directory],{detached:true,stdio:'ignore',windowsHide:false});child.unref();return {ok:true,path:project.directory};}
  async gitStatus(id){const project=await projects.get(id);if(!project)throw new Error('Project not found');let branch='',remotes='',status='';try{branch=(await run('git.exe',['branch','--show-current'],project.directory,15000)).stdout;remotes=(await run('git.exe',['remote','-v'],project.directory,15000)).stdout;status=(await run('git.exe',['status','--short'],project.directory,15000)).stdout;}catch(e){return {ok:false,error:e.message,directory:project.directory,gh:await ghState(project.directory)};}return {ok:true,branch,remotes,status,dirty:Boolean(status),directory:project.directory,gh:await ghState(project.directory)};}
  async connectGithub(id){const project=await projects.get(id);if(!project)throw new Error('Project not found');const exe=await ghExe();if(!exe)throw new Error('GitHub CLI نصب نیست.');const child=spawn('cmd.exe',['/k',`"${exe}" auth login --web --git-protocol https`],{cwd:project.directory,detached:true,stdio:'ignore',windowsHide:false});child.unref();return {ok:true,started:true};}
  async publishGithub(id,{message='Maria project update'}={}){const project=await projects.get(id);if(!project)throw new Error('Project not found');const info=await this.gitStatus(id);if(!info.ok)throw new Error(info.error||'Git status failed');if(info.dirty){await run('git.exe',['add','-A'],project.directory,30000);try{await run('git.exe',['commit','-m',String(message||'Maria project update').slice(0,180)],project.directory,60000);}catch(e){if(!/nothing to commit/i.test(`${e.stdout||''} ${e.stderr||''} ${e.message||''}`))throw e;}}let branch=(await this.gitStatus(id)).branch||'main';if(!info.remotes||!/(^|\n)origin\s/m.test(info.remotes)){const gh=await ghState(project.directory),exe=await ghExe();if(!gh.authenticated||!exe)throw new Error('GitHub هنوز Login نشده؛ اول Connect GitHub را بزن.');const repo=safeRepoName(project.name);const out=await run(exe,['repo','create',repo,'--private','--source','.', '--remote','origin','--push'],project.directory,240000);return {ok:true,branch,remote:'origin',repo,created:true,output:out.stdout||out.stderr};}const out=await run('git.exe',['push','--set-upstream','origin',branch],project.directory,180000);return {ok:true,branch,remote:'origin',output:out.stdout||out.stderr};}
}
export const projectService=new ProjectService();
