import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
const defaultDir=()=>process.env.BLACK_CLOVER_DATA_DIR||path.join(process.env.APPDATA||path.join(os.homedir(),'.black-clover'),'BlackClover');
const now=()=>new Date().toISOString();
export class ReminderStore{
  constructor({directory=defaultDir()}={}){this.file=path.join(directory,'reminders.json');this.backup=path.join(directory,'reminders.backup.json');this.directory=directory;this.items=[];this.loaded=false;}
  async load(){if(this.loaded)return this.items;this.loaded=true;for(const f of [this.file,this.backup]){try{const j=JSON.parse(await fs.readFile(f,'utf8'));if(Array.isArray(j?.items)){this.items=j.items;return this.items;}}catch(e){if(e.code!=='ENOENT')console.warn('Reminder load failed',e.message);}}return this.items;}
  async save(){await fs.mkdir(this.directory,{recursive:true});try{await fs.copyFile(this.file,this.backup);}catch{}const tmp=`${this.file}.tmp`;await fs.writeFile(tmp,JSON.stringify({version:2,items:this.items,updatedAt:now()},null,2),'utf8');await fs.rename(tmp,this.file);}
  async create({message,dueAt,intervalMinutes=0,title='',category='general',priority='normal'}={}){await this.load();const when=new Date(dueAt);if(!String(message||'').trim()||Number.isNaN(when.getTime()))throw new Error('Valid message and dueAt are required');const item={id:crypto.randomUUID(),title:String(title||'').trim().slice(0,160),message:String(message).trim().slice(0,4000),dueAt:when.toISOString(),intervalMinutes:Math.max(0,Number(intervalMinutes)||0),category:String(category||'general').slice(0,60),priority:['low','normal','high'].includes(priority)?priority:'normal',enabled:true,status:'active',createdAt:now(),updatedAt:now(),lastTriggeredAt:null};this.items.push(item);await this.save();return item;}
  async list({includeDone=false}={}){await this.load();return this.items.filter(x=>includeDone||x.enabled).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));}
  async get(id){await this.load();return this.items.find(x=>x.id===id)||null;}
  async update(id,patch={}){await this.load();const item=this.items.find(x=>x.id===id);if(!item)return null;if(typeof patch.message==='string'&&patch.message.trim())item.message=patch.message.trim().slice(0,4000);if(typeof patch.title==='string')item.title=patch.title.trim().slice(0,160);if(typeof patch.category==='string')item.category=patch.category.slice(0,60);if(['low','normal','high'].includes(patch.priority))item.priority=patch.priority;if(patch.dueAt){const d=new Date(patch.dueAt);if(Number.isNaN(d.getTime()))throw new Error('Invalid dueAt');item.dueAt=d.toISOString();}if(Number.isFinite(Number(patch.intervalMinutes)))item.intervalMinutes=Math.max(0,Number(patch.intervalMinutes));if(typeof patch.enabled==='boolean')item.enabled=patch.enabled;item.status=item.enabled?'active':item.status;item.updatedAt=now();await this.save();return item;}
  async snooze(id,minutes=10){await this.load();const item=this.items.find(x=>x.id===id);if(!item)return null;item.dueAt=new Date(Date.now()+Math.max(1,Number(minutes)||10)*60000).toISOString();item.enabled=true;item.status='active';item.updatedAt=now();await this.save();return item;}
  async complete(id){await this.load();const item=this.items.find(x=>x.id===id);if(!item)return false;item.enabled=false;item.status='done';item.completedAt=now();item.updatedAt=now();await this.save();return true;}
  async cancel(id){await this.load();const item=this.items.find(x=>x.id===id);if(!item)return false;item.enabled=false;item.status='cancelled';item.updatedAt=now();await this.save();return true;}
  async remove(id){await this.load();const n=this.items.length;this.items=this.items.filter(x=>x.id!==id);if(n===this.items.length)return false;await this.save();return true;}
  async takeDue(current=Date.now()){await this.load();const due=[];let changed=false;for(const item of this.items){if(!item.enabled||new Date(item.dueAt).getTime()>current)continue;due.push({...item});item.lastTriggeredAt=now();if(item.intervalMinutes>0){let next=new Date(item.dueAt).getTime(),step=item.intervalMinutes*60000;while(next<=current)next+=step;item.dueAt=new Date(next).toISOString();item.status='active';}else{item.enabled=false;item.status='triggered';}item.updatedAt=now();changed=true;}if(changed)await this.save();return due;}
}
export const reminders=new ReminderStore();
