import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
const defaultDir=()=>process.env.BLACK_CLOVER_DATA_DIR||path.join(process.env.APPDATA||path.join(os.homedir(),'.black-clover'),'BlackClover');
export class ReminderStore{
  constructor({directory=defaultDir()}={}){this.file=path.join(directory,'reminders.json');this.directory=directory;this.items=[];this.loaded=false;this.actionExecutor=null;this.executing=new Set();this.actionRuns=new Set();this.saveChain=Promise.resolve();}
  setActionExecutor(fn){this.actionExecutor=typeof fn==='function'?fn:null;}
  async load(){if(this.loaded)return this.items;this.loaded=true;try{const j=JSON.parse(await fs.readFile(this.file,'utf8'));this.items=Array.isArray(j?.items)?j.items.map(x=>({...x,kind:x.kind||'reminder'})):[];}catch(e){if(e.code!=='ENOENT')console.warn('Reminder load failed',e.message);}return this.items;}
  save(){const snapshot=JSON.stringify({version:2,items:this.items,updatedAt:new Date().toISOString()},null,2);const pending=this.saveChain.catch(()=>{}).then(async()=>{await fs.mkdir(this.directory,{recursive:true});const tmp=`${this.file}.tmp`;await fs.writeFile(tmp,snapshot,'utf8');await fs.rename(tmp,this.file);});this.saveChain=pending;return pending;}
  async whenIdle(){while(this.actionRuns.size)await Promise.allSettled([...this.actionRuns]);await this.saveChain;}
  async create({message,dueAt,intervalMinutes=0}){await this.load();const when=new Date(dueAt);if(!String(message||'').trim()||Number.isNaN(when.getTime()))throw new Error('Valid message and dueAt are required');const item={id:crypto.randomUUID(),kind:'reminder',message:String(message).trim(),dueAt:when.toISOString(),intervalMinutes:Math.max(0,Number(intervalMinutes)||0),enabled:true,createdAt:new Date().toISOString()};this.items.push(item);await this.save();return item;}
  async createAction({instruction,dueAt,intervalMinutes=0,label=''}){await this.load();const when=new Date(dueAt),task=String(instruction||'').trim();if(!task||Number.isNaN(when.getTime()))throw new Error('Valid instruction and dueAt are required');const item={id:crypto.randomUUID(),kind:'action',instruction:task,label:String(label||task).trim().slice(0,180),message:String(label||task).trim().slice(0,180),dueAt:when.toISOString(),intervalMinutes:Math.max(0,Number(intervalMinutes)||0),enabled:true,createdAt:new Date().toISOString(),lastRunAt:null,lastResult:null};this.items.push(item);await this.save();return item;}
  async list(){await this.load();return this.items.filter(x=>x.enabled).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt));}
  async cancel(id){await this.load();const item=this.items.find(x=>x.id===id);if(!item)return false;item.enabled=false;await this.save();return true;}
  _advance(item,now){if(item.intervalMinutes>0){let next=new Date(item.dueAt).getTime(),step=item.intervalMinutes*60000;while(next<=now)next+=step;item.dueAt=new Date(next).toISOString();}else item.enabled=false;}
  async _runActions(actions,now){if(!this.actionExecutor)return;for(const item of actions){if(this.executing.has(item.id))continue;this.executing.add(item.id);try{const out=await this.actionExecutor({...item});const target=this.items.find(x=>x.id===item.id);if(target){target.lastRunAt=new Date(now).toISOString();target.lastResult={ok:out?.ok!==false,text:String(out?.text||'').slice(0,2000),requiresConfirmation:Boolean(out?.requiresConfirmation)};await this.save();}const report=out?.requiresConfirmation?`کار زمان‌بندی‌شده «${item.label||item.instruction}» به مرحله‌ای رسید که تأیید دستی لازم دارد و آن بخش خودکار اجرا نشد.`:`کار زمان‌بندی‌شده «${item.label||item.instruction}» اجرا شد${out?.text?` — ${String(out.text).slice(0,500)}`:''}`;await this.create({message:report,dueAt:new Date(Date.now()+1000).toISOString()});}catch(e){const target=this.items.find(x=>x.id===item.id);if(target){target.lastRunAt=new Date(now).toISOString();target.lastResult={ok:false,text:String(e.message||e).slice(0,2000)};await this.save();}await this.create({message:`اجرای کار زمان‌بندی‌شده «${item.label||item.instruction}» کامل نشد: ${e.message||e}`,dueAt:new Date(Date.now()+1000).toISOString()});}finally{this.executing.delete(item.id);}}}
  async takeDue(now=Date.now()){await this.load();const remindersDue=[],actionsDue=[];let changed=false;for(const item of this.items){if(!item.enabled||new Date(item.dueAt).getTime()>now)continue;if((item.kind||'reminder')==='action'){if(!this.actionExecutor)continue;actionsDue.push({...item});this._advance(item,now);changed=true;}else{remindersDue.push({...item});this._advance(item,now);changed=true;}}if(changed)await this.save();if(actionsDue.length){const pending=Promise.resolve().then(()=>this._runActions(actionsDue,now));this.actionRuns.add(pending);pending.then(()=>this.actionRuns.delete(pending),error=>{this.actionRuns.delete(pending);console.warn('Scheduled action failed',error.message);});}return remindersDue;}
}
export const reminders=new ReminderStore();
