import dns from 'node:dns/promises';
import net from 'node:net';

const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const decode=s=>String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const privateIp=ip=>ip==='::1'||ip.startsWith('127.')||ip.startsWith('10.')||ip.startsWith('192.168.')||/^172\.(1[6-9]|2\d|3[01])\./.test(ip)||ip.startsWith('169.254.')||ip.startsWith('fc')||ip.startsWith('fd');
async function assertPublicUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('Only public http/https URLs are allowed');if(['localhost','0.0.0.0'].includes(u.hostname)||u.hostname.endsWith('.local'))throw new Error('Local/private addresses are blocked');const records=await dns.lookup(u.hostname,{all:true});if(records.some(x=>privateIp(x.address)))throw new Error('Local/private addresses are blocked');return u;}
const fetchText=async(url,{timeout=12000,max=120000}={})=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 BlackCloverResearch/1.0','accept':'text/html,application/xhtml+xml,text/plain;q=0.9,*/*;q=0.5'},redirect:'follow',signal:controller.signal});if(!r.ok)throw new Error(`HTTP ${r.status}`);const text=await r.text();return text.slice(0,max);}finally{clearTimeout(timer);}};

export const researchTools={
  live_web_search:tool('read','Search the live public web for current information without opening the browser',schema({query:{type:'string'},limit:{type:'number'}},['query']),async({query,limit=6})=>{const max=Math.max(1,Math.min(Number(limit)||6,10)),url=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`;const html=await fetchText(url,{max:180000});const rows=[];const re=/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]*?<a[^>]+class="[^"]*result__snippet[^"]*"[^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(html))&&rows.length<max){let href=m[1];try{const wrapped=new URL(href,'https://duckduckgo.com');const uddg=wrapped.searchParams.get('uddg');if(uddg)href=decodeURIComponent(uddg);}catch{}rows.push({title:decode(m[2]),url:href,snippet:decode(m[3])});}if(!rows.length)return result('live_web_search',false,'Search provider returned no parseable results');return result('live_web_search',true,'Live web search completed',{query,results:rows});}),
  read_web_page:tool('read','Read useful text from a public web page URL for research',schema({url:{type:'string'},max_chars:{type:'number'}},['url']),async({url,max_chars=18000})=>{const u=await assertPublicUrl(url),html=await fetchText(u.href,{max:250000});const cleaned=decode(html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' '));return result('read_web_page',true,'Web page read',{url:u.href,text:cleaned.slice(0,Math.max(1000,Math.min(Number(max_chars)||18000,30000)))});}),
  wikipedia_search:tool('read','Search Wikipedia for background/reference information',schema({query:{type:'string'},limit:{type:'number'}},['query']),async({query,limit=5})=>{const url=`https://en.wikipedia.org/w/api.php?action=query&list=search&format=json&origin=*&srlimit=${Math.max(1,Math.min(Number(limit)||5,10))}&srsearch=${encodeURIComponent(query)}`;const data=JSON.parse(await fetchText(url,{max:200000}));return result('wikipedia_search',true,'Wikipedia search completed',{query,results:(data?.query?.search||[]).map(x=>({title:x.title,snippet:decode(x.snippet),pageid:x.pageid}))});})
};
