import dns from 'node:dns/promises';
import net from 'node:net';

const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const decode=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const privateIp=ip=>{const v=String(ip||'').toLowerCase();if(net.isIPv4(v))return v.startsWith('127.')||v.startsWith('10.')||v.startsWith('192.168.')||/^172\.(1[6-9]|2\d|3[01])\./.test(v)||v.startsWith('169.254.')||v==='0.0.0.0';return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe80:')||v.startsWith('::ffff:127.');};
async function assertPublicUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('Only public http/https URLs are allowed');const host=u.hostname.toLowerCase();if(['localhost','0.0.0.0','::1'].includes(host)||host.endsWith('.local')||host.endsWith('.internal'))throw new Error('Local/private addresses are blocked');const records=await dns.lookup(host,{all:true});if(!records.length||records.some(x=>privateIp(x.address)))throw new Error('Local/private addresses are blocked');return u;}
async function fetchPublicText(raw,{timeout=12000,max=120000,maxRedirects=5,headers={}}={}){let u=await assertPublicUrl(raw);for(let hop=0;hop<=maxRedirects;hop++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(u.href,{headers:{'user-agent':'Mozilla/5.0 BlackCloverResearch/0.5','accept':'text/html,application/xhtml+xml,application/xml,text/plain;q=0.9,*/*;q=0.5',...headers},redirect:'manual',signal:controller.signal});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw new Error('Redirect without location');u=await assertPublicUrl(new URL(loc,u).href);continue;}if(!r.ok)throw new Error(`HTTP ${r.status}`);const text=await r.text();return {url:u.href,text:text.slice(0,max),contentType:r.headers.get('content-type')||''};}finally{clearTimeout(timer);}}throw new Error('Too many redirects');}
async function searchDuck(query,limit){const url=`https://html.duckduckgo.com/html/?q=${encodeURIComponent(query)}`,{text:html}=await fetchPublicText(url,{max:220000});const rows=[];const re=/<a[^>]+class="[^"]*result__a[^"]*"[^>]+href="([^"]+)"[^>]*>([\s\S]*?)<\/a>[\s\S]*?(?:class="[^"]*result__snippet[^"]*"[^>]*>)([\s\S]*?)(?:<\/a>|<\/div>)/gi;let m;while((m=re.exec(html))&&rows.length<limit){let href=decode(m[1]);try{const wrapped=new URL(href,'https://duckduckgo.com');const uddg=wrapped.searchParams.get('uddg');if(uddg)href=decodeURIComponent(uddg);}catch{}if(/^https?:/i.test(href))rows.push({title:decode(m[2]),url:href,snippet:decode(m[3]),source:'duckduckgo'});}return rows;}
async function searchBingRss(query,limit){const url=`https://www.bing.com/search?format=rss&q=${encodeURIComponent(query)}`,{text:xml}=await fetchPublicText(url,{max:180000});const out=[];const re=/<item>[\s\S]*?<title>([\s\S]*?)<\/title>[\s\S]*?<link>([\s\S]*?)<\/link>[\s\S]*?<description>([\s\S]*?)<\/description>[\s\S]*?<\/item>/gi;let m;while((m=re.exec(xml))&&out.length<limit)out.push({title:decode(m[1]),url:decode(m[2]),snippet:decode(m[3]),source:'bing-rss'});return out;}
async function liveSearch(query,limit=6){const max=Math.max(1,Math.min(Number(limit)||6,10));try{const rows=await searchDuck(query,max);if(rows.length)return rows;}catch{}return searchBingRss(query,max);}
const cleanPage=html=>decode(String(html).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<noscript[\s\S]*?<\/noscript>/gi,' ').replace(/<svg[\s\S]*?<\/svg>/gi,' '));
const compactWikiQuery=q=>{const raw=String(q||'').trim(),latin=raw.match(/\b[A-Za-z][A-Za-z0-9.+#-]{1,20}\b/g)||[];if(latin.length===1&&/[\u0600-\u06FF]/.test(raw))return latin[0];return raw.replace(/(?:چیست|چیه|چی هست|کیه|کجاست|کجا هست|چرا|چطور|چطوری|چگونه|کار می.?کنه|کار می.?کند|یعنی چی|معنی(?:ش)? چیه|توضیح بده|بگو|لطفا|لطفاً|\?|؟)/gi,' ').replace(/\s+/g,' ').trim()||raw;};


export async function researchTopic(query,{sources=4,search=liveSearch,read=fetchPublicText}={}){
  const count=Math.max(2,Math.min(Number(sources)||4,6)),rows=await search(query,Math.min(10,count+5));
  const candidates=[...new Map(rows.map(row=>[row.url,row])).values()];
  const fetchRow=async row=>{try{const page=await read(row.url,{max:180000,timeout:6500});const text=cleanPage(page.text).slice(0,10000);return {...row,url:page.url,text,readFailed:!text,searchSource:row.source};}catch(error){return {...row,text:'',readFailed:true,readError:String(error.message||error).slice(0,160),searchSource:row.source};}};
  let pages=await Promise.all(candidates.slice(0,count).map(fetchRow));
  if(pages.filter(s=>s.text&&!s.readFailed).length<count&&candidates.length>count)pages.push(...await Promise.all(candidates.slice(count).map(fetchRow)));
  const readPages=pages.filter(s=>s.text&&!s.readFailed),snippets=pages.filter(s=>s.readFailed);
  const picked=[...readPages,...snippets].slice(0,count);
  return {query,retrievedAt:new Date().toISOString(),sources:picked,quality:readPages.length>=count?'full-text':readPages.length?'partial-text':'search-snippets',readSources:Math.min(readPages.length,count),attemptedSources:pages.length};
}

export const researchTools={
  live_web_search:tool('read','Search the live public web for current information without opening the browser. Returns source URLs and retrieval time',schema({query:{type:'string'},limit:{type:'number'}},['query']),async({query,limit=6})=>{const rows=await liveSearch(query,limit);if(!rows.length)return result('live_web_search',false,'Search providers returned no results');return result('live_web_search',true,'Live web search completed',{query,retrievedAt:new Date().toISOString(),results:rows});}),
  read_web_page:tool('read','Read useful text from a public web page. Every redirect is revalidated to block local/private-network access',schema({url:{type:'string'},max_chars:{type:'number'}},['url']),async({url,max_chars=18000})=>{const fetched=await fetchPublicText(url,{max:280000}),cleaned=cleanPage(fetched.text),n=Math.max(1000,Math.min(Number(max_chars)||18000,40000));return result('read_web_page',true,'Web page read',{url:fetched.url,retrievedAt:new Date().toISOString(),text:cleaned.slice(0,n)});}),
  wikipedia_search:tool('read','Search Wikipedia for background/reference information and return a concise intro extract',schema({query:{type:'string'},limit:{type:'number'}},['query']),async({query,limit=5})=>{const raw=String(query||''),lang=/[\u0600-\u06FF]/.test(raw)?'fa':'en',searchQuery=compactWikiQuery(raw),n=Math.max(1,Math.min(Number(limit)||5,10)),url=`https://${lang}.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${encodeURIComponent(searchQuery)}&gsrlimit=${n}&prop=extracts&exintro=1&explaintext=1&exchars=1800&format=json&origin=*`,fetched=await fetchPublicText(url,{max:260000}),data=JSON.parse(fetched.text),pages=Object.values(data?.query?.pages||{}).sort((a,b)=>(a.index??999)-(b.index??999));return result('wikipedia_search',true,'Wikipedia search completed',{query:raw,searchQuery,language:lang,retrievedAt:new Date().toISOString(),results:pages.map(x=>({title:x.title,snippet:decode(x.extract||''),text:decode(x.extract||''),pageid:x.pageid,url:`https://${lang}.wikipedia.org/?curid=${x.pageid}`}))});}),
  research_topic:tool('read','Research a public topic across multiple live sources. Read candidate pages in parallel; if pages cannot be read try additional results, and disclose whether only search snippets are available.',schema({query:{type:'string'},sources:{type:'number'}},['query']),async({query,sources=4})=>{const data=await researchTopic(query,{sources});return result('research_topic',data.sources.length>0,data.quality==='search-snippets'?'Search snippets retrieved; full page text unavailable':'Multi-source research completed',data);})
};
