import { reminders } from './ReminderStore.js';
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
export const schedulerTools={
  create_reminder:tool('low','Create a durable local reminder that survives application and Windows restarts. due_at must be an ISO date/time. Optional interval_minutes repeats it',{type:'object',properties:{message:{type:'string'},title:{type:'string'},due_at:{type:'string'},interval_minutes:{type:'number'},category:{type:'string'},priority:{type:'string',enum:['low','normal','high']}},required:['message','due_at']},async({message,title='',due_at,interval_minutes=0,category='general',priority='normal'})=>result('create_reminder',true,'Reminder created',await reminders.create({message,title,dueAt:due_at,intervalMinutes:interval_minutes,category,priority}))),
  list_reminders:tool('read','List active local reminders and schedules',{type:'object',properties:{include_done:{type:'boolean'}},required:[]},async({include_done=false})=>result('list_reminders',true,'Reminders listed',await reminders.list({includeDone:include_done}))),
  update_reminder:tool('low','Edit a reminder message, due time, repeat interval, category or priority',{type:'object',properties:{id:{type:'string'},message:{type:'string'},title:{type:'string'},due_at:{type:'string'},interval_minutes:{type:'number'},category:{type:'string'},priority:{type:'string',enum:['low','normal','high']}},required:['id']},async({id,due_at,...patch})=>{const x=await reminders.update(id,{...patch,...(due_at?{dueAt:due_at}:{})});return result('update_reminder',Boolean(x),x?'Reminder updated':'Reminder not found',x);}),
  snooze_reminder:tool('low','Snooze an existing reminder for a number of minutes',{type:'object',properties:{id:{type:'string'},minutes:{type:'number'}},required:['id']},async({id,minutes=10})=>{const x=await reminders.snooze(id,minutes);return result('snooze_reminder',Boolean(x),x?'Reminder snoozed':'Reminder not found',x);}),
  complete_reminder:tool('low','Mark a reminder as completed without permanently deleting its history',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const ok=await reminders.complete(id);return result('complete_reminder',ok,ok?'Reminder completed':'Reminder not found',{id});}),
  cancel_reminder:tool('sensitive','Cancel an existing reminder by id while keeping its history',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const ok=await reminders.cancel(id);return result('cancel_reminder',ok,ok?'Reminder cancelled':'Reminder not found',{id});}),
  remove_reminder:tool('sensitive','Permanently remove a reminder and its local history by id',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const ok=await reminders.remove(id);return result('remove_reminder',ok,ok?'Reminder removed':'Reminder not found',{id});})
};
