import { reminders } from './ReminderStore.js';
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
export const schedulerTools={
  create_reminder:tool('low','Create a durable local reminder that only notifies the user. due_at must be an ISO date/time. Optional interval_minutes repeats it',{type:'object',properties:{message:{type:'string'},due_at:{type:'string'},interval_minutes:{type:'number'}},required:['message','due_at']},async({message,due_at,interval_minutes=0})=>result('create_reminder',true,'Reminder created',await reminders.create({message,dueAt:due_at,intervalMinutes:interval_minutes}))),
  create_scheduled_action:tool('low','Schedule a real future Agent action. At due_at Maria re-enters the instruction into the same chat/action brain and executes the available tools automatically. Use this instead of create_reminder when the user says to DO something later (research, prepare, open, send, organize, etc). Sensitive steps still require confirmation and are never silently approved.',{type:'object',properties:{instruction:{type:'string'},due_at:{type:'string'},interval_minutes:{type:'number'},label:{type:'string'}},required:['instruction','due_at']},async({instruction,due_at,interval_minutes=0,label=''})=>result('create_scheduled_action',true,'Executable scheduled action created',await reminders.createAction({instruction,dueAt:due_at,intervalMinutes:interval_minutes,label}))),
  list_reminders:tool('read','List active reminders and executable scheduled actions',{type:'object',properties:{},required:[]},async()=>result('list_reminders',true,'Schedules listed',await reminders.list())),
  cancel_reminder:tool('sensitive','Cancel an existing reminder or scheduled action by id',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const ok=await reminders.cancel(id);return result('cancel_reminder',ok,ok?'Schedule cancelled':'Schedule not found',{id});})
};
