import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import dns from 'node:dns/promises';
import net from 'node:net';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import JSZip from 'jszip';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const encode=x=>Buffer.from(JSON.stringify(x),'utf8').toString('base64');
const ext=p=>path.extname(String(p||'')).toLowerCase();
async function where(exe){try{const {stdout}=await execFileAsync('where.exe',[exe],{windowsHide:true,timeout:10000});return stdout.trim().split(/\r?\n/)[0]||null;}catch{return null;}}
async function excelComAvailable(){try{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',"try{$x=New-Object -ComObject Excel.Application;$x.Quit();[Runtime.InteropServices.Marshal]::ReleaseComObject($x)|Out-Null;'true'}catch{'false'}"],{windowsHide:true,timeout:15000});return stdout.trim()==='true';}catch{return false;}}
async function psExcel(payload,body,{timeout=120000}={}){const data=encode(payload),script=`$ErrorActionPreference='Stop';$p=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('${data}'))|ConvertFrom-Json;$excel=$null;$wb=$null;try{$excel=New-Object -ComObject Excel.Application;$excel.Visible=$false;$excel.DisplayAlerts=$false;$wb=$excel.Workbooks.Open($p.file);${body}}finally{if($wb){try{$wb.Close($false)}catch{};try{[Runtime.InteropServices.Marshal]::ReleaseComObject($wb)|Out-Null}catch{}};if($excel){try{$excel.Quit()}catch{};try{[Runtime.InteropServices.Marshal]::ReleaseComObject($excel)|Out-Null}catch{}};[GC]::Collect();[GC]::WaitForPendingFinalizers()}`;const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout,maxBuffer:16_000_000});return stdout.trim()?JSON.parse(stdout):null;}
async function runPython(code,payload,{timeout=120000}={}){const py=await where('py.exe')||await where('python.exe');if(!py)throw new Error('Python is not installed');const args=path.basename(py).toLowerCase()==='py.exe'?['-3','-c',code,encode(payload)]:['-c',code,encode(payload)];const {stdout}=await execFileAsync(py,args,{windowsHide:true,timeout,maxBuffer:16_000_000});return stdout.trim()?JSON.parse(stdout):null;}
async function backup(file){const p=path.resolve(file),e=path.extname(p),base=p.slice(0,-e.length),stamp=new Date().toISOString().replace(/[:.]/g,'-'),dst=`${base}.maria-backup-${stamp}${e}`;await fs.copyFile(p,dst);return dst;}
const pyPrelude=`import sys,json,base64,os\np=json.loads(base64.b64decode(sys.argv[1]).decode('utf-8'))\n`;
async function listSheets(file){if(await excelComAvailable())return psExcel({file:path.resolve(file)},"$out=@();foreach($s in $wb.Worksheets){$out+=$s.Name};$out|ConvertTo-Json -Compress");return runPython(pyPrelude+`from openpyxl import load_workbook\nwb=load_workbook(p['file'],read_only=True,keep_vba=p['file'].lower().endswith('.xlsm'))\nprint(json.dumps(wb.sheetnames,ensure_ascii=False))`,{file:path.resolve(file)});}
async function readRange(file,sheet,range,maxCells=5000){const payload={file:path.resolve(file),sheet:sheet||'',range:range||'',maxCells:Math.max(1,Math.min(Number(maxCells)||5000,10000))};if(await excelComAvailable())return psExcel(payload,"$ws=if($p.sheet){$wb.Worksheets.Item($p.sheet)}else{$wb.Worksheets.Item(1)};$rg=if($p.range){$ws.Range($p.range)}else{$ws.UsedRange};$rows=[Math]::Min($rg.Rows.Count,[Math]::Max(1,[Math]::Floor($p.maxCells/[Math]::Max(1,$rg.Columns.Count))));$cols=[Math]::Min($rg.Columns.Count,$p.maxCells);$cells=@();for($r=1;$r -le $rows;$r++){for($c=1;$c -le $cols;$c++){$cell=$rg.Cells.Item($r,$c);$cells+=[pscustomobject]@{address=$cell.Address($false,$false);value=$cell.Value2;formula=$cell.Formula}}};[pscustomobject]@{sheet=$ws.Name;range=$rg.Address($false,$false);rows=$rows;columns=$cols;cells=$cells}|ConvertTo-Json -Depth 5 -Compress");return runPython(pyPrelude+`from openpyxl import load_workbook\nfrom openpyxl.utils.cell import range_boundaries\nwb=load_workbook(p['file'],data_only=False,keep_vba=p['file'].lower().endswith('.xlsm'))\nws=wb[p['sheet']] if p.get('sheet') else wb.worksheets[0]\nif p.get('range'):\n minc,minr,maxc,maxr=range_boundaries(p['range'])\nelse:\n minc,minr,maxc,maxr=1,1,ws.max_column,ws.max_row\ncols=max(1,maxc-minc+1); maxrows=max(1,min(maxr-minr+1,int(p['maxCells'])//cols)); maxr=min(maxr,minr+maxrows-1)\ncells=[]\nfor row in ws.iter_rows(min_row=minr,max_row=maxr,min_col=minc,max_col=maxc):\n for cell in row: cells.append({'address':cell.coordinate,'value':cell.value,'formula':cell.value if isinstance(cell.value,str) and cell.value.startswith('=') else None})\nprint(json.dumps({'sheet':ws.title,'range':f'{ws.cell(minr,minc).coordinate}:{ws.cell(maxr,maxc).coordinate}','rows':maxr-minr+1,'columns':maxc-minc+1,'cells':cells},ensure_ascii=False,default=str))`,payload);}
async function setCells(file,sheet,changes){const p=path.resolve(file),backupPath=await backup(p),payload={file:p,sheet:sheet||'',changes:(changes||[]).slice(0,2000)};if(await excelComAvailable()){const data=await psExcel(payload,"$ws=if($p.sheet){$wb.Worksheets.Item($p.sheet)}else{$wb.Worksheets.Item(1)};foreach($ch in $p.changes){$cell=$ws.Range($ch.cell);if($null -ne $ch.formula -and $ch.formula -ne ''){$cell.Formula=$ch.formula}else{$cell.Value2=$ch.value}};$wb.Save();[pscustomobject]@{sheet=$ws.Name;changed=$p.changes.Count}|ConvertTo-Json -Compress",{timeout:180000});return {...data,backup:backupPath,engine:'excel-com'};}const data=await runPython(pyPrelude+`from openpyxl import load_workbook\nwb=load_workbook(p['file'],keep_vba=p['file'].lower().endswith('.xlsm'))\nws=wb[p['sheet']] if p.get('sheet') else wb.worksheets[0]\nfor ch in p.get('changes',[]): ws[ch['cell']]=ch.get('formula') if ch.get('formula') not in (None,'') else ch.get('value')\nwb.save(p['file'])\nprint(json.dumps({'sheet':ws.title,'changed':len(p.get('changes',[]))},ensure_ascii=False))`,payload,{timeout:180000});return {...data,backup:backupPath,engine:'openpyxl'};}
async function appendRows(file,sheet,rows,startColumn=1){const p=path.resolve(file),backupPath=await backup(p),payload={file:p,sheet:sheet||'',rows:(rows||[]).slice(0,1000),startColumn:Math.max(1,Number(startColumn)||1)};if(await excelComAvailable()){const data=await psExcel(payload,"$ws=if($p.sheet){$wb.Worksheets.Item($p.sheet)}else{$wb.Worksheets.Item(1)};$last=$ws.UsedRange.Row+$ws.UsedRange.Rows.Count-1;if($last -lt 1){$last=0};$r=$last+1;foreach($row in $p.rows){$c=$p.startColumn;foreach($v in $row){$ws.Cells.Item($r,$c).Value2=$v;$c++};$r++};$wb.Save();[pscustomobject]@{sheet=$ws.Name;startRow=$last+1;rowsAdded=$p.rows.Count}|ConvertTo-Json -Compress",{timeout:180000});return {...data,backup:backupPath,engine:'excel-com'};}const data=await runPython(pyPrelude+`from openpyxl import load_workbook\nwb=load_workbook(p['file'],keep_vba=p['file'].lower().endswith('.xlsm'))\nws=wb[p['sheet']] if p.get('sheet') else wb.worksheets[0]\nstart=ws.max_row+1\nfor ri,row in enumerate(p.get('rows',[]),start=start):\n for ci,v in enumerate(row,start=int(p.get('startColumn',1))): ws.cell(ri,ci).value=v\nwb.save(p['file'])\nprint(json.dumps({'sheet':ws.title,'startRow':start,'rowsAdded':len(p.get('rows',[]))},ensure_ascii=False))`,payload,{timeout:180000});return {...data,backup:backupPath,engine:'openpyxl'};}
async function addImage(file,sheet,image,cell='A1',width=0,height=0){const p=path.resolve(file),img=path.resolve(image),backupPath=await backup(p),payload={file:p,sheet:sheet||'',image:img,cell,width:Number(width)||0,height:Number(height)||0};if(await excelComAvailable()){const data=await psExcel(payload,"$ws=if($p.sheet){$wb.Worksheets.Item($p.sheet)}else{$wb.Worksheets.Item(1)};$anchor=$ws.Range($p.cell);$shape=$ws.Shapes.AddPicture($p.image,$false,$true,$anchor.Left,$anchor.Top,-1,-1);if($p.width -gt 0){$shape.Width=$p.width};if($p.height -gt 0){$shape.Height=$p.height};$wb.Save();[pscustomobject]@{sheet=$ws.Name;cell=$p.cell;image=$p.image}|ConvertTo-Json -Compress",{timeout:180000});return {...data,backup:backupPath,engine:'excel-com'};}const data=await runPython(pyPrelude+`from openpyxl import load_workbook\nfrom openpyxl.drawing.image import Image\nwb=load_workbook(p['file'],keep_vba=p['file'].lower().endswith('.xlsm'))\nws=wb[p['sheet']] if p.get('sheet') else wb.worksheets[0]\nimg=Image(p['image'])\nif p.get('width',0)>0: img.width=p['width']\nif p.get('height',0)>0: img.height=p['height']\nws.add_image(img,p.get('cell','A1'));wb.save(p['file'])\nprint(json.dumps({'sheet':ws.title,'cell':p.get('cell','A1'),'image':p['image']},ensure_ascii=False))`,payload,{timeout:180000});return {...data,backup:backupPath,engine:'openpyxl'};}
async function listHyperlinks(file){const p=path.resolve(file);if(await excelComAvailable())return psExcel({file:p},"$out=@();foreach($ws in $wb.Worksheets){foreach($h in $ws.Hyperlinks){$out+=[pscustomobject]@{sheet=$ws.Name;cell=$h.Range.Address($false,$false);text=$h.TextToDisplay;address=$h.Address;subAddress=$h.SubAddress}}};$out|ConvertTo-Json -Depth 4 -Compress");return runPython(pyPrelude+`from openpyxl import load_workbook\nwb=load_workbook(p['file'],read_only=False,data_only=False,keep_vba=p['file'].lower().endswith('.xlsm'))\nout=[]\nfor ws in wb.worksheets:\n for row in ws.iter_rows():\n  for c in row:\n   if c.hyperlink: out.append({'sheet':ws.title,'cell':c.coordinate,'text':str(c.value or ''),'address':c.hyperlink.target,'subAddress':c.hyperlink.location})\nprint(json.dumps(out,ensure_ascii=False))`,{file:p},{timeout:180000});}
const privateIp=ip=>{const v=String(ip||'').toLowerCase();if(net.isIPv4(v))return v.startsWith('127.')||v.startsWith('10.')||v.startsWith('192.168.')||/^172\.(1[6-9]|2\d|3[01])\./.test(v)||v.startsWith('169.254.')||v==='0.0.0.0';return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe80:');};
async function publicUrl(raw){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('not public http');const rec=await dns.lookup(u.hostname,{all:true});if(!rec.length||rec.some(x=>privateIp(x.address)))throw new Error('private address blocked');return u;}
async function downloadImage(raw,dest){let u=await publicUrl(raw);for(let i=0;i<5;i++){const r=await fetch(u,{redirect:'manual',signal:AbortSignal.timeout(20000)});if([301,302,303,307,308].includes(r.status)){const loc=r.headers.get('location');if(!loc)throw new Error('redirect missing');u=await publicUrl(new URL(loc,u).href);continue;}if(!r.ok)throw new Error(`HTTP ${r.status}`);const type=r.headers.get('content-type')||'';if(!type.toLowerCase().startsWith('image/'))throw new Error('link is not an image');const buf=Buffer.from(await r.arrayBuffer());if(buf.length>20_000_000)throw new Error('image too large');await fs.writeFile(dest,buf);return {path:dest,url:u.href,contentType:type,size:buf.length};}throw new Error('too many redirects');}
async function collectImages(file,outputDir){const p=path.resolve(file),base=path.basename(p,path.extname(p)).replace(/[^\p{L}\p{N}._-]+/gu,'_'),out=outputDir?path.resolve(outputDir):path.join(os.homedir(),'Downloads','BlackClover-Workbook-Media',`${base}-${Date.now()}`);await fs.mkdir(out,{recursive:true});const images=[];if(['.xlsx','.xlsm','.xltx','.xltm'].includes(ext(p))){try{const zip=await JSZip.loadAsync(await fs.readFile(p));for(const [name,entry] of Object.entries(zip.files)){if(entry.dir||!name.toLowerCase().startsWith('xl/media/'))continue;const dest=path.join(out,path.basename(name));await fs.writeFile(dest,await entry.async('nodebuffer'));images.push({kind:'embedded',path:dest,source:name});}}catch{}}
  const links=await listHyperlinks(p).catch(()=>[]);let n=1;for(const h of Array.isArray(links)?links:links?[links]:[]){const address=String(h.address||'').trim();if(!address)continue;try{if(/^https?:/i.test(address)){const pathname=new URL(address).pathname,guess=path.extname(pathname).match(/^\.[a-z0-9]{2,5}$/i)?.[0]||'.img',dest=path.join(out,`linked-${n++}${guess}`);images.push({kind:'linked-web',...(await downloadImage(address,dest)),sheet:h.sheet,cell:h.cell});}else{const local=path.resolve(path.dirname(p),address.replace(/^file:\/\//i,''));if(/\.(png|jpe?g|gif|webp|bmp|tiff?)$/i.test(local)){const dest=path.join(out,`linked-${n++}${path.extname(local)}`);await fs.copyFile(local,dest);images.push({kind:'linked-local',path:dest,source:local,sheet:h.sheet,cell:h.cell});}}}catch{}}
  return {outputDirectory:out,count:images.length,images,hyperlinks:Array.isArray(links)?links:links?[links]:[]};}
export const spreadsheetTools={
  excel_status:tool('read','Check whether native Microsoft Excel COM automation is available and whether the Python OpenPyXL fallback is installed',schema({}),async()=>{let openpyxl=false;try{await runPython(pyPrelude+`import openpyxl\nprint(json.dumps({'ok':True,'version':openpyxl.__version__}))`,{});openpyxl=true;}catch{}return result('excel_status',true,'Spreadsheet engines checked',{excelCom:await excelComAvailable(),openpyxl});}),
  excel_list_sheets:tool('read','List worksheets in an Excel workbook (.xlsx/.xlsm/.xls when Microsoft Excel is available)',schema({file:{type:'string'}},['file']),async({file})=>result('excel_list_sheets',true,'Workbook sheets listed',{file:path.resolve(file),sheets:await listSheets(file)})),
  excel_read_range:tool('read','Read cell values and formulas from a worksheet range. If range is omitted, reads the used range up to a safe cell limit',schema({file:{type:'string'},sheet:{type:'string'},range:{type:'string'},max_cells:{type:'number'}},['file']),async({file,sheet='',range='',max_cells=5000})=>result('excel_read_range',true,'Workbook range read',await readRange(file,sheet,range,max_cells))),
  excel_set_cells:tool('sensitive','Set values or formulas in Excel cells while automatically creating a timestamped backup first',schema({file:{type:'string'},sheet:{type:'string'},changes:{type:'array',items:{type:'object',properties:{cell:{type:'string'},value:{},formula:{type:'string'}},required:['cell']}}},['file','changes']),async({file,sheet='',changes=[]})=>result('excel_set_cells',true,'Workbook cells updated',await setCells(file,sheet,changes))),
  excel_append_rows:tool('sensitive','Append rows to an Excel worksheet while automatically creating a timestamped backup first',schema({file:{type:'string'},sheet:{type:'string'},rows:{type:'array',items:{type:'array'}},start_column:{type:'number'}},['file','rows']),async({file,sheet='',rows=[],start_column=1})=>result('excel_append_rows',true,'Rows appended to workbook',await appendRows(file,sheet,rows,start_column))),
  excel_add_image:tool('sensitive','Insert an image into an Excel worksheet at a target cell with automatic backup',schema({file:{type:'string'},sheet:{type:'string'},image:{type:'string'},cell:{type:'string'},width:{type:'number'},height:{type:'number'}},['file','image']),async({file,sheet='',image,cell='A1',width=0,height=0})=>result('excel_add_image',true,'Image inserted into workbook',await addImage(file,sheet,image,cell,width,height))),
  excel_list_hyperlinks:tool('read','List hyperlinks in an Excel workbook with worksheet and cell locations',schema({file:{type:'string'}},['file']),async({file})=>result('excel_list_hyperlinks',true,'Workbook hyperlinks listed',{file:path.resolve(file),links:await listHyperlinks(file)})),
  excel_collect_images:tool('read','Extract embedded workbook images and collect reachable image hyperlinks into a normal folder so they can be viewed or sent to messaging apps',schema({file:{type:'string'},output_directory:{type:'string'}},['file']),async({file,output_directory=''})=>result('excel_collect_images',true,'Workbook images collected',await collectImages(file,output_directory)))
};
