import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { execFile,spawn } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const schema=(properties,required=[])=>({type:'object',properties,required});
const q=s=>String(s??'').replaceAll("'","''");
const appData=()=>process.env.BLACK_CLOVER_DATA_DIR||path.join(process.env.APPDATA||path.join(os.homedir(),'.black-clover'),'BlackClover');
async function where(exe){try{const {stdout}=await execFileAsync('where.exe',[exe],{windowsHide:true,timeout:10000});return stdout.trim().split(/\r?\n/)[0]||null;}catch{return null;}}
async function exists(p){try{await fs.access(p);return true;}catch{return false;}}
async function resolveEs(){const candidates=[path.join(appData(),'runtime','everything','es.exe'),path.join(process.env.LOCALAPPDATA||'','Microsoft','WinGet','Links','es.exe')];for(const p of candidates)if(await exists(p))return p;return where('es.exe');}
async function resolveEverything(){const candidates=[path.join(process.env.PROGRAMFILES||'','Everything','Everything.exe'),path.join(process.env.LOCALAPPDATA||'','Everything','Everything.exe')];for(const p of candidates)if(await exists(p))return p;return where('Everything.exe');}
async function ensureEverything(){const exe=await resolveEverything();if(!exe)return false;try{const {stdout}=await execFileAsync('tasklist.exe',['/FI','IMAGENAME eq Everything.exe','/NH'],{windowsHide:true,timeout:10000});if(!/Everything\.exe/i.test(stdout)){const child=spawn(exe,['-startup'],{detached:true,stdio:'ignore',windowsHide:true});child.unref();await new Promise(r=>setTimeout(r,1200));}return true;}catch{return false;}}
async function fixedDrives(){try{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',"Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3' | Select-Object DeviceID,VolumeName,FileSystem,Size,FreeSpace | ConvertTo-Json -Compress"],{windowsHide:true,timeout:15000,maxBuffer:2_000_000});if(!stdout.trim())return[];const x=JSON.parse(stdout);return (Array.isArray(x)?x:[x]).map(d=>({drive:d.DeviceID,label:d.VolumeName||'',fileSystem:d.FileSystem||'',size:Number(d.Size||0),free:Number(d.FreeSpace||0)}));}catch{return[];}}
async function everythingSearch(query,{extensions=[],limit=50,kind='file'}={}){const es=await resolveEs();if(!es)return null;await ensureEverything();const max=Math.max(1,Math.min(Number(limit)||50,500));let search=String(query||'').trim();const exts=(extensions||[]).map(x=>String(x).replace(/^\./,'').replace(/[^a-z0-9]/gi,'')).filter(Boolean);if(exts.length)search+=` ext:${exts.join(';')}`;if(kind==='file')search+=' file:';if(kind==='folder')search+=' folder:';try{const {stdout}=await execFileAsync(es,['-n',String(max),'-full-path-and-name',search],{windowsHide:true,timeout:25000,maxBuffer:12_000_000});return stdout.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).slice(0,max);}catch{return null;}}
async function fallbackSearch(query,{extensions=[],limit=50,kind='file'}={}){const max=Math.max(1,Math.min(Number(limit)||50,200)),needle=q(query),exts=(extensions||[]).map(x=>String(x).replace(/^\./,'').replace(/[^a-z0-9]/gi,'')).filter(Boolean);const filter=exts.length?`$ext=@(${exts.map(x=>`'.${q(x)}'`).join(',')});`:'$ext=@();';const kindExpr=kind==='folder'?'$_.PSIsContainer':kind==='any'?'$true':'!$_.PSIsContainer';const script=`$ErrorActionPreference='SilentlyContinue';${filter}$max=${max};$out=New-Object System.Collections.Generic.List[string];$drives=Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3'|Select-Object -ExpandProperty DeviceID;foreach($d in $drives){Get-ChildItem ($d+'\\') -Force -Recurse -ErrorAction SilentlyContinue | Where-Object { ${kindExpr} -and $_.Name -like '*${needle}*' -and ($ext.Count -eq 0 -or $_.Extension -in $ext) } | ForEach-Object {if($out.Count -lt $max){$out.Add($_.FullName)}};if($out.Count -ge $max){break}};$out|ConvertTo-Json -Compress`;
  try{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:120000,maxBuffer:12_000_000});if(!stdout.trim())return[];const x=JSON.parse(stdout);return (Array.isArray(x)?x:[x]).filter(Boolean);}catch(e){if(e.killed||e.signal)return[];throw e;}}
async function globalSearch(query,opts={}){let paths=await everythingSearch(query,opts);let engine='everything';if(paths===null){paths=await fallbackSearch(query,opts);engine='powershell-fallback';}const out=[];for(const p of paths){try{const s=await fs.stat(p);out.push({name:path.basename(p),path:p,type:s.isDirectory()?'directory':'file',size:s.isFile()?s.size:0,modified:s.mtime.toISOString(),extension:s.isFile()?path.extname(p).toLowerCase():''});}catch{out.push({name:path.basename(p),path:p,type:'unknown'});} }return {engine,items:out};}
export const storageTools={
  storage_overview:tool('read','List fixed local Windows drives and capacity so Maria understands the machine storage layout',schema({}),async()=>result('storage_overview',true,'Storage overview loaded',{drives:await fixedDrives(),everythingCli:Boolean(await resolveEs()),everything:Boolean(await resolveEverything())})),
  global_find_files:tool('read','Find a file or folder by partial name across all fixed local drives. Uses Everything instant index when installed and a slower Windows fallback otherwise',schema({query:{type:'string'},extensions:{type:'array',items:{type:'string'}},limit:{type:'number'},kind:{type:'string',enum:['file','folder','any']}},['query']),async({query,extensions=[],limit=50,kind='file'})=>{const data=await globalSearch(query,{extensions,limit,kind});return result('global_find_files',true,`Global storage search completed with ${data.engine}`,data);}),
  open_named_file:tool('low','Find a file anywhere on fixed local drives by name and open the best match with its default Windows application',schema({name:{type:'string'},extensions:{type:'array',items:{type:'string'}}},['name']),async({name,extensions=[]})=>{const data=await globalSearch(name,{extensions,limit:10,kind:'file'});const item=data.items[0];if(!item)return result('open_named_file',false,'No matching file found',{query:name,engine:data.engine});spawn('explorer.exe',[item.path],{detached:true,windowsHide:true});return result('open_named_file',true,'Matching file opened',{...item,engine:data.engine,candidates:data.items.slice(0,10)});}),
  reveal_named_file:tool('low','Find a file anywhere on fixed local drives and reveal the best match in Windows Explorer',schema({name:{type:'string'},extensions:{type:'array',items:{type:'string'}}},['name']),async({name,extensions=[]})=>{const data=await globalSearch(name,{extensions,limit:10,kind:'file'});const item=data.items[0];if(!item)return result('reveal_named_file',false,'No matching file found',{query:name,engine:data.engine});spawn('explorer.exe',['/select,',item.path],{detached:true,windowsHide:true});return result('reveal_named_file',true,'Matching file revealed',{...item,engine:data.engine});})
};
