import { execFile,spawn } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const empty={type:'object',properties:{},required:[]};
async function ps(script,{timeout=60000,maxBuffer=10_000_000}={}){const {stdout,stderr}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{windowsHide:true,timeout,maxBuffer});return {stdout:stdout.trim(),stderr:stderr.trim()};}
const json=async script=>{const {stdout}=await ps(`${script} | ConvertTo-Json -Depth 6 -Compress`);if(!stdout)return[];return JSON.parse(stdout);};
const open=(exe,args=[])=>{spawn(exe,args,{detached:true,windowsHide:true,stdio:'ignore'}).unref();};
const openSettings=(name,uri)=>tool('low',`Open Windows ${name} settings`,empty,async()=>{open('cmd.exe',['/c','start','',uri]);return result(`open_${name}`,true,`${name} opened`);});

export const systemDeepTools={
  performance_snapshot:tool('read','Read a lightweight CPU, memory and disk performance snapshot',empty,async()=>result('performance_snapshot',true,'Performance snapshot read',await json("$os=Get-CimInstance Win32_OperatingSystem;$cpu=(Get-Counter '\\Processor(_Total)\\% Processor Time').CounterSamples.CookedValue;$disk=(Get-Counter '\\PhysicalDisk(_Total)\\% Disk Time').CounterSamples.CookedValue;[pscustomobject]@{cpuPercent=[math]::Round($cpu,1);memoryUsedPercent=[math]::Round((1-($os.FreePhysicalMemory/$os.TotalVisibleMemorySize))*100,1);freeMemoryGB=[math]::Round($os.FreePhysicalMemory/1MB,2);diskBusyPercent=[math]::Round($disk,1);uptimeHours=[math]::Round(((Get-Date)-$os.LastBootUpTime).TotalHours,1)}"))),
  battery_status:tool('read','Read laptop battery charge, status and estimated runtime when available',empty,async()=>result('battery_status',true,'Battery status read',await json("Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue | Select-Object Name,EstimatedChargeRemaining,BatteryStatus,EstimatedRunTime,DesignVoltage"))),
  power_plan_status:tool('read','Read the active Windows power plan',empty,async()=>{const {stdout}=await execFileAsync('powercfg.exe',['/getactivescheme'],{windowsHide:true,timeout:10000});return result('power_plan_status',true,'Power plan read',{output:stdout.trim()});}),
  set_power_plan:tool('low','Switch Windows power mode between balanced, high_performance and power_saver',{type:'object',properties:{mode:{type:'string',enum:['balanced','high_performance','power_saver']}},required:['mode']},async({mode})=>{const ids={balanced:'381b4222-f694-41f0-9685-ff5bb260df2e',high_performance:'8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c',power_saver:'a1841308-3541-4fab-bc81-f71556f20b4a'};await execFileAsync('powercfg.exe',['/setactive',ids[mode]],{windowsHide:true,timeout:15000});return result('set_power_plan',true,`Power plan set to ${mode}`,{mode});}),
  disk_health_summary:tool('read','Read physical disk health and operational status',empty,async()=>result('disk_health_summary',true,'Disk health read',await json("Get-PhysicalDisk -ErrorAction SilentlyContinue | Select-Object FriendlyName,MediaType,HealthStatus,OperationalStatus,Size,AllocatedSize"))),
  volume_inventory:tool('read','List Windows volumes, drive letters, file systems and free space',empty,async()=>result('volume_inventory',true,'Volumes listed',await json("Get-Volume -ErrorAction SilentlyContinue | Select-Object DriveLetter,FileSystemLabel,FileSystem,HealthStatus,Size,SizeRemaining"))),
  process_resource_usage:tool('read','List processes using the most CPU and memory', {type:'object',properties:{limit:{type:'number'}},required:[]},async({limit=20})=>{const n=Math.max(5,Math.min(Number(limit)||20,80));return result('process_resource_usage',true,'Top resource processes listed',await json(`Get-Process | Sort-Object CPU -Descending | Select-Object -First ${n} Name,Id,CPU,@{n='WorkingSetMB';e={[math]::Round($_.WorkingSet64/1MB,1)}},MainWindowTitle`));}),
  startup_programs:tool('read','List configured Windows startup programs from common startup sources',empty,async()=>result('startup_programs',true,'Startup programs listed',await json("Get-CimInstance Win32_StartupCommand -ErrorAction SilentlyContinue | Select-Object Name,Command,Location,User"))),
  windows_services:tool('read','List Windows services, optionally filtered by name or display name',{type:'object',properties:{filter:{type:'string'},state:{type:'string',enum:['all','running','stopped']}},required:[]},async({filter='',state='all'})=>{const f=String(filter||'').replaceAll("'","''"),where=state==='running'?" | Where-Object {$_.Status -eq 'Running'}":state==='stopped'?" | Where-Object {$_.Status -eq 'Stopped'}":'';return result('windows_services',true,'Services listed',await json(`Get-Service ${where} | Where-Object {$_.Name -like '*${f}*' -or $_.DisplayName -like '*${f}*'} | Select-Object -First 200 Name,DisplayName,Status,StartType`));}),
  scheduled_tasks_summary:tool('read','List enabled scheduled tasks with next run times',{type:'object',properties:{filter:{type:'string'}},required:[]},async({filter=''})=>{const f=String(filter||'').replaceAll("'","''");return result('scheduled_tasks_summary',true,'Scheduled tasks listed',await json(`Get-ScheduledTask -ErrorAction SilentlyContinue | Where-Object {$_.State -ne 'Disabled' -and ($_.TaskName -like '*${f}*' -or $_.TaskPath -like '*${f}*')} | Select-Object -First 120 TaskName,TaskPath,State`));}),
  recent_system_errors:tool('read','Read recent Windows System and Application error events for troubleshooting',{type:'object',properties:{hours:{type:'number'},limit:{type:'number'}},required:[]},async({hours=24,limit=60})=>{const h=Math.max(1,Math.min(Number(hours)||24,168)),n=Math.max(10,Math.min(Number(limit)||60,200));return result('recent_system_errors',true,'Recent error events read',await json(`$start=(Get-Date).AddHours(-${h});Get-WinEvent -FilterHashtable @{LogName='System','Application';Level=1,2;StartTime=$start} -ErrorAction SilentlyContinue | Select-Object -First ${n} TimeCreated,LogName,ProviderName,Id,LevelDisplayName,Message`));}),
  defender_status:tool('read','Read Microsoft Defender protection and signature status',empty,async()=>result('defender_status',true,'Defender status read',await json("Get-MpComputerStatus -ErrorAction SilentlyContinue | Select-Object AntivirusEnabled,AntispywareEnabled,RealTimeProtectionEnabled,BehaviorMonitorEnabled,IoavProtectionEnabled,NISEnabled,AntivirusSignatureLastUpdated,QuickScanAge,FullScanAge"))),
  firewall_status:tool('read','Read Windows Firewall profile states',empty,async()=>result('firewall_status',true,'Firewall status read',await json("Get-NetFirewallProfile -ErrorAction SilentlyContinue | Select-Object Name,Enabled,DefaultInboundAction,DefaultOutboundAction"))),
  update_history:tool('read','Read recent installed Windows updates and hotfixes',{type:'object',properties:{limit:{type:'number'}},required:[]},async({limit=50})=>{const n=Math.max(5,Math.min(Number(limit)||50,150));return result('update_history',true,'Update history read',await json(`Get-HotFix -ErrorAction SilentlyContinue | Sort-Object InstalledOn -Descending | Select-Object -First ${n} HotFixID,Description,InstalledOn,InstalledBy`));}),
  problem_devices:tool('read','List Plug and Play devices reporting Windows errors',empty,async()=>result('problem_devices',true,'Problem devices checked',await json("Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue | Where-Object {$_.Status -ne 'OK'} | Select-Object -First 150 Class,FriendlyName,InstanceId,Status,Problem"))),
  device_inventory:tool('read','List installed Plug and Play devices, optionally filtered by class or name',{type:'object',properties:{filter:{type:'string'},limit:{type:'number'}},required:[]},async({filter='',limit=200})=>{const f=String(filter||'').replaceAll("'","''"),n=Math.max(20,Math.min(Number(limit)||200,500));return result('device_inventory',true,'Devices listed',await json(`Get-PnpDevice -PresentOnly -ErrorAction SilentlyContinue | Where-Object {$_.FriendlyName -like '*${f}*' -or $_.Class -like '*${f}*'} | Select-Object -First ${n} Class,FriendlyName,Status,InstanceId`));}),
  display_inventory:tool('read','Read installed display adapters and monitor information',empty,async()=>result('display_inventory',true,'Display inventory read',await json("Get-CimInstance Win32_VideoController -ErrorAction SilentlyContinue | Select-Object Name,AdapterRAM,DriverVersion,VideoModeDescription,CurrentHorizontalResolution,CurrentVerticalResolution"))),
  audio_device_inventory:tool('read','List Windows audio endpoint and media devices',empty,async()=>result('audio_device_inventory',true,'Audio devices listed',await json("Get-PnpDevice -PresentOnly -Class AudioEndpoint,Media -ErrorAction SilentlyContinue | Select-Object Class,FriendlyName,Status,InstanceId"))),
  printer_inventory:tool('read','List installed printers and default state',empty,async()=>result('printer_inventory',true,'Printers listed',await json("Get-Printer -ErrorAction SilentlyContinue | Select-Object Name,DriverName,PortName,PrinterStatus,Shared,Published"))),
  network_adapters:tool('read','List Windows network adapters and link status',empty,async()=>result('network_adapters',true,'Network adapters listed',await json("Get-NetAdapter -ErrorAction SilentlyContinue | Select-Object Name,InterfaceDescription,Status,LinkSpeed,MacAddress"))),
  wifi_status:tool('read','Read current Wi-Fi interface and connection details',empty,async()=>{const {stdout}=await execFileAsync('netsh.exe',['wlan','show','interfaces'],{windowsHide:true,timeout:15000,maxBuffer:2_000_000});return result('wifi_status',true,'Wi-Fi status read',{output:stdout.slice(0,12000)});}),
  ip_configuration:tool('read','Read active IP addresses, gateways and DNS servers',empty,async()=>result('ip_configuration',true,'IP configuration read',await json("Get-NetIPConfiguration -ErrorAction SilentlyContinue | Select-Object InterfaceAlias,InterfaceDescription,IPv4Address,IPv6Address,IPv4DefaultGateway,DNSServer"))),
  listening_ports:tool('read','List local TCP listening ports and owning process ids',{type:'object',properties:{limit:{type:'number'}},required:[]},async({limit=150})=>{const n=Math.max(20,Math.min(Number(limit)||150,400));return result('listening_ports',true,'Listening ports listed',await json(`Get-NetTCPConnection -State Listen -ErrorAction SilentlyContinue | Select-Object -First ${n} LocalAddress,LocalPort,OwningProcess`));}),
  environment_summary:tool('read','Read safe high-level Windows environment information without secrets',empty,async()=>result('environment_summary',true,'Environment summary read',await json("[pscustomobject]@{ComputerName=$env:COMPUTERNAME;UserDomain=$env:USERDOMAIN;ProcessorArchitecture=$env:PROCESSOR_ARCHITECTURE;NumberOfProcessors=$env:NUMBER_OF_PROCESSORS;Temp=$env:TEMP;SystemDrive=$env:SystemDrive;ProgramFiles=$env:ProgramFiles;OneDrive=$env:OneDrive}"))),
  windows_locale:tool('read','Read Windows culture, language list and regional settings',empty,async()=>result('windows_locale',true,'Locale read',await json("[pscustomobject]@{Culture=(Get-Culture).Name;UICulture=(Get-UICulture).Name;Languages=(Get-WinUserLanguageList).LanguageTag;HomeLocation=(Get-WinHomeLocation).GeoId}"))),
  time_zone_status:tool('read','Read the active Windows time zone',empty,async()=>result('time_zone_status',true,'Time zone read',await json("Get-TimeZone | Select-Object Id,DisplayName,StandardName,DaylightName"))),
  restore_points:tool('read','List available Windows System Restore points when System Restore is enabled',empty,async()=>result('restore_points',true,'Restore points listed',await json("Get-ComputerRestorePoint -ErrorAction SilentlyContinue | Select-Object -First 50 SequenceNumber,Description,CreationTime,RestorePointType,EventType"))),
  temp_usage:tool('read','Estimate size and file count of the current user temporary folder',empty,async()=>result('temp_usage',true,'Temporary folder usage measured',await json("$x=Get-ChildItem $env:TEMP -Force -Recurse -File -ErrorAction SilentlyContinue | Measure-Object Length -Sum;[pscustomobject]@{path=$env:TEMP;files=$x.Count;bytes=[double]$x.Sum;gigabytes=[math]::Round($x.Sum/1GB,3)}"))),
  recycle_bin_usage:tool('read','Estimate Recycle Bin item count and size for the current user',empty,async()=>result('recycle_bin_usage',true,'Recycle Bin usage measured',await json("$s=New-Object -ComObject Shell.Application;$b=$s.Namespace(10);$items=@($b.Items());$total=0;foreach($i in $items){$total+=[double]($b.GetDetailsOf($i,1) -replace '[^0-9]','')};[pscustomobject]@{items=$items.Count;approxBytes=$total}"))),
  flush_dns_cache:tool('low','Flush the Windows DNS resolver cache',empty,async()=>{await execFileAsync('ipconfig.exe',['/flushdns'],{windowsHide:true,timeout:30000});return result('flush_dns_cache',true,'DNS cache flushed');}),
  restart_explorer:tool('low','Restart Windows Explorer shell to recover a stuck desktop/taskbar',empty,async()=>{await ps("Stop-Process -Name explorer -Force -ErrorAction SilentlyContinue;Start-Process explorer.exe");return result('restart_explorer',true,'Windows Explorer restarted');}),
  start_windows_update_scan:tool('low','Ask Windows Update to start a scan using the built-in update client',empty,async()=>{open('UsoClient.exe',['StartScan']);return result('start_windows_update_scan',true,'Windows Update scan requested');}),
  verify_system_files:tool('read','Run SFC verification only. This checks protected Windows system files without repairing them',empty,async()=>{const {stdout,stderr}=await execFileAsync('sfc.exe',['/verifyonly'],{windowsHide:false,timeout:1800000,maxBuffer:12_000_000});return result('verify_system_files',true,'SFC verification completed',{stdout:stdout.slice(-20000),stderr:stderr.slice(-6000)});}),
  scan_windows_image_health:tool('read','Run DISM ScanHealth to diagnose Windows component-store corruption without repairing it',empty,async()=>{const {stdout,stderr}=await execFileAsync('dism.exe',['/Online','/Cleanup-Image','/ScanHealth'],{windowsHide:false,timeout:1800000,maxBuffer:12_000_000});return result('scan_windows_image_health',true,'DISM health scan completed',{stdout:stdout.slice(-20000),stderr:stderr.slice(-6000)});}),
  repair_windows_image:tool('sensitive','Run DISM RestoreHealth to repair the Windows component store. Requires administrator rights and may take a long time',empty,async()=>{const {stdout,stderr}=await execFileAsync('dism.exe',['/Online','/Cleanup-Image','/RestoreHealth'],{windowsHide:false,timeout:3600000,maxBuffer:16_000_000});return result('repair_windows_image',true,'DISM repair completed',{stdout:stdout.slice(-24000),stderr:stderr.slice(-8000)});}),
  repair_system_files:tool('sensitive','Run SFC /scannow to repair protected Windows system files. Requires administrator rights',empty,async()=>{const {stdout,stderr}=await execFileAsync('sfc.exe',['/scannow'],{windowsHide:false,timeout:3600000,maxBuffer:16_000_000});return result('repair_system_files',true,'SFC repair completed',{stdout:stdout.slice(-24000),stderr:stderr.slice(-8000)});}),
  create_restore_point:tool('sensitive','Create a Windows System Restore checkpoint before major changes when System Restore is enabled',{type:'object',properties:{description:{type:'string'}},required:[]},async({description='Black Clover Maria checkpoint'})=>{const d=String(description).replaceAll("'","''").slice(0,100);await ps(`Checkpoint-Computer -Description '${d}' -RestorePointType MODIFY_SETTINGS`,{timeout:120000});return result('create_restore_point',true,'Restore point requested',{description:d});}),
  cleanup_user_temp:tool('sensitive','Delete disposable files from the current user TEMP directory, skipping locked files',{type:'object',properties:{older_than_days:{type:'number'}},required:[]},async({older_than_days=2})=>{const d=Math.max(0,Math.min(Number(older_than_days)||2,365));const data=await json(`$cut=(Get-Date).AddDays(-${d});$before=Get-ChildItem $env:TEMP -Force -Recurse -File -ErrorAction SilentlyContinue | Where-Object {$_.LastWriteTime -lt $cut};$bytes=($before|Measure-Object Length -Sum).Sum;$count=@($before).Count;$before|Remove-Item -Force -ErrorAction SilentlyContinue;[pscustomobject]@{attempted=$count;bytes=[double]$bytes}`);return result('cleanup_user_temp',true,'Temporary-file cleanup completed',data);}),
  empty_recycle_bin:tool('sensitive','Permanently empty the Windows Recycle Bin',empty,async()=>{await ps('Clear-RecycleBin -Force -ErrorAction Stop',{timeout:120000});return result('empty_recycle_bin',true,'Recycle Bin emptied');}),
  open_task_manager:openSettings('task_manager','taskmgr.exe'),
  open_device_manager:tool('low','Open Windows Device Manager',empty,async()=>{open('devmgmt.msc');return result('open_device_manager',true,'Device Manager opened');}),
  open_services_manager:tool('low','Open Windows Services management console',empty,async()=>{open('services.msc');return result('open_services_manager',true,'Services opened');}),
  open_event_viewer:tool('low','Open Windows Event Viewer',empty,async()=>{open('eventvwr.msc');return result('open_event_viewer',true,'Event Viewer opened');}),
  open_disk_management:tool('low','Open Windows Disk Management',empty,async()=>{open('diskmgmt.msc');return result('open_disk_management',true,'Disk Management opened');}),
  open_power_options:tool('low','Open classic Windows Power Options',empty,async()=>{open('control.exe',['/name','Microsoft.PowerOptions']);return result('open_power_options',true,'Power Options opened');}),
  open_default_apps:openSettings('default_apps','ms-settings:defaultapps'),
  open_microphone_privacy:openSettings('microphone_privacy','ms-settings:privacy-microphone'),
  open_camera_privacy:openSettings('camera_privacy','ms-settings:privacy-webcam'),
  open_notifications_settings:openSettings('notifications_settings','ms-settings:notifications')
};
