import { execFile, spawn } from 'node:child_process';
import os from 'node:os';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);

const ps=async(script)=>{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:30000,maxBuffer:4_000_000});return stdout.trim();};
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const quote=s=>String(s).replaceAll("'","''");
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)));
const openExternal=url=>{spawn('cmd.exe',['/c','start','',url],{detached:true,windowsHide:true});};
const sendMediaKey=async key=>ps(`$w=New-Object -ComObject WScript.Shell; $w.SendKeys('${key}')`);

export const tools={
  get_system_info:{risk:'read',description:'Read Windows/system information, memory and uptime',schema:{type:'object',properties:{},required:[]},run:async()=>result('get_system_info',true,'System information read',{platform:os.platform(),release:os.release(),arch:os.arch(),hostname:os.hostname(),totalRamGB:+(os.totalmem()/1073741824).toFixed(1),freeRamGB:+(os.freemem()/1073741824).toFixed(1),uptimeMinutes:Math.round(os.uptime()/60)})},
  list_processes:{risk:'read',description:'List running processes, optionally filtered by name',schema:{type:'object',properties:{filter:{type:'string'}},required:[]},run:async({filter=''})=>{const raw=await ps("Get-Process | Sort-Object ProcessName | Select-Object -First 200 Name,Id | ConvertTo-Json -Compress");let data=JSON.parse(raw||'[]');if(!Array.isArray(data))data=[data];if(filter)data=data.filter(x=>x.Name?.toLowerCase().includes(filter.toLowerCase()));return result('list_processes',true,'Processes listed',data);}},
  find_app:{risk:'read',description:'Find installed application shortcuts by name',schema:{type:'object',properties:{name:{type:'string'}},required:['name']},run:async({name})=>{const q=quote(name);const raw=await ps(`$p=@($env:ProgramData+'\\Microsoft\\Windows\\Start Menu\\Programs',$env:APPDATA+'\\Microsoft\\Windows\\Start Menu\\Programs'); Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {$_.BaseName -like '*${q}*'} | Select-Object -First 30 BaseName,FullName | ConvertTo-Json -Compress`);const data=raw?JSON.parse(raw):[];return result('find_app',true,'Search completed',Array.isArray(data)?data:[data]);}},
  launch_app:{risk:'low',description:'Launch an installed application by Start Menu shortcut name',schema:{type:'object',properties:{name:{type:'string'}},required:['name']},run:async({name})=>{const q=quote(name);const raw=await ps(`$p=@($env:ProgramData+'\\Microsoft\\Windows\\Start Menu\\Programs',$env:APPDATA+'\\Microsoft\\Windows\\Start Menu\\Programs'); $x=Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {$_.BaseName -like '*${q}*'} | Select-Object -First 1; if($x){Start-Process $x.FullName; $x.FullName}`);if(!raw)return result('launch_app',false,'Application not found');return result('launch_app',true,'Launch requested',{shortcut:raw});}},
  open_url:{risk:'low',description:'Open an http/https URL in the default browser',schema:{type:'object',properties:{url:{type:'string'}},required:['url']},run:async({url})=>{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are allowed');openExternal(u.href);return result('open_url',true,'URL opened',{url:u.href});}},
  web_search:{risk:'low',description:'Search Google/web in the default browser',schema:{type:'object',properties:{query:{type:'string'}},required:['query']},run:async({query})=>{const url=`https://www.google.com/search?q=${encodeURIComponent(query)}`;openExternal(url);return result('web_search',true,'Web search opened',{query,url});}},
  youtube_search:{risk:'low',description:'Search YouTube in the default browser',schema:{type:'object',properties:{query:{type:'string'}},required:['query']},run:async({query})=>{const url=`https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;openExternal(url);return result('youtube_search',true,'YouTube search opened',{query,url});}},
  get_volume:{risk:'read',description:'Read current Windows master volume percentage',schema:{type:'object',properties:{},required:[]},run:async()=>{const raw=await ps(`Add-Type -TypeDefinition 'using System.Runtime.InteropServices; public class A{[DllImport("winmm.dll")] public static extern int waveOutGetVolume(System.IntPtr hwo,out uint dwVolume);}' ; [uint32]$v=0; [A]::waveOutGetVolume([IntPtr]::Zero,[ref]$v)|Out-Null; [math]::Round((($v -band 0xffff)/65535)*100)`);return result('get_volume',true,'Volume read',{percent:Number(raw)});}},
  set_volume:{risk:'low',description:'Set Windows master output volume from 0 to 100 percent',schema:{type:'object',properties:{percent:{type:'number'}},required:['percent']},run:async({percent})=>{const n=clamp(percent,0,100),v=Math.round(n/100*65535);await ps(`Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class A{[DllImport("winmm.dll")] public static extern int waveOutSetVolume(IntPtr hwo,uint dwVolume);}' ; $v=${v}; [A]::waveOutSetVolume([IntPtr]::Zero,($v -bor ($v -shl 16)))|Out-Null`);return result('set_volume',true,`Volume set to ${Math.round(n)}%`,{percent:Math.round(n)});}},
  get_brightness:{risk:'read',description:'Read built-in display brightness when Windows exposes WMI brightness control',schema:{type:'object',properties:{},required:[]},run:async()=>{const raw=await ps(`(Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightness -ErrorAction Stop | Select-Object -First 1 -ExpandProperty CurrentBrightness)`);if(raw==='')return result('get_brightness',false,'Brightness control is not available for this display');return result('get_brightness',true,'Brightness read',{percent:Number(raw)});}},
  set_brightness:{risk:'low',description:'Set built-in display brightness from 0 to 100 when supported by Windows/WMI',schema:{type:'object',properties:{percent:{type:'number'}},required:['percent']},run:async({percent})=>{const n=Math.round(clamp(percent,0,100));await ps(`$m=Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightnessMethods -ErrorAction Stop | Select-Object -First 1; Invoke-CimMethod -InputObject $m -MethodName WmiSetBrightness -Arguments @{Timeout=1;Brightness=${n}} | Out-Null`);return result('set_brightness',true,`Brightness set to ${n}%`,{percent:n});}},
  media_play_pause:{risk:'low',description:'Toggle play/pause for the active Windows media session',schema:{type:'object',properties:{},required:[]},run:async()=>{await sendMediaKey('{MEDIA_PLAY_PAUSE}');return result('media_play_pause',true,'Play/pause key sent');}},
  media_next:{risk:'low',description:'Skip to next track in the active Windows media session',schema:{type:'object',properties:{},required:[]},run:async()=>{await sendMediaKey('{MEDIA_NEXT_TRACK}');return result('media_next',true,'Next-track key sent');}},
  media_previous:{risk:'low',description:'Go to previous track in the active Windows media session',schema:{type:'object',properties:{},required:[]},run:async()=>{await sendMediaKey('{MEDIA_PREV_TRACK}');return result('media_previous',true,'Previous-track key sent');}},
  lock_pc:{risk:'low',description:'Lock the current Windows session',schema:{type:'object',properties:{},required:[]},run:async()=>{spawn('rundll32.exe',['user32.dll,LockWorkStation'],{detached:true,windowsHide:true});return result('lock_pc',true,'Lock requested');}},
  sleep_pc:{risk:'sensitive',description:'Put the PC into sleep/suspend mode',schema:{type:'object',properties:{},required:[]},run:async()=>{await ps('Add-Type -AssemblyName System.Windows.Forms; [System.Windows.Forms.Application]::SetSuspendState([System.Windows.Forms.PowerState]::Suspend,$false,$false)');return result('sleep_pc',true,'Sleep requested');}},
  check_windows_update:{risk:'low',description:'Open Windows Update settings',schema:{type:'object',properties:{},required:[]},run:async()=>{spawn('cmd.exe',['/c','start','','ms-settings:windowsupdate'],{detached:true,windowsHide:true});return result('check_windows_update',true,'Windows Update opened');}},
  list_directory:{risk:'read',description:'List files and folders in a user-specified directory',schema:{type:'object',properties:{directory:{type:'string'}},required:['directory']},run:async({directory})=>{const p=path.resolve(directory);const entries=await fs.readdir(p,{withFileTypes:true});return result('list_directory',true,'Directory listed',entries.slice(0,300).map(e=>({name:e.name,type:e.isDirectory()?'directory':'file'})));}},
  shutdown_pc:{risk:'sensitive',description:'Shut down Windows after explicit user confirmation',schema:{type:'object',properties:{},required:[]},run:async()=>{spawn('shutdown.exe',['/s','/t','0'],{detached:true,windowsHide:true});return result('shutdown_pc',true,'Shutdown requested');}},
  restart_pc:{risk:'sensitive',description:'Restart Windows after explicit user confirmation',schema:{type:'object',properties:{},required:[]},run:async()=>{spawn('shutdown.exe',['/r','/t','0'],{detached:true,windowsHide:true});return result('restart_pc',true,'Restart requested');}}
};

export function ollamaTools(){return Object.entries(tools).map(([name,t])=>({type:'function',function:{name,description:t.description,parameters:t.schema}}));}
export async function runTool(name,args={}){const t=tools[name];if(!t)throw new Error(`Unknown tool: ${name}`);return t.run(args);}
