import { execFile, spawn } from 'node:child_process';
import os from 'node:os';
import fs from 'node:fs/promises';
import path from 'node:path';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const ps=async(script)=>{const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:45000,maxBuffer:6_000_000});return stdout.trim();};
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const quote=s=>String(s).replaceAll("'","''");
const clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)));
const openExternal=url=>spawn('cmd.exe',['/c','start','',url],{detached:true,windowsHide:true});
const sendMediaKey=async key=>ps(`$w=New-Object -ComObject WScript.Shell; $w.SendKeys('${key}')`);
const empty={type:'object',properties:{},required:[]};
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const appRoots=`@($env:ProgramData+'\\Microsoft\\Windows\\Start Menu\\Programs',$env:APPDATA+'\\Microsoft\\Windows\\Start Menu\\Programs')`;
const appSearchScript=name=>`$p=${appRoots}; Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {$_.BaseName -like '*${quote(name)}*'} | Select-Object -First 30 BaseName,FullName | ConvertTo-Json -Compress`;
const parseJsonArray=raw=>{if(!raw)return[];const x=JSON.parse(raw);return Array.isArray(x)?x:[x];};
const setting=(name,uri)=>tool('low',`Open Windows ${name} settings`,empty,async()=>{openExternal(uri);return result(`open_${name}_settings`,true,`${name} settings opened`);});
const sendKeys=async keys=>ps(`$w=New-Object -ComObject WScript.Shell; Start-Sleep -Milliseconds 100; $w.SendKeys('${quote(keys)}')`);
const mouseScript=`Add-Type -TypeDefinition @'\nusing System; using System.Runtime.InteropServices; public static class BCMouse { [DllImport("user32.dll")] public static extern bool SetCursorPos(int X,int Y); [DllImport("user32.dll")] public static extern void mouse_event(uint f,uint dx,uint dy,uint data,UIntPtr extra); }\n'@;`;

export const tools={
  get_system_info:tool('read','Read Windows/system information, memory and uptime',empty,async()=>result('get_system_info',true,'System information read',{platform:os.platform(),release:os.release(),arch:os.arch(),hostname:os.hostname(),username:os.userInfo().username,totalRamGB:+(os.totalmem()/1073741824).toFixed(1),freeRamGB:+(os.freemem()/1073741824).toFixed(1),uptimeMinutes:Math.round(os.uptime()/60),home:os.homedir()})),
  get_time:tool('read','Read local date and time',empty,async()=>result('get_time',true,'Time read',{iso:new Date().toISOString(),local:new Date().toString()})),
  list_processes:tool('read','List running processes, optionally filtered by name',{type:'object',properties:{filter:{type:'string'}},required:[]},async({filter=''})=>{const raw=await ps("Get-Process | Sort-Object ProcessName | Select-Object -First 250 Name,Id,MainWindowTitle | ConvertTo-Json -Compress");let data=parseJsonArray(raw);if(filter)data=data.filter(x=>x.Name?.toLowerCase().includes(filter.toLowerCase())||x.MainWindowTitle?.toLowerCase().includes(filter.toLowerCase()));return result('list_processes',true,'Processes listed',data);}),
  find_app:tool('read','Find installed application shortcuts by name',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>result('find_app',true,'Search completed',parseJsonArray(await ps(appSearchScript(name))))),
  list_installed_apps:tool('read','List installed Start Menu applications',{type:'object',properties:{filter:{type:'string'}},required:[]},async({filter=''})=>{const raw=await ps(`$p=${appRoots}; Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {$_.BaseName -like '*${quote(filter)}*'} | Sort-Object BaseName -Unique | Select-Object -First 300 BaseName,FullName | ConvertTo-Json -Compress`);return result('list_installed_apps',true,'Installed applications listed',parseJsonArray(raw));}),
  launch_app:tool('low','Launch an installed application by Start Menu shortcut name',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{const raw=await ps(`$p=${appRoots}; $x=Get-ChildItem $p -Recurse -Filter *.lnk -ErrorAction SilentlyContinue | Where-Object {$_.BaseName -like '*${quote(name)}*'} | Select-Object -First 1; if($x){Start-Process $x.FullName; $x.FullName}`);return raw?result('launch_app',true,'Application launched',{shortcut:raw}):result('launch_app',false,'Application not found');}),
  close_app:tool('sensitive','Close a running application by process/window name',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{const raw=await ps(`$p=Get-Process -ErrorAction SilentlyContinue | Where-Object {$_.ProcessName -like '*${quote(name)}*' -or $_.MainWindowTitle -like '*${quote(name)}*'} | Select-Object -First 10; if(!$p){'NONE'} else {$p|Stop-Process -Force;($p.ProcessName -join ',')}`);return raw==='NONE'?result('close_app',false,'Running application not found'):result('close_app',true,'Application closed',{processes:raw});}),
  winget_search:tool('read','Search software through Windows Package Manager',{type:'object',properties:{query:{type:'string'}},required:['query']},async({query})=>{const {stdout}=await execFileAsync('winget.exe',['search','--query',String(query),'--accept-source-agreements'],{windowsHide:true,timeout:60000,maxBuffer:4_000_000});return result('winget_search',true,'winget search completed',{output:stdout.slice(0,12000)});}),
  install_app:tool('sensitive','Install an application with winget after confirmation',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const {stdout}=await execFileAsync('winget.exe',['install','--id',String(id),'-e','--accept-package-agreements','--accept-source-agreements'],{windowsHide:false,timeout:600000,maxBuffer:8_000_000});return result('install_app',true,'Installation completed',{output:stdout.slice(-8000)});}),
  uninstall_app:tool('sensitive','Uninstall an application with winget after confirmation',{type:'object',properties:{id:{type:'string'}},required:['id']},async({id})=>{const {stdout}=await execFileAsync('winget.exe',['uninstall','--id',String(id),'-e'],{windowsHide:false,timeout:600000,maxBuffer:8_000_000});return result('uninstall_app',true,'Uninstall completed',{output:stdout.slice(-8000)});}),
  open_url:tool('low','Open an http/https URL in the default browser',{type:'object',properties:{url:{type:'string'}},required:['url']},async({url})=>{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are allowed');openExternal(u.href);return result('open_url',true,'URL opened',{url:u.href});}),
  web_search:tool('low','Search Google/web in the default browser',{type:'object',properties:{query:{type:'string'}},required:['query']},async({query})=>{const url=`https://www.google.com/search?q=${encodeURIComponent(query)}`;openExternal(url);return result('web_search',true,'Web search opened',{query,url});}),
  youtube_search:tool('low','Search YouTube in the default browser',{type:'object',properties:{query:{type:'string'}},required:['query']},async({query})=>{const url=`https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`;openExternal(url);return result('youtube_search',true,'YouTube search opened',{query,url});}),
  google_maps_search:tool('low','Search a place in Google Maps',{type:'object',properties:{query:{type:'string'}},required:['query']},async({query})=>{const url=`https://www.google.com/maps/search/${encodeURIComponent(query)}`;openExternal(url);return result('google_maps_search',true,'Maps search opened',{query,url});}),
  get_volume:tool('read','Read current Windows master volume percentage',empty,async()=>{const raw=await ps(`Add-Type -TypeDefinition 'using System.Runtime.InteropServices; public class A{[DllImport("winmm.dll")] public static extern int waveOutGetVolume(System.IntPtr hwo,out uint dwVolume);}' ; [uint32]$v=0; [A]::waveOutGetVolume([IntPtr]::Zero,[ref]$v)|Out-Null; [math]::Round((($v -band 0xffff)/65535)*100)`);return result('get_volume',true,'Volume read',{percent:Number(raw)});}),
  set_volume:tool('low','Set Windows master output volume 0-100',{type:'object',properties:{percent:{type:'number'}},required:['percent']},async({percent})=>{const n=clamp(percent,0,100),v=Math.round(n/100*65535);await ps(`Add-Type -TypeDefinition 'using System; using System.Runtime.InteropServices; public class A{[DllImport("winmm.dll")] public static extern int waveOutSetVolume(IntPtr hwo,uint dwVolume);}' ; $v=${v}; [A]::waveOutSetVolume([IntPtr]::Zero,($v -bor ($v -shl 16)))|Out-Null`);return result('set_volume',true,`Volume set to ${Math.round(n)}%`,{percent:Math.round(n)});}),
  volume_up:tool('low','Increase Windows volume',empty,async()=>{for(let i=0;i<3;i++)await sendMediaKey('{VOLUME_UP}');return result('volume_up',true,'Volume increased');}),
  volume_down:tool('low','Decrease Windows volume',empty,async()=>{for(let i=0;i<3;i++)await sendMediaKey('{VOLUME_DOWN}');return result('volume_down',true,'Volume decreased');}),
  toggle_mute:tool('low','Toggle Windows speaker mute',empty,async()=>{await sendMediaKey('{VOLUME_MUTE}');return result('toggle_mute',true,'Mute toggled');}),
  get_brightness:tool('read','Read built-in display brightness',empty,async()=>{const raw=await ps(`Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightness -ErrorAction Stop|Select-Object -First 1 -ExpandProperty CurrentBrightness`);return result('get_brightness',raw!=='',raw===''?'Brightness unavailable':'Brightness read',raw===''?null:{percent:Number(raw)});}),
  set_brightness:tool('low','Set built-in display brightness 0-100',{type:'object',properties:{percent:{type:'number'}},required:['percent']},async({percent})=>{const n=Math.round(clamp(percent,0,100));await ps(`$m=Get-CimInstance -Namespace root/WMI -ClassName WmiMonitorBrightnessMethods -ErrorAction Stop|Select-Object -First 1;Invoke-CimMethod -InputObject $m -MethodName WmiSetBrightness -Arguments @{Timeout=1;Brightness=${n}}|Out-Null`);return result('set_brightness',true,`Brightness set to ${n}%`,{percent:n});}),
  media_play_pause:tool('low','Toggle active media play/pause',empty,async()=>{await sendMediaKey('{MEDIA_PLAY_PAUSE}');return result('media_play_pause',true,'Play/pause sent');}),
  media_next:tool('low','Next media track',empty,async()=>{await sendMediaKey('{MEDIA_NEXT_TRACK}');return result('media_next',true,'Next track sent');}),
  media_previous:tool('low','Previous media track',empty,async()=>{await sendMediaKey('{MEDIA_PREV_TRACK}');return result('media_previous',true,'Previous track sent');}),
  lock_pc:tool('low','Lock Windows session',empty,async()=>{spawn('rundll32.exe',['user32.dll,LockWorkStation'],{detached:true,windowsHide:true});return result('lock_pc',true,'Lock requested');}),
  sleep_pc:tool('sensitive','Put PC to sleep',empty,async()=>{await ps('Add-Type -AssemblyName System.Windows.Forms;[System.Windows.Forms.Application]::SetSuspendState([System.Windows.Forms.PowerState]::Suspend,$false,$false)');return result('sleep_pc',true,'Sleep requested');}),
  shutdown_pc:tool('sensitive','Shut down Windows',empty,async()=>{spawn('shutdown.exe',['/s','/t','0'],{detached:true,windowsHide:true});return result('shutdown_pc',true,'Shutdown requested');}),
  restart_pc:tool('sensitive','Restart Windows',empty,async()=>{spawn('shutdown.exe',['/r','/t','0'],{detached:true,windowsHide:true});return result('restart_pc',true,'Restart requested');}),
  sign_out:tool('sensitive','Sign out Windows account',empty,async()=>{spawn('shutdown.exe',['/l'],{detached:true,windowsHide:true});return result('sign_out',true,'Sign-out requested');}),
  check_windows_update:tool('low','Open Windows Update',empty,async()=>{openExternal('ms-settings:windowsupdate');return result('check_windows_update',true,'Windows Update opened');}),
  open_display_settings:setting('display','ms-settings:display'),open_sound_settings:setting('sound','ms-settings:sound'),open_bluetooth_settings:setting('bluetooth','ms-settings:bluetooth'),open_network_settings:setting('network','ms-settings:network'),open_apps_settings:setting('apps','ms-settings:appsfeatures'),open_storage_settings:setting('storage','ms-settings:storagesense'),open_privacy_settings:setting('privacy','ms-settings:privacy'),open_windows_security:setting('security','windowsdefender:'),
  list_directory:tool('read','List files/folders in a directory',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>result('list_directory',true,'Directory listed',(await fs.readdir(path.resolve(directory),{withFileTypes:true})).slice(0,500).map(e=>({name:e.name,type:e.isDirectory()?'directory':'file'})))),
  file_info:tool('read','Read file/folder metadata',{type:'object',properties:{target:{type:'string'}},required:['target']},async({target})=>{const p=path.resolve(target),s=await fs.stat(p);return result('file_info',true,'File information read',{path:p,size:s.size,isDirectory:s.isDirectory(),created:s.birthtime,modified:s.mtime});}),
  read_text_file:tool('read','Read UTF-8 text file up to 200 KB',{type:'object',properties:{file:{type:'string'}},required:['file']},async({file})=>{const p=path.resolve(file),s=await fs.stat(p);if(s.size>200000)throw new Error('File is larger than 200 KB');return result('read_text_file',true,'Text file read',{path:p,content:await fs.readFile(p,'utf8')});}),
  create_folder:tool('low','Create folder',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>{const p=path.resolve(directory);await fs.mkdir(p,{recursive:true});return result('create_folder',true,'Folder created',{path:p});}),
  write_text_file:tool('sensitive','Create/replace UTF-8 text file',{type:'object',properties:{file:{type:'string'},content:{type:'string'}},required:['file','content']},async({file,content})=>{const p=path.resolve(file);await fs.mkdir(path.dirname(p),{recursive:true});await fs.writeFile(p,String(content),'utf8');return result('write_text_file',true,'Text file written',{path:p});}),
  delete_path:tool('sensitive','Delete file/folder recursively',{type:'object',properties:{target:{type:'string'}},required:['target']},async({target})=>{const p=path.resolve(target);if(p===path.parse(p).root)throw new Error('Refusing filesystem root deletion');await fs.rm(p,{recursive:true,force:false});return result('delete_path',true,'Path deleted',{path:p});}),
  open_folder:tool('low','Open folder in Explorer',{type:'object',properties:{directory:{type:'string'}},required:['directory']},async({directory})=>{spawn('explorer.exe',[path.resolve(directory)],{detached:true,windowsHide:true});return result('open_folder',true,'Folder opened');}),
  open_file:tool('low','Open file in default application',{type:'object',properties:{file:{type:'string'}},required:['file']},async({file})=>{await ps(`Start-Process -FilePath '${quote(path.resolve(file))}'`);return result('open_file',true,'File opened');}),
  copy_to_clipboard:tool('low','Copy text to Windows clipboard',{type:'object',properties:{text:{type:'string'}},required:['text']},async({text})=>{await ps(`Set-Clipboard -Value '${quote(text)}'`);return result('copy_to_clipboard',true,'Text copied');}),
  read_clipboard:tool('read','Read text clipboard',empty,async()=>result('read_clipboard',true,'Clipboard read',{text:await ps('Get-Clipboard -Raw')})),
  take_screenshot:tool('sensitive','Save screenshot of all screens to PNG',{type:'object',properties:{file:{type:'string'}},required:['file']},async({file})=>{const p=path.resolve(file);await fs.mkdir(path.dirname(p),{recursive:true});await ps(`Add-Type -AssemblyName System.Windows.Forms;Add-Type -AssemblyName System.Drawing;$b=[System.Windows.Forms.SystemInformation]::VirtualScreen;$bmp=New-Object Drawing.Bitmap $b.Width,$b.Height;$g=[Drawing.Graphics]::FromImage($bmp);$g.CopyFromScreen($b.Left,$b.Top,0,0,$bmp.Size);$bmp.Save('${quote(p)}',[Drawing.Imaging.ImageFormat]::Png);$g.Dispose();$bmp.Dispose()`);return result('take_screenshot',true,'Screenshot saved',{path:p});}),
  list_windows:tool('read','List visible top-level application windows',empty,async()=>result('list_windows',true,'Windows listed',parseJsonArray(await ps(`Get-Process|Where-Object {$_.MainWindowHandle -ne 0}|Select-Object ProcessName,Id,MainWindowTitle|ConvertTo-Json -Compress`)))),
  focus_window:tool('low','Focus a visible window by title or process name',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{const ok=await ps(`$w=New-Object -ComObject WScript.Shell;$p=Get-Process|Where-Object {$_.MainWindowTitle -like '*${quote(name)}*' -or $_.ProcessName -like '*${quote(name)}*'}|Select-Object -First 1;if($p){[bool]$w.AppActivate($p.Id)}else{$false}`);return result('focus_window',ok.toLowerCase()==='true',ok.toLowerCase()==='true'?'Window focused':'Window not found');}),
  type_text:tool('sensitive','Type literal text into the currently focused application after confirmation',{type:'object',properties:{text:{type:'string'}},required:['text']},async({text})=>{await ps(`Set-Clipboard -Value '${quote(text)}';$w=New-Object -ComObject WScript.Shell;$w.SendKeys('^v')`);return result('type_text',true,'Text typed');}),
  press_key:tool('low','Press a supported keyboard key or shortcut. Examples ENTER, ESC, TAB, CTRL+C, CTRL+V, ALT+TAB',{type:'object',properties:{key:{type:'string'}},required:['key']},async({key})=>{const map={'ENTER':'{ENTER}','ESC':'{ESC}','TAB':'{TAB}','SPACE':' ','BACKSPACE':'{BACKSPACE}','DELETE':'{DELETE}','UP':'{UP}','DOWN':'{DOWN}','LEFT':'{LEFT}','RIGHT':'{RIGHT}','CTRL+C':'^c','CTRL+V':'^v','CTRL+X':'^x','CTRL+A':'^a','CTRL+S':'^s','CTRL+Z':'^z','ALT+TAB':'%{TAB}','WIN+D':'#d'};const k=map[String(key).toUpperCase()];if(!k)throw new Error('Unsupported key/shortcut');await sendKeys(k);return result('press_key',true,'Key sent',{key});}),
  move_mouse:tool('low','Move mouse cursor to absolute screen coordinates',{type:'object',properties:{x:{type:'number'},y:{type:'number'}},required:['x','y']},async({x,y})=>{const X=Math.round(x),Y=Math.round(y);await ps(`${mouseScript}[BCMouse]::SetCursorPos(${X},${Y})|Out-Null`);return result('move_mouse',true,'Mouse moved',{x:X,y:Y});}),
  mouse_click:tool('sensitive','Click mouse at current cursor position after confirmation',{type:'object',properties:{button:{type:'string',enum:['left','right','middle']},double:{type:'boolean'}},required:[]},async({button='left',double=false})=>{const codes={left:[2,4],right:[8,16],middle:[32,64]},[down,up]=codes[button]||codes.left,count=double?2:1;await ps(`${mouseScript}for($i=0;$i -lt ${count};$i++){[BCMouse]::mouse_event(${down},0,0,0,[UIntPtr]::Zero);[BCMouse]::mouse_event(${up},0,0,0,[UIntPtr]::Zero);Start-Sleep -Milliseconds 90}`);return result('mouse_click',true,'Mouse clicked',{button,double});}),
  mouse_scroll:tool('low','Scroll mouse wheel; positive is up and negative is down',{type:'object',properties:{amount:{type:'number'}},required:['amount']},async({amount})=>{const n=Math.round(clamp(amount,-20,20))*120;await ps(`${mouseScript}[BCMouse]::mouse_event(2048,0,0,[uint32](${n}),[UIntPtr]::Zero)`);return result('mouse_scroll',true,'Mouse scrolled',{amount});})
};
export function ollamaTools(){return Object.entries(tools).map(([name,t])=>({type:'function',function:{name,description:t.description,parameters:t.schema}}));}
export async function runTool(name,args={}){const t=tools[name];if(!t)throw new Error(`Unknown tool: ${name}`);return t.run(args);}
