import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
async function capture(){const file=path.join(os.tmpdir(),`black-clover-screen-${crypto.randomUUID()}.png`),q=file.replaceAll("'","''");const script=`Add-Type -AssemblyName System.Windows.Forms; Add-Type -AssemblyName System.Drawing; $r=[System.Windows.Forms.SystemInformation]::VirtualScreen; $bmp=New-Object System.Drawing.Bitmap($r.Width,$r.Height); $g=[System.Drawing.Graphics]::FromImage($bmp); try{$g.CopyFromScreen($r.Left,$r.Top,0,0,$bmp.Size);$bmp.Save('${q}',[System.Drawing.Imaging.ImageFormat]::Png)} finally{$g.Dispose();$bmp.Dispose()}; [pscustomobject]@{left=$r.Left;top=$r.Top;width=$r.Width;height=$r.Height}|ConvertTo-Json -Compress`;const {stdout}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{windowsHide:true,timeout:30000,maxBuffer:1_000_000});return {file,screen:JSON.parse(stdout.trim())};}
async function analyze(prompt){const shot=await capture();try{const image=(await fs.readFile(shot.file)).toString('base64'),model=process.env.BLACK_CLOVER_VISION_MODEL||'qwen3-vl:4b',controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000);try{const r=await fetch(`${(process.env.OLLAMA_URL||'http://127.0.0.1:11434').replace(/\/$/,'')}/api/chat`,{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({model,stream:false,keep_alive:'30s',messages:[{role:'system',content:'You are the private local vision module for a Windows desktop agent. Inspect only what is visible in the supplied screenshot. Be precise about text, controls, approximate positions and uncertainty. Never invent hidden UI.'},{role:'user',content:prompt,images:[image]}],options:{temperature:.15,num_ctx:4096}})});if(!r.ok)throw new Error(`Vision model HTTP ${r.status}`);const data=await r.json();return {model,screen:shot.screen,analysis:String(data?.message?.content||'').trim()};}finally{clearTimeout(timer);}}finally{await fs.rm(shot.file,{force:true}).catch(()=>{});}}
export const visionTools={
  vision_inspect_screen:tool('read','Privately capture the current Windows desktop and inspect it with the local Qwen vision model. Use when UI Automation cannot identify what is visible or spatial layout matters',{type:'object',properties:{question:{type:'string'}},required:[]},async({question='Describe the visible Windows desktop, active app, important text, dialogs, buttons and approximate positions. Mention anything blocking the requested task.'})=>{try{return result('vision_inspect_screen',true,'Screen inspected locally',await analyze(String(question)));}catch(e){return result('vision_inspect_screen',false,`Local vision unavailable: ${e.message}`,{hint:'Install qwen3-vl:4b from Maria Setup Center'});}})
};
