import { execFile,spawn } from 'node:child_process';
import { promisify } from 'node:util';
const execFileAsync=promisify(execFile);
const result=(name,success,message,data=null)=>({tool_name:name,success,message,data});
const tool=(risk,description,schema,run)=>({risk,description,schema,run});
const empty={type:'object',properties:{},required:[]};
const q=s=>String(s??'').replaceAll("'","''");
async function ps(script,{timeout=60000,maxBuffer=8_000_000}={}){const {stdout,stderr}=await execFileAsync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{windowsHide:true,timeout,maxBuffer});return {stdout:stdout.trim(),stderr:stderr.trim()};}
const json=async script=>{const {stdout}=await ps(`${script}|ConvertTo-Json -Depth 6 -Compress`);if(!stdout)return null;return JSON.parse(stdout);};
const open=(name,cmd,args=[])=>tool('low',`Open ${name}`,empty,async()=>{spawn(cmd,args,{detached:true,windowsHide:false});return result(`open_${name.toLowerCase().replace(/\W+/g,'_')}`,true,`${name} opened`);});
export const windowsAdvancedTools={
  get_battery_status:tool('read','Read laptop battery charge, charging state and estimated runtime when available',empty,async()=>result('get_battery_status',true,'Battery status read',await json("Get-CimInstance Win32_Battery -ErrorAction SilentlyContinue|Select-Object Name,EstimatedChargeRemaining,BatteryStatus,EstimatedRunTime,Status"))),
  get_cpu_details:tool('read','Read CPU model, cores, logical processors and current load',empty,async()=>result('get_cpu_details',true,'CPU details read',await json("Get-CimInstance Win32_Processor|Select-Object Name,NumberOfCores,NumberOfLogicalProcessors,LoadPercentage,MaxClockSpeed"))),
  get_gpu_details:tool('read','Read installed display adapters and driver versions',empty,async()=>result('get_gpu_details',true,'GPU details read',await json("Get-CimInstance Win32_VideoController|Select-Object Name,AdapterRAM,DriverVersion,VideoProcessor,CurrentHorizontalResolution,CurrentVerticalResolution"))),
  get_memory_details:tool('read','Read physical memory totals and module information',empty,async()=>result('get_memory_details',true,'Memory details read',{os:await json("Get-CimInstance Win32_OperatingSystem|Select-Object TotalVisibleMemorySize,FreePhysicalMemory,TotalVirtualMemorySize,FreeVirtualMemory"),modules:await json("Get-CimInstance Win32_PhysicalMemory|Select-Object Manufacturer,Capacity,Speed,PartNumber")})),
  list_fixed_disks:tool('read','List local disks, free space and filesystem',empty,async()=>result('list_fixed_disks',true,'Disks listed',await json("Get-CimInstance Win32_LogicalDisk -Filter 'DriveType=3'|Select-Object DeviceID,VolumeName,FileSystem,Size,FreeSpace"))),
  get_disk_health:tool('read','Read physical disk health and operational status through Windows Storage cmdlets',empty,async()=>{let data=null;try{data=await json("Get-PhysicalDisk|Select-Object FriendlyName,MediaType,Size,HealthStatus,OperationalStatus,Usage");}catch{}return result('get_disk_health',true,'Disk health checked',data);}),
  list_network_adapters:tool('read','List Windows network adapters and link state',empty,async()=>result('list_network_adapters',true,'Network adapters listed',await json("Get-NetAdapter -ErrorAction SilentlyContinue|Select-Object Name,InterfaceDescription,Status,LinkSpeed,MacAddress,MediaType"))),
  get_network_configuration:tool('read','Read active IP addresses, gateways and DNS configuration',empty,async()=>result('get_network_configuration',true,'Network configuration read',await json("Get-NetIPConfiguration -ErrorAction SilentlyContinue|Select-Object InterfaceAlias,IPv4Address,IPv6Address,IPv4DefaultGateway,DNSServer"))),
  list_wifi_profiles:tool('read','List saved Windows Wi-Fi profile names without exposing passwords',empty,async()=>{const {stdout}=await execFileAsync('netsh.exe',['wlan','show','profiles'],{windowsHide:true,timeout:20000});return result('list_wifi_profiles',true,'Wi-Fi profiles listed',{output:stdout.slice(0,12000)});}),
  flush_dns_cache:tool('low','Flush the Windows DNS resolver cache',empty,async()=>{const {stdout}=await execFileAsync('ipconfig.exe',['/flushdns'],{windowsHide:true,timeout:30000});return result('flush_dns_cache',true,'DNS cache flushed',{output:stdout.trim()});}),
  renew_network_lease:tool('sensitive','Release and renew Windows DHCP leases; temporarily interrupts network connectivity',empty,async()=>{await execFileAsync('ipconfig.exe',['/release'],{windowsHide:true,timeout:60000}).catch(()=>{});const {stdout}=await execFileAsync('ipconfig.exe',['/renew'],{windowsHide:true,timeout:120000});return result('renew_network_lease',true,'Network lease renewed',{output:stdout.slice(-12000)});}),
  get_firewall_status:tool('read','Read Windows Firewall profile states',empty,async()=>result('get_firewall_status',true,'Firewall status read',await json("Get-NetFirewallProfile|Select-Object Name,Enabled,DefaultInboundAction,DefaultOutboundAction"))),
  get_defender_status:tool('read','Read Microsoft Defender protection status without changing security settings',empty,async()=>{let data=null;try{data=await json("Get-MpComputerStatus|Select-Object AntivirusEnabled,AntispywareEnabled,RealTimeProtectionEnabled,IoavProtectionEnabled,NISEnabled,AntivirusSignatureLastUpdated,QuickScanAge,FullScanAge");}catch{}return result('get_defender_status',true,'Defender status read',data);}),
  run_defender_quick_scan:tool('sensitive','Start a Microsoft Defender quick scan using the standard Windows cmdlet',empty,async()=>{await ps('Start-MpScan -ScanType QuickScan',{timeout:900000});return result('run_defender_quick_scan',true,'Defender quick scan completed or was handed off to Defender');}),
  list_services:tool('read','List Windows services, optionally filtered by name/display name',{type:'object',properties:{filter:{type:'string'}},required:[]},async({filter=''})=>{const f=q(filter);return result('list_services',true,'Services listed',await json(`Get-Service|Where-Object {$_.Name -like '*${f}*' -or $_.DisplayName -like '*${f}*'}|Select-Object -First 250 Name,DisplayName,Status,StartType`));}),
  start_service:tool('sensitive','Start a named Windows service',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{await ps(`Start-Service -Name '${q(name)}' -ErrorAction Stop`);return result('start_service',true,'Service started',{name});}),
  stop_service:tool('sensitive','Stop a named Windows service',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{await ps(`Stop-Service -Name '${q(name)}' -ErrorAction Stop`);return result('stop_service',true,'Service stopped',{name});}),
  restart_service:tool('sensitive','Restart a named Windows service',{type:'object',properties:{name:{type:'string'}},required:['name']},async({name})=>{await ps(`Restart-Service -Name '${q(name)}' -ErrorAction Stop`);return result('restart_service',true,'Service restarted',{name});}),
  list_startup_commands:tool('read','List applications configured to start with Windows',empty,async()=>result('list_startup_commands',true,'Startup entries listed',await json("Get-CimInstance Win32_StartupCommand|Select-Object Name,Command,Location,User"))),
  list_scheduled_tasks:tool('read','List enabled Windows scheduled tasks with current state',empty,async()=>result('list_scheduled_tasks',true,'Scheduled tasks listed',await json("Get-ScheduledTask|Where-Object {$_.State -ne 'Disabled'}|Select-Object -First 300 TaskName,TaskPath,State"))),
  recent_system_errors:tool('read','Read recent Windows System/Application error events for troubleshooting',{type:'object',properties:{hours:{type:'number'},limit:{type:'number'}},required:[]},async({hours=24,limit=80})=>{const h=Math.max(1,Math.min(Number(hours)||24,168)),n=Math.max(1,Math.min(Number(limit)||80,300));const data=await json(`$since=(Get-Date).AddHours(-${h});Get-WinEvent -FilterHashtable @{LogName=@('System','Application');Level=2;StartTime=$since} -ErrorAction SilentlyContinue|Select-Object -First ${n} TimeCreated,LogName,ProviderName,Id,LevelDisplayName,Message`);return result('recent_system_errors',true,'Recent Windows errors collected',data);}),
  recent_system_warnings:tool('read','Read recent Windows warning events for diagnostics',{type:'object',properties:{hours:{type:'number'},limit:{type:'number'}},required:[]},async({hours=24,limit=80})=>{const h=Math.max(1,Math.min(Number(hours)||24,168)),n=Math.max(1,Math.min(Number(limit)||80,300));const data=await json(`$since=(Get-Date).AddHours(-${h});Get-WinEvent -FilterHashtable @{LogName=@('System','Application');Level=3;StartTime=$since} -ErrorAction SilentlyContinue|Select-Object -First ${n} TimeCreated,LogName,ProviderName,Id,Message`);return result('recent_system_warnings',true,'Recent warnings collected',data);}),
  get_power_plan:tool('read','Read active Windows power plan',empty,async()=>{const {stdout}=await execFileAsync('powercfg.exe',['/getactivescheme'],{windowsHide:true,timeout:15000});return result('get_power_plan',true,'Active power plan read',{output:stdout.trim()});}),
  set_power_mode_balanced:tool('sensitive','Switch Windows to the built-in Balanced power scheme',empty,async()=>{await execFileAsync('powercfg.exe',['/setactive','381b4222-f694-41f0-9685-ff5bb260df2e'],{windowsHide:true,timeout:15000});return result('set_power_mode_balanced',true,'Balanced power plan activated');}),
  set_power_mode_high_performance:tool('sensitive','Switch Windows to the built-in High performance power scheme when available',empty,async()=>{await execFileAsync('powercfg.exe',['/setactive','8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'],{windowsHide:true,timeout:15000});return result('set_power_mode_high_performance',true,'High performance power plan activated');}),
  hibernate_pc:tool('sensitive','Hibernate Windows immediately when hibernation is available',empty,async()=>{spawn('shutdown.exe',['/h'],{detached:true,windowsHide:true});return result('hibernate_pc',true,'Hibernate requested');}),
  turn_off_display:tool('low','Turn off displays without sleeping the computer',empty,async()=>{await ps("Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class M{[DllImport(\"user32.dll\")]public static extern IntPtr SendMessage(IntPtr h,int m,IntPtr w,IntPtr l);}' ;[M]::SendMessage([IntPtr]0xffff,0x112,[IntPtr]0xF170,[IntPtr]2)|Out-Null");return result('turn_off_display',true,'Display power-off requested');}),
  minimize_foreground_window:tool('low','Minimize the currently focused Windows application window',empty,async()=>{await ps("Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class W{[DllImport(\"user32.dll\")]public static extern IntPtr GetForegroundWindow();[DllImport(\"user32.dll\")]public static extern bool ShowWindow(IntPtr h,int n);}' ;$h=[W]::GetForegroundWindow();if($h -ne [IntPtr]::Zero){[W]::ShowWindow($h,6)|Out-Null}");return result('minimize_foreground_window',true,'Foreground window minimized');}),
  maximize_foreground_window:tool('low','Maximize the currently focused Windows application window',empty,async()=>{await ps("Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class W{[DllImport(\"user32.dll\")]public static extern IntPtr GetForegroundWindow();[DllImport(\"user32.dll\")]public static extern bool ShowWindow(IntPtr h,int n);}' ;$h=[W]::GetForegroundWindow();if($h -ne [IntPtr]::Zero){[W]::ShowWindow($h,3)|Out-Null}");return result('maximize_foreground_window',true,'Foreground window maximized');}),
  restore_foreground_window:tool('low','Restore the currently focused Windows application window',empty,async()=>{await ps("Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public class W{[DllImport(\"user32.dll\")]public static extern IntPtr GetForegroundWindow();[DllImport(\"user32.dll\")]public static extern bool ShowWindow(IntPtr h,int n);}' ;$h=[W]::GetForegroundWindow();if($h -ne [IntPtr]::Zero){[W]::ShowWindow($h,9)|Out-Null}");return result('restore_foreground_window',true,'Foreground window restored');}),
  show_desktop:tool('low','Toggle Windows Show Desktop using the native Win+D shortcut',empty,async()=>{await ps("Add-Type -TypeDefinition 'using System;using System.Runtime.InteropServices;public static class K{[DllImport(\"user32.dll\")]public static extern void keybd_event(byte vk,byte scan,uint flags,UIntPtr extra);}' ;[K]::keybd_event(0x5B,0,0,[UIntPtr]::Zero);[K]::keybd_event(0x44,0,0,[UIntPtr]::Zero);[K]::keybd_event(0x44,0,2,[UIntPtr]::Zero);[K]::keybd_event(0x5B,0,2,[UIntPtr]::Zero)");return result('show_desktop',true,'Show Desktop requested');}),
  open_task_manager:open('Task Manager','taskmgr.exe'),
  open_device_manager:open('Device Manager','devmgmt.msc'),
  open_event_viewer:open('Event Viewer','eventvwr.msc'),
  open_services_console:open('Services Console','services.msc'),
  open_system_information:open('System Information','msinfo32.exe'),
  open_disk_management:open('Disk Management','diskmgmt.msc'),
  open_resource_monitor:open('Resource Monitor','resmon.exe'),
  run_sfc_scan:tool('sensitive','Run Windows System File Checker scan (sfc /scannow) using the official repair utility',empty,async()=>{const {stdout}=await execFileAsync('sfc.exe',['/scannow'],{windowsHide:false,timeout:3600000,maxBuffer:20_000_000});return result('run_sfc_scan',true,'SFC scan completed',{output:stdout.slice(-16000)});}),
  run_dism_health_scan:tool('sensitive','Run DISM ScanHealth on the Windows component store without applying repairs',empty,async()=>{const {stdout}=await execFileAsync('dism.exe',['/Online','/Cleanup-Image','/ScanHealth'],{windowsHide:false,timeout:3600000,maxBuffer:20_000_000});return result('run_dism_health_scan',true,'DISM health scan completed',{output:stdout.slice(-16000)});}),
  run_dism_restore_health:tool('sensitive','Run DISM RestoreHealth using standard Windows repair mechanisms',empty,async()=>{const {stdout}=await execFileAsync('dism.exe',['/Online','/Cleanup-Image','/RestoreHealth'],{windowsHide:false,timeout:3600000,maxBuffer:20_000_000});return result('run_dism_restore_health',true,'DISM repair completed',{output:stdout.slice(-16000)});}),
  clean_user_temp_files:tool('sensitive','Delete only the current user TEMP directory contents; does not touch arbitrary folders',{type:'object',properties:{older_than_hours:{type:'number'}},required:[]},async({older_than_hours=24})=>{const h=Math.max(1,Math.min(Number(older_than_hours)||24,720));const data=await json(`$cut=(Get-Date).AddHours(-${h});$items=Get-ChildItem $env:TEMP -Force -ErrorAction SilentlyContinue|Where-Object {$_.LastWriteTime -lt $cut};$count=@($items).Count;$bytes=($items|Where-Object {!$_.PSIsContainer}|Measure-Object Length -Sum).Sum;$items|Remove-Item -Recurse -Force -ErrorAction SilentlyContinue;[pscustomobject]@{count=$count;bytes=[double]($bytes??0)}`);return result('clean_user_temp_files',true,'Old user temporary files cleanup attempted',data);}),
  empty_recycle_bin:tool('sensitive','Empty Windows Recycle Bin for local drives',empty,async()=>{await ps('Clear-RecycleBin -Force -ErrorAction Stop',{timeout:180000});return result('empty_recycle_bin',true,'Recycle Bin emptied');}),
  list_optional_features:tool('read','List Windows optional features and their enabled state',empty,async()=>result('list_optional_features',true,'Optional features listed',await json("Get-WindowsOptionalFeature -Online -ErrorAction SilentlyContinue|Select-Object FeatureName,State")))
};
