const { contextBridge,ipcRenderer }=require('electron');
contextBridge.exposeInMainWorld('blackClover',{
  chat:(text,options={})=>ipcRenderer.invoke('agent:chat',{text,options}),
  modelCatalog:()=>ipcRenderer.invoke('brain:catalog'),
  confirm:(id,approved)=>ipcRenderer.invoke('agent:confirm',{id,approved}),
  getStatus:()=>ipcRenderer.invoke('agent:status'),
  runtimeRuns:(options={})=>ipcRenderer.invoke('agent:runtime-runs',options),
  runtimeErrorReport:(options={})=>ipcRenderer.invoke('agent:runtime-error-report',options),
  toggle:()=>ipcRenderer.invoke('assistant:toggle'),
  showChat:()=>ipcRenderer.invoke('assistant:show-chat'),
  hideChat:()=>ipcRenderer.invoke('assistant:hide-chat'),
  showAvatar:()=>ipcRenderer.invoke('assistant:show-avatar'),
  hideAvatar:()=>ipcRenderer.invoke('assistant:hide-avatar'),
  showProjects:()=>ipcRenderer.invoke('assistant:show-projects'),
  hideProjects:()=>ipcRenderer.invoke('assistant:hide-projects'),
  showPins:()=>ipcRenderer.invoke('assistant:show-pins'),
  hidePins:()=>ipcRenderer.invoke('assistant:hide-pins'),
  showReminders:()=>ipcRenderer.invoke('assistant:show-reminders'),
  hideReminders:()=>ipcRenderer.invoke('assistant:hide-reminders'),
  toggleTop:()=>ipcRenderer.invoke('assistant:toggle-top'),
  windowState:()=>ipcRenderer.invoke('assistant:window-state'),
  minimizeChat:()=>ipcRenderer.invoke('assistant:minimize-chat'),
  minimizeSurface:surface=>ipcRenderer.invoke('assistant:minimize-surface',surface),
  openSettings:()=>ipcRenderer.invoke('assistant:open-settings'),
  prompt:text=>ipcRenderer.invoke('assistant:prompt',text),
  listProjects:()=>ipcRenderer.invoke('projects:list'),
  projectCatalog:()=>ipcRenderer.invoke('projects:catalog'),
  createProject:payload=>ipcRenderer.invoke('projects:create',payload),
  updateProject:(id,patch)=>ipcRenderer.invoke('projects:update',{id,patch}),
  removeProject:id=>ipcRenderer.invoke('projects:remove',id),
  projectChat:payload=>ipcRenderer.invoke('projects:chat',payload),
  openProjectVsCode:id=>ipcRenderer.invoke('projects:open-vscode',id),
  openProjectFolder:id=>ipcRenderer.invoke('projects:open-folder',id),
  projectGitStatus:id=>ipcRenderer.invoke('projects:git-status',id),
  connectProjectGithub:id=>ipcRenderer.invoke('projects:connect-github',id),
  publishProjectGithub:(id,message)=>ipcRenderer.invoke('projects:publish-github',{id,message}),
  openWebService:service=>ipcRenderer.invoke('browser:open-service',service),
  listPins:()=>ipcRenderer.invoke('pins:list'),
  createPin:payload=>ipcRenderer.invoke('pins:create',payload),
  updatePin:payload=>ipcRenderer.invoke('pins:update',payload),
  removePin:id=>ipcRenderer.invoke('pins:remove',id),
  listReminders:()=>ipcRenderer.invoke('reminders:list'),
  createReminder:payload=>ipcRenderer.invoke('reminders:create',payload),
  cancelReminder:id=>ipcRenderer.invoke('reminders:cancel',id),
  diagnostics:()=>ipcRenderer.invoke('system:diagnostics'),
  installDependency:id=>ipcRenderer.invoke('system:install-dependency',id),
  provisionAll:()=>ipcRenderer.invoke('system:install-all-dependencies'),
  restartAsAdmin:()=>ipcRenderer.invoke('system:restart-admin'),
  getStartup:()=>ipcRenderer.invoke('system:get-startup'),
  setStartup:enabled=>ipcRenderer.invoke('system:set-startup',Boolean(enabled)),
  speechStatus:()=>ipcRenderer.invoke('speech:status'),
  transcribeAudio:(bytes,language='fa')=>ipcRenderer.invoke('speech:transcribe',{bytes,language}),
  synthesizeSpeech:(text,options={})=>ipcRenderer.invoke('speech:synthesize',{text,...options}),
  onEvent:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('agent:event',h);return()=>ipcRenderer.removeListener('agent:event',h);},
  onFocusInput:fn=>{const h=()=>fn();ipcRenderer.on('assistant:focus-input',h);return()=>ipcRenderer.removeListener('assistant:focus-input',h);},
  onAssistantResponse:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:response',h);return()=>ipcRenderer.removeListener('assistant:response',h);},
  onOpenSettings:fn=>{const h=()=>fn();ipcRenderer.on('assistant:open-settings',h);return()=>ipcRenderer.removeListener('assistant:open-settings',h);},
  onPrefillPrompt:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:prefill-prompt',h);return()=>ipcRenderer.removeListener('assistant:prefill-prompt',h);}
});
