const { contextBridge,ipcRenderer }=require('electron');
contextBridge.exposeInMainWorld('blackClover',{
  chat:(text,options={})=>ipcRenderer.invoke('agent:chat',{text,options}),
  replayMessage:payload=>ipcRenderer.invoke('agent:replay',payload),
  cancelChat:(conversationId='')=>ipcRenderer.invoke('agent:cancel',conversationId),
  pickChatFiles:()=>ipcRenderer.invoke('chats:pick-files'),
  listChats:(filter={})=>ipcRenderer.invoke('chats:list',filter),
  getChat:id=>ipcRenderer.invoke('chats:get',id),
  createChat:(payload={})=>ipcRenderer.invoke('chats:create',payload),
  updateChat:(id,patch)=>ipcRenderer.invoke('chats:update',{id,patch}),
  removeChat:id=>ipcRenderer.invoke('chats:remove',id),
  appendChatMessage:(conversationId,message)=>ipcRenderer.invoke('chats:message-append',{conversationId,message}),
  updateChatMessage:(conversationId,messageId,patch)=>ipcRenderer.invoke('chats:message-update',{conversationId,messageId,patch}),
  removeChatMessage:(conversationId,messageId)=>ipcRenderer.invoke('chats:message-remove',{conversationId,messageId}),
  branchChat:(conversationId,messageId)=>ipcRenderer.invoke('chats:branch',{conversationId,messageId}),
  listChatFolders:()=>ipcRenderer.invoke('chats:folders'),
  createChatFolder:name=>ipcRenderer.invoke('chats:folder-create',name),
  renameChatFolder:(id,name)=>ipcRenderer.invoke('chats:folder-rename',{id,name}),
  updateChatFolder:(id,patch)=>ipcRenderer.invoke('chats:folder-update',{id,patch}),
  removeChatFolder:id=>ipcRenderer.invoke('chats:folder-remove',id),
  copyChat:id=>ipcRenderer.invoke('chats:copy',id),
  exportChat:id=>ipcRenderer.invoke('chats:export',id),
  modelCatalog:()=>ipcRenderer.invoke('brain:catalog'),
  brainSettings:()=>ipcRenderer.invoke('brain:settings'),
  saveBrainProvider:payload=>ipcRenderer.invoke('brain:save-provider',payload),
  removeBrainProvider:provider=>ipcRenderer.invoke('brain:remove-provider',provider),
  testBrainProvider:provider=>ipcRenderer.invoke('brain:test-provider',provider),
  connectGithubBrain:()=>ipcRenderer.invoke('brain:github-login'),
  chatgptStatus:()=>ipcRenderer.invoke('chatgpt:status'),
  signInChatGPT:(options={})=>ipcRenderer.invoke('chatgpt:sign-in',options),
  selectChatGPTProfile:profileId=>ipcRenderer.invoke('chatgpt:select-profile',profileId),
  cancelChatGPTSignIn:()=>ipcRenderer.invoke('chatgpt:cancel-sign-in'),
  disconnectChatGPT:()=>ipcRenderer.invoke('chatgpt:disconnect'),
  openChatGPTUsage:()=>ipcRenderer.invoke('chatgpt:usage'),
  refreshChatGPTModels:()=>ipcRenderer.invoke('chatgpt:refresh-models'),
  testChatGPTConnection:()=>ipcRenderer.invoke('chatgpt:test-response'),
  confirm:(id,approved)=>ipcRenderer.invoke('agent:confirm',{id,approved}),
  getStatus:()=>ipcRenderer.invoke('agent:status'),
  openExternal:url=>ipcRenderer.invoke('assistant:open-external',url),
  toggle:()=>ipcRenderer.invoke('assistant:toggle'),
  showChat:()=>ipcRenderer.invoke('assistant:show-chat'),
  hideChat:()=>ipcRenderer.invoke('assistant:hide-chat'),
  showAvatar:()=>ipcRenderer.invoke('assistant:show-avatar'),
  hideAvatar:()=>ipcRenderer.invoke('assistant:hide-avatar'),
  showProjects:()=>ipcRenderer.invoke('assistant:show-projects'),
  hideProjects:()=>ipcRenderer.invoke('assistant:hide-projects'),
  showPins:()=>ipcRenderer.invoke('assistant:show-pins'),
  hidePins:()=>ipcRenderer.invoke('assistant:hide-pins'),
  showReminders:()=>ipcRenderer.invoke('assistant:show-reminders'),
  hideReminders:()=>ipcRenderer.invoke('assistant:hide-reminders'),
  showMotions:()=>ipcRenderer.invoke('assistant:show-motions'),
  hideMotions:()=>ipcRenderer.invoke('assistant:hide-motions'),
  showWardrobe:()=>ipcRenderer.invoke('assistant:show-wardrobe'),
  hideWardrobe:()=>ipcRenderer.invoke('assistant:hide-wardrobe'),
  toggleTop:()=>ipcRenderer.invoke('assistant:toggle-top'),
  windowState:()=>ipcRenderer.invoke('assistant:window-state'),
  setUiState:(mode,detail='')=>ipcRenderer.invoke('assistant:set-ui-state',{mode,detail}),
  minimizeChat:()=>ipcRenderer.invoke('assistant:minimize-chat'),
  minimizeSurface:surface=>ipcRenderer.invoke('assistant:minimize-surface',surface),
  openSettings:(section='general')=>ipcRenderer.invoke('assistant:open-settings',section),
  prompt:text=>ipcRenderer.invoke('assistant:prompt',text),
  listLocalAssets:()=>ipcRenderer.invoke('assets:list-local'),
  readLocalAsset:name=>ipcRenderer.invoke('assets:read-local',name),
  openLocalAssetFolder:()=>ipcRenderer.invoke('assets:open-folder'),
  applyLocalAvatar:name=>ipcRenderer.invoke('assets:apply-avatar',name),
  applyBuiltInAvatar:payload=>ipcRenderer.invoke('avatar:apply-built-in',payload),
  avatarLockState:()=>ipcRenderer.invoke('avatar:lock-state'),
  setAvatarLock:payload=>ipcRenderer.invoke('avatar:set-lock',payload),
  importLocalMotion:name=>ipcRenderer.invoke('assets:import-motion',name),
  playAvatarMotion:id=>ipcRenderer.invoke('avatar:play-motion',id),
  listProjects:()=>ipcRenderer.invoke('projects:list'),
  projectCatalog:()=>ipcRenderer.invoke('projects:catalog'),
  createProject:payload=>ipcRenderer.invoke('projects:create',payload),
  updateProject:(id,patch)=>ipcRenderer.invoke('projects:update',{id,patch}),
  removeProject:id=>ipcRenderer.invoke('projects:remove',id),
  projectChat:payload=>ipcRenderer.invoke('projects:chat',payload),
  openProjectVsCode:id=>ipcRenderer.invoke('projects:open-vscode',id),
  openProjectFolder:id=>ipcRenderer.invoke('projects:open-folder',id),
  projectGitStatus:id=>ipcRenderer.invoke('projects:git-status',id),
  connectProjectGithub:id=>ipcRenderer.invoke('projects:connect-github',id),
  publishProjectGithub:(id,message)=>ipcRenderer.invoke('projects:publish-github',{id,message}),
  openWebService:service=>ipcRenderer.invoke('browser:open-service',service),
  listPins:()=>ipcRenderer.invoke('pins:list'),
  createPin:payload=>ipcRenderer.invoke('pins:create',payload),
  updatePin:payload=>ipcRenderer.invoke('pins:update',payload),
  removePin:id=>ipcRenderer.invoke('pins:remove',id),
  listReminders:()=>ipcRenderer.invoke('reminders:list'),
  createReminder:payload=>ipcRenderer.invoke('reminders:create',payload),
  cancelReminder:id=>ipcRenderer.invoke('reminders:cancel',id),
  diagnostics:()=>ipcRenderer.invoke('system:diagnostics'),
  installDependency:id=>ipcRenderer.invoke('system:install-dependency',id),
  provisionAll:()=>ipcRenderer.invoke('system:install-all-dependencies'),
  restartAsAdmin:()=>ipcRenderer.invoke('system:restart-admin'),
  getStartup:()=>ipcRenderer.invoke('system:get-startup'),
  setStartup:enabled=>ipcRenderer.invoke('system:set-startup',Boolean(enabled)),
  speechStatus:()=>ipcRenderer.invoke('speech:status'),
  transcribeAudio:(bytes,language='fa')=>ipcRenderer.invoke('speech:transcribe',{bytes,language}),
  synthesizeSpeech:(text,options={})=>ipcRenderer.invoke('speech:synthesize',{text,...options}),
  onEvent:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('agent:event',h);return()=>ipcRenderer.removeListener('agent:event',h);},
  onFocusInput:fn=>{const h=()=>fn();ipcRenderer.on('assistant:focus-input',h);return()=>ipcRenderer.removeListener('assistant:focus-input',h);},
  onAssistantResponse:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:response',h);return()=>ipcRenderer.removeListener('assistant:response',h);},
  onLocalAvatar:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:local-avatar',h);return()=>ipcRenderer.removeListener('assistant:local-avatar',h);},
  onBuiltInAvatar:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:built-in-avatar',h);return()=>ipcRenderer.removeListener('assistant:built-in-avatar',h);},
  onLocalMotion:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:local-motion',h);return()=>ipcRenderer.removeListener('assistant:local-motion',h);},
  onPlayMotion:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:play-motion',h);return()=>ipcRenderer.removeListener('assistant:play-motion',h);},
  onOpenSettings:fn=>{const h=(_e,v)=>fn(v||{});ipcRenderer.on('assistant:open-settings',h);return()=>ipcRenderer.removeListener('assistant:open-settings',h);},
  onPrefillPrompt:fn=>{const h=(_e,v)=>fn(v);ipcRenderer.on('assistant:prefill-prompt',h);return()=>ipcRenderer.removeListener('assistant:prefill-prompt',h);},
  onSurfaceOpening:fn=>{const h=()=>fn();ipcRenderer.on('assistant:surface-opening',h);return()=>ipcRenderer.removeListener('assistant:surface-opening',h);},
  onSurfaceClosing:fn=>{const h=()=>fn();ipcRenderer.on('assistant:surface-closing',h);return()=>ipcRenderer.removeListener('assistant:surface-closing',h);}
});
