import { isRemovedAvatarRecord } from '../main/RemovedAvatars.js';
const DB='black-clover-asset-library',STORE='items';
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('category','category');}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
async function tx(mode,fn){const db=await openDb();try{return await new Promise((resolve,reject)=>{const t=db.transaction(STORE,mode),s=t.objectStore(STORE);let out;Promise.resolve(fn(s)).then(v=>out=v).catch(reject);t.oncomplete=()=>resolve(out);t.onerror=()=>reject(t.error);t.onabort=()=>reject(t.error);});}finally{db.close();}}
const ext=name=>String(name||'').toLowerCase().match(/\.([a-z0-9]+)$/)?.[1]||'';
export async function importAsset(file,category='wardrobe'){if(!file)throw new Error('فایل انتخاب نشده.');const bytes=await file.arrayBuffer(),extension=ext(file.name),id=`${category}:${Date.now()}:${Math.random().toString(36).slice(2,8)}`;const direct=extension==='vrm'?'avatar':extension==='vrma'?'motion':null;const item={id,category,name:file.name,size:file.size,type:file.type||'',extension,direct,updatedAt:Date.now(),bytes};if(isRemovedAvatarRecord(item))throw new Error('این کاراکتر به درخواست شما حذف شده است.');await tx('readwrite',s=>s.put(item));return {...item,bytes:undefined};}
export async function listAssets(category=null){const all=await tx('readwrite',async s=>{const items=await request(s.getAll());for(const item of items||[])if(isRemovedAvatarRecord(item))s.delete(item.id);return (items||[]).filter(x=>!isRemovedAvatarRecord(x));});return (all||[]).filter(x=>!category||x.category===category).sort((a,b)=>b.updatedAt-a.updatedAt).map(({bytes,...x})=>x);}
export async function getAssetFile(id){const item=await tx('readonly',async s=>request(s.get(id)));if(isRemovedAvatarRecord(item)){await removeAsset(id);return null;}if(!item?.bytes)return null;return new File([item.bytes],item.name,{type:item.type||'application/octet-stream'});}
export async function removeAsset(id){await tx('readwrite',s=>s.delete(id));}
