import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { VRMLoaderPlugin,VRMUtils } from '@pixiv/three-vrm';
import { VRMAnimationLoaderPlugin,createVRMAnimationClip } from '@pixiv/three-vrm-animation';
import { getCurrentAvatarUrl,saveCurrentAvatar } from './avatarStorage.js';
import { getMotionUrl,listMotions } from './motionStorage.js';

const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smooth=(current,target,speed,dt)=>THREE.MathUtils.lerp(current,target,1-Math.exp(-speed*dt));
const EMOTIONS={neutral:{happy:0,angry:0,sad:0,surprised:0,relaxed:.02},happy:{happy:.52,relaxed:.12},angry:{angry:.46},sad:{sad:.48,relaxed:.05},surprised:{surprised:.58},shy:{happy:.2,relaxed:.18}};
const EXPRESSION_ALIASES={mouth:['aa','a','A'],blink:['blink','Blink'],happy:['happy','joy','Joy'],angry:['angry','Angry'],sad:['sad','sorrow','Sorrow'],surprised:['surprised','Surprised'],relaxed:['relaxed','fun','Fun']};

function makeLoader(){const loader=new GLTFLoader();loader.register(parser=>new VRMLoaderPlugin(parser));loader.register(parser=>new VRMAnimationLoaderPlugin(parser));return loader;}
function resolveExpression(manager,names){if(!manager)return null;for(const name of names){try{if(manager.getExpression?.(name))return name;const v=manager.getValue?.(name);if(v!==null&&v!==undefined)return name;}catch{}}return null;}
function frameModel(camera,scene){const box=new THREE.Box3().setFromObject(scene);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),height=Math.max(size.y,.8);camera.position.set(center.x,center.y+height*.02,center.z+Math.max(2.65,height*1.92));camera.lookAt(center.x,center.y+height*.02,center.z);camera.updateProjectionMatrix();}

export async function mountAvatar(host){
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(28,1,.1,30),renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});camera.position.set(0,1.35,3.3);renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;host.appendChild(renderer.domElement);
  scene.add(new THREE.HemisphereLight(0xffffff,0x202030,2.3));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(1,2,2);scene.add(key);const rim=new THREE.DirectionalLight(0x8397ff,.9);rim.position.set(-2,1,-1);scene.add(rim);
  let vrm=null,head=null,chest=null,hips=null,hipsBaseY=0,mixer=null,currentAction=null,idleMotionId=null,revokeAvatarUrl=()=>{},expressionNames={};
  const state={mode:'idle',emotion:'neutral',emotionUntil:0,mouth:0,blink:0,nextBlink:performance.now()+1800+Math.random()*2600,pointerX:0,pointerY:0,lastPulse:0,expressions:{},motion:null,motionUntil:0};
  const stopMotion=(fade=.22)=>{if(currentAction){try{currentAction.fadeOut(fade);}catch{}currentAction=null;}state.motion=null;state.motionUntil=0;host.dataset.motion='';};
  const disposeModel=()=>{stopMotion(0);mixer?.stopAllAction();mixer=null;if(!vrm)return;scene.remove(vrm.scene);try{VRMUtils.deepDispose?.(vrm.scene);}catch{}vrm=null;head=null;chest=null;hips=null;hipsBaseY=0;expressionNames={};};
  const prepareModel=loaded=>{disposeModel();vrm=loaded.userData.vrm;if(!vrm)throw new Error('این فایل VRM قابل خواندن نیست.');VRMUtils.removeUnnecessaryVertices(vrm.scene);VRMUtils.combineSkeletons(vrm.scene);try{VRMUtils.removeUnnecessaryJoints?.(vrm.scene);}catch{}try{VRMUtils.rotateVRM0?.(vrm);}catch{}
    vrm.scene.traverse(o=>o.frustumCulled=false);scene.add(vrm.scene);head=vrm.humanoid?.getNormalizedBoneNode('head');chest=vrm.humanoid?.getNormalizedBoneNode('chest');hips=vrm.humanoid?.getNormalizedBoneNode('hips');hipsBaseY=hips?.position.y||0;if(vrm.lookAt)vrm.lookAt.autoUpdate=false;mixer=new THREE.AnimationMixer(vrm.scene);mixer.addEventListener('finished',()=>{stopMotion(.12);host.dispatchEvent(new CustomEvent('blackclover:motion-ended'));if(idleMotionId)setTimeout(()=>playMotion(idleMotionId,{loop:true,fade:.18}).catch(()=>{}),140);});const manager=vrm.expressionManager;expressionNames=Object.fromEntries(Object.entries(EXPRESSION_ALIASES).map(([k,n])=>[k,resolveExpression(manager,n)]));frameModel(camera,vrm.scene);host.classList.remove('avatar-missing');host.classList.add('avatar-ready');delete host.dataset.error;host.dispatchEvent(new CustomEvent('blackclover:avatar-loaded',{detail:{meta:vrm.meta||{},expressions:expressionNames}}));if(idleMotionId)setTimeout(()=>setIdleMotion(idleMotionId).catch(()=>{}),180);};
  const loadUrl=async(url,{revoke=()=>{}}={})=>{host.classList.add('avatar-loading');try{const gltf=await makeLoader().loadAsync(url);revokeAvatarUrl();revokeAvatarUrl=revoke;prepareModel(gltf);return true;}finally{host.classList.remove('avatar-loading');}};
  const loadSavedOrFallback=async()=>{try{const stored=await getCurrentAvatarUrl();if(stored.url){await loadUrl(stored.url,{revoke:stored.revoke});return;}}catch(e){console.warn('Stored avatar load failed:',e);}try{await loadUrl('/models/Model_MOSO.vrm');}catch{host.classList.add('avatar-missing');host.dataset.error='یک فایل VRM برای ماریا انتخاب کن';}};
  const loadFile=async(file,{persist=true}={})=>{if(persist)await saveCurrentAvatar(file);const url=URL.createObjectURL(file);try{await loadUrl(url,{revoke:()=>URL.revokeObjectURL(url)});return {ok:true,name:file.name,size:file.size};}catch(e){URL.revokeObjectURL(url);throw e;}};
  const loadBuiltIn=async(url)=>{await loadUrl(url);return {ok:true,url};};
  const playMotion=async(id,{loop=false,fade=.25}={})=>{if(!vrm||!mixer)throw new Error('اول یک شخصیت VRM بارگذاری کن.');const stored=await getMotionUrl(id);if(!stored)throw new Error(`حرکت «${id}» نصب نشده.`);try{const gltf=await makeLoader().loadAsync(stored.url),animation=gltf.userData.vrmAnimations?.[0];if(!animation)throw new Error('VRMA قابل خواندن نیست.');const clip=createVRMAnimationClip(animation,vrm);if(!clip)throw new Error('تبدیل حرکت برای این مدل ممکن نشد.');if(currentAction)currentAction.fadeOut(fade);const action=mixer.clipAction(clip);action.reset();action.enabled=true;action.clampWhenFinished=!loop;action.setLoop(loop?THREE.LoopRepeat:THREE.LoopOnce,loop?Infinity:1);action.fadeIn(fade).play();currentAction=action;state.motion=id;state.motionUntil=performance.now()+Math.max(400,clip.duration*1000+500);host.dataset.motion=id;host.dispatchEvent(new CustomEvent('blackclover:motion-started',{detail:{id,duration:clip.duration,name:stored.info.name}}));return {id,duration:clip.duration};}finally{stored.revoke();}};
  const setIdleMotion=async id=>{idleMotionId=id||null;if(!idleMotionId)return;await playMotion(idleMotionId,{loop:true,fade:.18});};
  const expression=(key,value)=>{const name=expressionNames[key];if(!name)return;try{vrm?.expressionManager?.setValue(name,clamp(value));}catch{}};
  const setMode=mode=>{state.mode=mode||'idle';host.dataset.avatarState=state.mode;};const setEmotion=(emotion='neutral',duration=3200)=>{state.emotion=EMOTIONS[emotion]?emotion:'neutral';state.emotionUntil=performance.now()+Math.max(0,duration);host.dataset.emotion=state.emotion;};
  const observer=new MutationObserver(()=>setMode(host.dataset.voiceState||'idle'));observer.observe(host,{attributes:true,attributeFilter:['data-voice-state']});setMode(host.dataset.voiceState||'idle');host.addEventListener('blackclover:emotion',e=>setEmotion(e.detail?.emotion,e.detail?.duration));host.addEventListener('blackclover:motion',e=>playMotion(e.detail?.id,e.detail||{}).catch(err=>host.dispatchEvent(new CustomEvent('blackclover:motion-error',{detail:{error:err.message}}))));host.addEventListener('blackclover:voice-pulse',()=>{state.lastPulse=performance.now();state.mouth=Math.max(state.mouth,.72+Math.random()*.22);});host.addEventListener('pointermove',e=>{const r=host.getBoundingClientRect();state.pointerX=clamp((e.clientX-r.left)/Math.max(r.width,1),0,1)*2-1;state.pointerY=clamp((e.clientY-r.top)/Math.max(r.height,1),0,1)*2-1;});host.addEventListener('pointerleave',()=>{state.pointerX=0;state.pointerY=0;});
  const resize=()=>{const w=Math.max(host.clientWidth,1),h=Math.max(host.clientHeight,1);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host);resize();
  let alive=true,last=performance.now();function frame(now){if(!alive)return;requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;const t=now/1000;if(vrm){if(state.emotion!=='neutral'&&now>state.emotionUntil)setEmotion('neutral',0);if(now>=state.nextBlink){state.blink=1;state.nextBlink=now+2200+Math.random()*4200;}state.blink=Math.max(0,state.blink-dt*7.5);expression('blink',Math.sin(clamp(state.blink)*Math.PI));const speaking=state.mode==='speaking',listening=state.mode==='listening',targets=EMOTIONS[state.emotion]||EMOTIONS.neutral;for(const name of ['happy','angry','sad','surprised','relaxed']){const extra=name==='happy'?(speaking?.06:listening?.035:0):0,target=clamp((targets[name]||0)+extra);state.expressions[name]=smooth(state.expressions[name]||0,target,5,dt);expression(name,state.expressions[name]);}const pulseAge=now-state.lastPulse,mouthTarget=speaking?(pulseAge<240?state.mouth:.18+.12*(Math.sin(t*11)+1)):0;state.mouth=smooth(state.mouth,mouthTarget,speaking?13:18,dt);expression('mouth',state.mouth);
      const motionActive=Boolean(currentAction&&state.motion);if(!motionActive){const breathe=Math.sin(t*1.65)*.012,bob=Math.sin(t*.72)*.008;if(chest){chest.rotation.x=smooth(chest.rotation.x,breathe+(speaking?.012:0),3,dt);chest.rotation.z=smooth(chest.rotation.z,Math.sin(t*.55)*.006,3,dt);}if(hips)hips.position.y=smooth(hips.position.y,hipsBaseY+bob,4,dt);if(head){const emotionTilt=state.emotion==='shy'?.035:state.emotion==='sad'?.025:0,tx=(-state.pointerY*.055)+(listening?.025:0)+emotionTilt+Math.sin(t*.43)*.008,ty=(-state.pointerX*.09)+Math.sin(t*.31)*.012;head.rotation.x=smooth(head.rotation.x,tx,3.8,dt);head.rotation.y=smooth(head.rotation.y,ty,3.8,dt);head.rotation.z=smooth(head.rotation.z,speaking?Math.sin(t*.8)*.012:state.emotion==='shy'?.025:0,3,dt);}}mixer?.update(dt);vrm.update(dt);}renderer.render(scene,camera);}requestAnimationFrame(frame);await loadSavedOrFallback();
  return {loadFile,loadBuiltIn,playMotion,setIdleMotion,listMotions,setMode,setEmotion,dispose(){alive=false;observer.disconnect();ro.disconnect();disposeModel();revokeAvatarUrl();renderer.dispose();host.replaceChildren();}};
}
