import './dashboard.css';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{try{return new Intl.DateTimeFormat('fa-IR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d));}catch{return d||'';}};
function mount(){const actions=document.querySelector('.header-actions');if(!actions||document.querySelector('#organizerBtn'))return;const btn=document.createElement('button');btn.id='organizerBtn';btn.className='icon-btn organizer-btn';btn.title='یادآورها و متن‌های مهم';btn.innerHTML='<span>✦</span>';actions.prepend(btn);const root=document.createElement('div');root.id='organizer';root.className='organizer-backdrop';root.hidden=true;root.innerHTML=`<section class="organizer-panel"><header><div><h2>حافظهٔ روزمره ماریا</h2><p>یادآورها و متن‌های مهم؛ مستقل از مغز AI و ماندگار بعد از خاموش/روشن شدن.</p></div><button id="orgClose">×</button></header><nav><button data-tab="reminders" class="active">یادآورها</button><button data-tab="notes">متن‌های مهم</button></nav><div class="org-body"><section id="orgReminders"></section><section id="orgNotes" hidden></section></div></section>`;document.body.append(root);const remindersEl=root.querySelector('#orgReminders'),notesEl=root.querySelector('#orgNotes');
async function renderReminders(){const items=await window.blackClover.remindersList(true);remindersEl.innerHTML=`<div class="org-toolbar"><button id="orgRefreshReminders">تازه‌سازی</button></div><div class="org-list">${items.length?items.map(x=>`<article class="org-card ${x.enabled?'active':'done'}"><div class="org-card-head"><b>${esc(x.title||x.message.slice(0,55))}</b><span>${esc(x.priority||'normal')}</span></div><p>${esc(x.message)}</p><small>${fmt(x.dueAt)}${x.intervalMinutes?` • هر ${x.intervalMinutes} دقیقه`:''} • ${esc(x.status||'')}</small><div class="org-card-actions">${x.enabled?`<button data-snooze="${x.id}">۱۰ دقیقه بعد</button><button data-complete="${x.id}">انجام شد</button><button data-cancel="${x.id}">لغو</button>`:''}</div></article>`).join(''):'<div class="org-empty">یادآوری‌ای ثبت نشده.</div>'}</div>`;remindersEl.querySelector('#orgRefreshReminders')?.addEventListener('click',renderReminders);remindersEl.querySelectorAll('[data-snooze]').forEach(b=>b.onclick=async()=>{await window.blackClover.reminderSnooze(b.dataset.snooze,10);renderReminders();});remindersEl.querySelectorAll('[data-complete]').forEach(b=>b.onclick=async()=>{await window.blackClover.reminderComplete(b.dataset.complete);renderReminders();});remindersEl.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await window.blackClover.reminderCancel(b.dataset.cancel);renderReminders();});}
async function renderNotes(){const items=await window.blackClover.notesList(false);notesEl.innerHTML=`<form id="noteForm" class="note-form"><input id="noteTitle" placeholder="عنوان کوتاه"/><textarea id="noteText" placeholder="متن مهم، پرامپت، لینک، نکته…"></textarea><button>پین کن</button></form><div class="org-list note-grid">${items.length?items.map(x=>`<article class="org-card note-card" data-note="${x.id}"><div class="org-card-head"><b>${esc(x.title)}</b><span>${x.pinned?'پین':'عادی'}</span></div><p>${esc(x.text)}</p><small>${fmt(x.updatedAt)}</small><div class="org-card-actions"><button data-toggle-pin="${x.id}">${x.pinned?'برداشتن پین':'پین'}</button><button data-archive="${x.id}">آرشیو</button></div></article>`).join(''):'<div class="org-empty">متن مهمی پین نشده.</div>'}</div>`;const form=notesEl.querySelector('#noteForm');form.onsubmit=async e=>{e.preventDefault();const title=notesEl.querySelector('#noteTitle').value,text=notesEl.querySelector('#noteText').value;if(!text.trim()&&!title.trim())return;await window.blackClover.noteCreate({title,text,pinned:true});renderNotes();};notesEl.querySelectorAll('[data-toggle-pin]').forEach(b=>b.onclick=async e=>{e.preventDefault();const card=b.closest('[data-note]'),item=items.find(x=>x.id===card.dataset.note);await window.blackClover.noteUpdate(item.id,{pinned:!item.pinned});renderNotes();});notesEl.querySelectorAll('[data-archive]').forEach(b=>b.onclick=async e=>{e.preventDefault();await window.blackClover.noteArchive(b.dataset.archive);renderNotes();});}
async function open(tab='reminders'){root.hidden=false;for(const b of root.querySelectorAll('nav button'))b.classList.toggle('active',b.dataset.tab===tab);remindersEl.hidden=tab!=='reminders';notesEl.hidden=tab!=='notes';if(tab==='reminders')await renderReminders();else await renderNotes();}
btn.onclick=()=>open();root.querySelector('#orgClose').onclick=()=>{root.hidden=true;};root.addEventListener('click',e=>{if(e.target===root)root.hidden=true;});root.querySelectorAll('nav button').forEach(b=>b.onclick=()=>open(b.dataset.tab));window.addEventListener('blackclover:open-organizer',e=>open(e.detail?.tab||'reminders'));}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(mount,0));else setTimeout(mount,0);
