const cleanForSpeech=text=>String(text??'').replace(/https?:\/\/\S+/gi,' لینک ').replace(/[`*_#>|~]/g,' ').replace(/\b([A-Z]{2,})\b/g,m=>m.split('').join(' ')).replace(/\s*([،؛:!?؟.])\s*/g,'$1 ').replace(/\s+/g,' ').trim();
const scoreVoice=v=>{let score=0;const lang=String(v.lang||'').toLowerCase(),name=String(v.name||'').toLowerCase();if(lang==='fa-ir')score+=140;else if(lang.startsWith('fa'))score+=110;else return -1000;if(/female|woman|زن|dilara|heera|ava|aria|natural|neural/.test(name))score+=30;if(/natural|neural|online/.test(name))score+=12;if(v.localService)score+=5;return score;};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,Number(v)));
const splitSpeech=text=>{const parts=cleanForSpeech(text).match(/[^.!?؟\n]+[.!?؟]?/g)||[],out=[];for(const raw of parts){let s=raw.trim();while(s.length>240){let i=Math.max(s.lastIndexOf('،',220),s.lastIndexOf(' ',220));if(i<90)i=220;out.push(s.slice(0,i+1).trim());s=s.slice(i+1).trim();}if(s)out.push(s);}return out.length?out:[cleanForSpeech(text)];};
const base64Url=(mime,b64)=>`data:${mime};base64,${b64}`;

export class VoiceController extends EventTarget{
  constructor(){super();this.enabled=localStorage.getItem('blackClover:speech')!=='off';this.rate=Number(localStorage.getItem('blackClover:voiceRate')||1.03);this.pitch=Number(localStorage.getItem('blackClover:voicePitch')||1.05);this.volume=Number(localStorage.getItem('blackClover:voiceVolume')||1);this.engine=localStorage.getItem('blackClover:voiceEngine')||'auto';this.speaking=false;this.generation=0;this.voices=[];this.preferredVoice=localStorage.getItem('blackClover:voiceName')||'';this.audio=null;this.pulseTimer=null;this.localStatus=null;this.refreshVoices();globalThis.speechSynthesis?.addEventListener?.('voiceschanged',()=>this.refreshVoices());this.refreshLocalStatus();}
  async refreshLocalStatus(){try{this.localStatus=await window.blackClover?.speechStatus?.();}catch{this.localStatus=null;}this.dispatchEvent(new CustomEvent('engines',{detail:{local:this.localStatus,engine:this.engine}}));return this.localStatus;}
  refreshVoices(){this.voices=globalThis.speechSynthesis?.getVoices?.()||[];this.dispatchEvent(new CustomEvent('voices',{detail:{voices:this.voices,voice:this.bestVoice()}}));}
  bestVoice(){const exact=this.voices.find(v=>v.name===this.preferredVoice&&scoreVoice(v)>0);if(exact)return exact;const ranked=[...this.voices].map(v=>({v,s:scoreVoice(v)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s);return ranked[0]?.v||null;}
  settings(){const v=this.bestVoice();return {enabled:this.enabled,rate:this.rate,pitch:this.pitch,volume:this.volume,engine:this.engine,voice:v?{name:v.name,lang:v.lang}:null,local:this.localStatus,available:this.voices.map(x=>({name:x.name,lang:x.lang,local:x.localService}))};}
  configure({rate,pitch,volume,voiceName,engine}={}){if(Number.isFinite(Number(rate))){this.rate=clamp(rate,.75,1.3);localStorage.setItem('blackClover:voiceRate',this.rate);}if(Number.isFinite(Number(pitch))){this.pitch=clamp(pitch,.75,1.3);localStorage.setItem('blackClover:voicePitch',this.pitch);}if(Number.isFinite(Number(volume))){this.volume=clamp(volume,0,1);localStorage.setItem('blackClover:voiceVolume',this.volume);}if(typeof voiceName==='string'){this.preferredVoice=voiceName;localStorage.setItem('blackClover:voiceName',voiceName);}if(['auto','system','local'].includes(engine)){this.engine=engine;localStorage.setItem('blackClover:voiceEngine',engine);}this.dispatchEvent(new CustomEvent('settings',{detail:this.settings()}));}
  setEnabled(value){this.enabled=Boolean(value);localStorage.setItem('blackClover:speech',this.enabled?'on':'off');if(!this.enabled)this.stop('disabled');this.dispatchEvent(new CustomEvent('enabled',{detail:{enabled:this.enabled}}));}
  stop(reason='interrupted'){this.generation++;globalThis.speechSynthesis?.cancel?.();if(this.audio){try{this.audio.pause();this.audio.src='';}catch{}this.audio=null;}if(this.pulseTimer){clearInterval(this.pulseTimer);this.pulseTimer=null;}if(this.speaking){this.speaking=false;this.dispatchEvent(new CustomEvent('state',{detail:{state:'idle',reason}}));}}
  async speakLocal(text,generation){const status=this.localStatus||await this.refreshLocalStatus();if(!status?.localTts||!window.blackClover?.synthesizeSpeech)return false;const r=await window.blackClover.synthesizeSpeech(cleanForSpeech(text),{rate:this.rate,volume:this.volume});if(generation!==this.generation||!r?.audio)return false;const audio=new Audio(base64Url(r.mime||'audio/wav',r.audio));this.audio=audio;audio.volume=clamp(this.volume,0,1);audio.playbackRate=1;await new Promise((resolve,reject)=>{audio.onended=resolve;audio.onerror=()=>reject(new Error('Local audio playback failed'));audio.onplay=()=>{if(generation!==this.generation)return;this.speaking=true;this.dispatchEvent(new CustomEvent('state',{detail:{state:'speaking',engine:r.engine||'piper',text:r.text||text}}));this.pulseTimer=setInterval(()=>{if(generation===this.generation&&!audio.paused)this.dispatchEvent(new CustomEvent('boundary',{detail:{engine:'local'}}));},85);};audio.play().catch(reject);});if(this.pulseTimer){clearInterval(this.pulseTimer);this.pulseTimer=null;}if(this.audio===audio)this.audio=null;return true;}
  speakSystem(text,generation){if(!('speechSynthesis'in globalThis))return Promise.resolve(false);const chunks=splitSpeech(text).filter(Boolean);if(!chunks.length)return Promise.resolve(false);const voice=this.bestVoice();return new Promise(resolve=>{let index=0;const next=()=>{if(generation!==this.generation){resolve(false);return;}if(index>=chunks.length){resolve(true);return;}const chunk=chunks[index++],u=new SpeechSynthesisUtterance(chunk);u.lang=voice?.lang||'fa-IR';u.rate=clamp(this.rate,.75,1.3);u.pitch=clamp(this.pitch,.75,1.3);u.volume=clamp(this.volume,0,1);if(voice)u.voice=voice;u.onstart=()=>{if(generation!==this.generation)return;this.speaking=true;this.dispatchEvent(new CustomEvent('state',{detail:{state:'speaking',engine:'system',text:chunk,voice:voice?.name||null,chunk:index,total:chunks.length}}));};u.onboundary=e=>{if(generation===this.generation)this.dispatchEvent(new CustomEvent('boundary',{detail:{charIndex:e.charIndex,charLength:e.charLength||0,name:e.name||'',chunk:index,engine:'system'}}));};u.onend=next;u.onerror=e=>{if(['interrupted','canceled'].includes(e.error)){resolve(false);return;}next();};globalThis.speechSynthesis.speak(u);};next();});}
  async speak(text){if(!this.enabled)return false;const cleaned=cleanForSpeech(text);if(!cleaned)return false;this.stop('replace');const generation=++this.generation,systemVoice=this.bestVoice();try{let ok=false;if(this.engine==='local'||(this.engine==='auto'&&!systemVoice))ok=await this.speakLocal(cleaned,generation);if(!ok&&generation===this.generation)ok=await this.speakSystem(cleaned,generation);if(!ok&&this.engine==='system'&&generation===this.generation)ok=await this.speakLocal(cleaned,generation);if(generation===this.generation){this.speaking=false;this.dispatchEvent(new CustomEvent('state',{detail:{state:'idle',reason:'ended'}}));}return ok;}catch(e){if(generation!==this.generation)return false;try{const ok=await this.speakSystem(cleaned,generation);this.speaking=false;this.dispatchEvent(new CustomEvent('state',{detail:{state:'idle',reason:ok?'fallback-ended':'voice-error'}}));return ok;}catch{this.speaking=false;this.dispatchEvent(new CustomEvent('state',{detail:{state:'idle',reason:'voice-error'}}));return false;}}
  }
}
export const voice=new VoiceController();
